const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const M=require('../scripts/consumption-macro-model.js'),data=require('../data/consumption-macro/observations.json');
test('shared automatic history fills real gaps, preserves exact amounts and dates, attributes supplementary fields',()=>{
  const auto=require('../data/macro/automatic-series.json'),merged=M.mergeAutomatic(data,auto);
  assert.ok(M.records(merged,'cpi',{frequency:'monthly',basis:'month'}).length>=128);
  assert.ok(M.records(merged,'cpi').find(r=>r.period==='2025-02'));
  const missing=M.records(merged,'retail',{frequency:'monthly',basis:'month'}).find(r=>r.period==='2025-04');
  assert.ok(M.finite(missing.value));assert.equal(missing.yoy,5.1);assert.match(M.csv(merged,[missing]),/Choice/);
  const verified=M.records(merged,'retail',{frequency:'monthly',basis:'month'}).find(r=>r.period==='2026-08');assert.equal(verified.value,39824);assert.equal(merged.sources.find(s=>s.id===verified.sourceId).publishedAt,'2026-09-15');
  const historical=M.records(merged,'cpi').find(r=>r.period==='2016-01');assert.equal(merged.sources.find(s=>s.id===historical.sourceId).publishedAt,null);
  assert.equal(M.records(data,'retail').some(r=>r.period==='2025-04'),false);
  assert.ok(M.important.every(id=>merged.indicators.some(i=>i.id===id)));assert.equal(M.important.length,8);
});
test('unapproved, wrong units and wrong frequency automatic records fail closed',()=>{
  const auto=require('../data/macro/automatic-series.json');
  for(const mutate of [d=>d.publicRedistributionApproved=false,d=>d.series['consumer-cpi'].spec.unit='元',d=>d.series['consumer-cpi'].observations[0].period='2016-Q1',d=>d.series['consumer-cpi'].sourceUrl='https://choicew2z.eastmoney.com.evil.example/']){
    const bad=structuredClone(auto);mutate(bad);assert.throws(()=>M.mergeAutomatic(data,bad));
  }
});
test('official source integrity and independent release dates',()=>{assert.deepEqual(M.validate(data),[]);assert.equal(data.indicators.filter(i=>i.status==='connected').length,46);assert.equal(data.indicators.filter(i=>i.status==='pending').length,4);assert.equal(M.latest(data,'retail').value,39824);assert.equal(M.latest(data,'retail').yoy,.4);assert.equal(M.latest(data,'core_cpi').value,1);assert.equal(M.latest(data,'income_national').value,22981);assert.equal(data.sources.find(s=>s.id==='household-2026-Q2').publishedAt,'2026-07-15');});
test('frequency filters never replace annual values with monthly or quarterly values',()=>{assert.equal(M.latest(data,'retail','annual').period,'2025');assert.equal(M.latest(data,'retail','monthly').period,'2026-08');assert.equal(M.latest(data,'income_national','quarterly').basis,'ytd');assert.equal(M.latest(data,'income_national','monthly'),null);assert.ok(M.directory(data,{frequency:'quarterly'}).every(i=>M.records(data,i.id,{frequency:'quarterly'}).length));});
test('Jan-Feb combined records, missing months and cumulative resets are not interpolated',()=>{const rows=M.records(data,'retail',{frequency:'monthly',basis:'month'});assert.ok(!rows.some(r=>r.period.endsWith('-01')));assert.ok(rows.find(r=>r.period==='2026-02').basis==='jan_feb');assert.ok(!rows.some(r=>r.period==='2025-04'));const parts=M.segments(rows);assert.ok(!parts.some(part=>part.some(r=>r.period==='2025-03')&&part.some(r=>r.period==='2025-05')));const ytd=M.segments(M.records(data,'retail',{frequency:'monthly',basis:'ytd'}));assert.ok(ytd.every(part=>new Set(part.map(r=>r.period.slice(0,4))).size===1));});
test('new and legacy online retail definitions remain separate',()=>{assert.ok(M.records(data,'online_total').every(r=>r.period.startsWith('2026')));assert.ok(M.records(data,'online_total_legacy').every(r=>!r.period.startsWith('2026')));assert.equal(M.latest(data,'online_goods').basis,'ytd');assert.equal(M.latest(data,'online_total').value,134766);assert.equal(M.latest(data,'online_services').value,50571);});
test('confidence remains pending; travel estimates and rate-only series retain their meanings',()=>{assert.equal(M.latest(data,'confidence'),null);assert.equal(M.directory(data,{frequency:'holiday',status:'pending'}).length,3);const service=M.latest(data,'service_retail');assert.equal(service.value,4.9);assert.equal(service.yoy,null);const travel=M.latest(data,'holiday_travel');assert.equal(travel.quality,'estimate');assert.equal(travel.yoy,null);assert.match(travel.note,/日均同比/);const national=M.records(data,'holiday_trips').find(r=>r.period==='2025-国庆中秋');assert.equal(national.yoy,null);});
test('date intervals include boundaries and empty results are empty',()=>{const rows=M.records(data,'retail',{frequency:'monthly',basis:'month',from:'2026-08-31',to:'2026-08-31'});assert.equal(rows.length,1);assert.equal(M.records(data,'retail',{from:'2027-01-01'}).length,0);assert.equal(M.directory(data,{query:'不可能匹配的字符串'}).length,0);assert.ok(M.directory(data,{query:'化妆品'}).some(i=>i.id==='category_4'));});
test('invalid references, duplicates, fake domains and future releases fail validation',()=>{for(const mutate of [d=>d.observations.push({...d.observations[0]}),d=>d.observations[0].sourceId='missing',d=>d.observations[0].value='0',d=>d.sources[0].url='https://stats.gov.cn.evil.example/a',d=>d.sources[0].publishedAt='2099-01-01']){const bad=structuredClone(data);mutate(bad);assert.ok(M.validate(bad).length);}});
test('CSV uses BOM, quotes, metadata, empty nulls, real zero and formula protection',()=>{const d=structuredClone(data),r={...M.latest(d,'retail'),value:0,yoy:null,note:'=HYPERLINK("bad")'};const text=M.csv(d,[r]);assert.ok(text.startsWith('\ufeff'));assert.match(text,/"0","亿元",""/);assert.match(text,/"'=HYPERLINK\(""bad""\)"/);assert.match(text,/"2026-09-15"/);assert.match(text,/https:\/\/www.stats.gov.cn/);assert.equal(text.split('\r\n').length,2);});
test('shared navigation exposes consumption macro while preserving existing destinations',()=>{for(const page of ['index.html','industry.html','companies.html','research.html','quotes.html','macro.html','consumption-macro.html']){let nav;const document={body:{classList:{add(){}},dataset:{},prepend(el){nav=el;}},head:{append(){}},createElement(){return{};},querySelector(){return null;},querySelectorAll(){return[];}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../scripts/site-shell.js'),'utf8'),{document,location:{pathname:'/'+page,hash:''}});assert.doesNotMatch(nav.innerHTML,/consumption-macro.html/);assert.match(nav.innerHTML,/macro.html/);assert.match(nav.innerHTML,/行业数据/);assert.match(nav.innerHTML,/公司数据/);if(page==='consumption-macro.html')assert.equal(document.body.dataset.siteSection,'macro');}});
