const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const M=require('../scripts/dutyfree-holidays.js');
const d=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/dutyfree/holidays.json'),'utf8'));
const full=M.filter(d.records,'全部','全部');
assert.equal(full.length,35);
assert.equal(full.filter(r=>r.status==='available').length,35);
assert.equal(d.records.filter(r=>r.kind==='detail').length,30);
const newYear= M.filter(d.records,'元旦','2025')[0];
assert.equal(M.filter(d.records,'元旦','2026')[0].sales,7.12);
assert.equal(M.filter(d.records,'元旦','2026')[0].daily_sales,7.12/3);
assert.equal(newYear.days,1);
assert.ok(Math.abs(newYear.sales-1.29514963880289)<1e-12);
assert.equal(newYear.daily_sales,newYear.sales);
const calendar=d.records.find(r=>r.year===2025&&r.holiday==='元旦同日历三天');
assert.equal(calendar.days,3);
assert.ok(Math.abs(calendar.sales-3.1105286151157716)<1e-12);
assert.notEqual(newYear.sales,calendar.sales);
for(const r of full.filter(r=>r.status==='pending')){
  assert.equal(r.year,2026);for(const k of ['sales','shoppers','spend','daily_sales','daily_yoy'])assert.equal(r[k],null);
}
const spring=M.filter(d.records,'春节','2026')[0];
assert.equal(spring.days,9);assert.equal(spring.sales,27.2);assert.equal(spring.shoppers,32.5);
assert.ok(Math.abs(spring.daily_sales-27.2/9)<1e-12);
assert.ok(Math.abs(spring.daily_yoy-15.462167038098262)<1e-10);
assert.equal(M.filter(d.records,'国庆','全部').length,7);
assert.equal(M.filter(d.records,'国庆','2022')[0].daily_sales,null);
assert.equal(M.filter(d.records,'国庆','2022')[0].spend_yoy,null);
assert.ok(d.records.every(r=>r.web_source?.url||(r.source_cells.sales.cell&&r.sheet)));
const mid=M.filter(d.records,'中秋','2026')[0],national=M.filter(d.records,'国庆','2026')[0];
assert.equal(mid.sales,2.31);assert.equal(mid.shoppers,3.86);assert.equal(mid.days,3);assert.equal(mid.daily_sales,2.31/3);assert.equal(mid.daily_yoy,null);
assert.equal(national.sales,8.55);assert.equal(national.shoppers,12.3);assert.equal(national.days,7);assert.equal(national.daily_sales,8.55/7);
assert.equal(national.reported_shoppers_yoy,10.41);
assert.equal(national.items,69.68);assert.ok(national.additional_sources[0].url.includes('xinhuanet.com'));
assert.ok(Math.abs(national.daily_yoy-((8.55/7)/(9.44/8)-1)*100)<1e-10);
assert.equal(M.filter(d.records,'国庆','2026','detail')[0].sales,6.48);
assert.ok(mid.web_source.url.includes('2026/09-29'));assert.ok(national.web_source.url.includes('20261008'));
assert.ok(!d.records.some(r=>r.notes.some(n=>n.includes('假设2.1'))));
assert.equal(M.change(null,2),null);assert.equal(M.change(0,2),-100);assert.equal(M.change(2,0),null);
assert.equal(M.filter(d.records,'清明','2025').length,0);
const newYear2020=M.filter(d.records,'元旦','2020')[0],newYear2021=M.filter(d.records,'元旦','2021')[0];
assert.equal(newYear2020.days,1);assert.equal(newYear2020.sales,0.54);assert.equal(newYear2020.shoppers,1.71);
assert.equal(newYear2020.daily_sales,0.54);assert.equal(newYear2020.daily_yoy,null);
const oldCalendar=M.filter(d.records,'元旦','2020','detail').find(r=>r.holiday==='元旦同日历三天');
assert.equal(oldCalendar.days,3);assert.ok(Math.abs(oldCalendar.sales-1.8295161946063154)<1e-12);
assert.equal(newYear2021.reported_sales_yoy,195.16);
assert.ok(Math.abs(newYear2021.daily_yoy-(1.8/0.54-1)*100)<1e-10);
assert.equal(newYear2021.workbook_baseline.daily_yoy,195.16);
const dragon2023=M.filter(d.records,'端午','2023')[0],dragon2024=M.filter(d.records,'端午','2024')[0];
assert.equal(dragon2023.sales,2.6);assert.equal(dragon2023.shoppers,4.37);
assert.equal(dragon2023.daily_yoy,null);assert.ok(Math.abs(dragon2024.daily_yoy-(2.05/2.6-1)*100)<1e-10);
assert.ok(Math.abs(M.filter(d.records,'端午','2019')[0].sales-9526.61/10000)<1e-12);
const national2021=M.filter(d.records,'国庆','2021')[0];
assert.equal(national2021.reported_sales_yoy,66.9);
assert.ok(Math.abs(national2021.daily_yoy-((14.7/7)/(10.4/8)-1)*100)<1e-10);
assert.notEqual(national2021.daily_yoy,national2021.reported_sales_yoy);
assert.equal(M.filter(d.records,'清明','2026')[0].reported_shoppers_yoy,19.6);
assert.equal(M.filter(d.records,'端午','2026')[0].items,15.9);
assert.equal(M.filter(d.records,'五一','2026')[0].items,44.17);
assert.equal(new Set(d.records.map(r=>r.id)).size,d.records.length);
const D=require('../scripts/site-data.js'),compat=D.csv(fs.readFileSync(path.join(__dirname,'../data/dutyfree_holiday.csv'),'utf8'));
assert.equal(compat.length,full.length);
for(const r of full){
 const csv=compat.find(v=>Number(v.year)===r.year&&v.holiday===r.holiday);
 assert.ok(csv);assert.equal(Number(csv.sales_cny_100m),r.sales);
 assert.equal(csv.daily_sales_cny_100m===''?null:Number(csv.daily_sales_cny_100m),r.daily_sales);
 if(r.web_source?.checkedAt){assert.ok(r.web_source.locator);assert.ok(r.web_source.publishedAt<=r.web_source.checkedAt);}
}
console.log('Holiday data, missing-value handling, period separation and filters passed.');
// Exercise the actual browser download handler with a minimal DOM and Blob capture.
(async()=>{
  const vm=require('node:vm'),elements=new Map();let downloaded,downloadName;
  const element=id=>{if(!elements.has(id))elements.set(id,{parentElement:{},value:'combo'});return elements.get(id);};
  const context={SiteCharts:{paired:()=>({html:''})},window:{},document:{getElementById:element,createElement:()=>({click(){downloadName=this.download;}})},location:{pathname:'/industry.html',hash:'#dutyfree'},addEventListener(){},fetch:async()=>({ok:true,json:async()=>d}),Blob,URL:{createObjectURL(blob){downloaded=blob;return 'blob:test';},revokeObjectURL(){}},setTimeout(){},console};
  vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../scripts/dutyfree-holidays.js'),'utf8'),context);
  await new Promise(resolve=>setImmediate(resolve));
  element('dh-holiday').onchange({target:{value:'春节'}});element('dh-year').onchange({target:{value:'2026'}});element('dh-download').onclick();
  const text=await downloaded.text(),D=require('../scripts/site-data.js'),rows=D.csv(text);
  assert.equal(downloadName,'离岛免税-春节-2026.csv');assert.equal(rows.length,1);
  assert.equal(Number(rows[0]['销售额（亿元）']),27.2);assert.equal(Number(rows[0]['日均销售额（亿元）']),27.2/9);
  assert.ok(rows[0]['来源单元格'].includes('春节假期!C17'));assert.ok(rows[0]['原始文件或网页'].endsWith('.xlsx'));
  element('dh-holiday').onchange({target:{value:'中秋'}});element('dh-download').onclick();
  const midExport=D.csv(await downloaded.text())[0];assert.equal(Number(midExport['销售额（亿元）']),2.31);assert.equal(midExport['状态'],'available');assert.equal(midExport['原始文件或网页'],mid.web_source.url);
  element('dh-holiday').onchange({target:{value:'国庆'}});element('dh-download').onclick();
  const nationalExport=D.csv(await downloaded.text())[0];assert.equal(Number(nationalExport['销售额（亿元）']),8.55);assert.equal(Number(nationalExport['统计天数']),7);
  element('dh-holiday').onchange({target:{value:'清明'}});element('dh-download').onclick();
  const qingmingExport=D.csv(await downloaded.text())[0];
  assert.equal(Number(qingmingExport['购物件数（万件）']),22.42);
  assert.equal(Number(qingmingExport['原文购物人次同比（%）']),19.6);
  assert.equal(qingmingExport['来源发布日期'],'2026-04-07');
  element('dh-holiday').onchange({target:{value:'端午'}});element('dh-year').onchange({target:{value:'2024'}});
  assert.ok(element('dh-table').innerHTML.includes('-21.2%'));
  element('dh-metric').onchange({target:{value:'items'}});
  assert.ok(element('dh-chart-title').textContent.includes('购物件数'));
  element('dh-holiday').onchange({target:{value:'清明'}});element('dh-year').onchange({target:{value:'2025'}});
  assert.equal(element('dh-download').disabled,true);
  assert.ok(element('dh-coverage').textContent.includes('2025年清明'));
  console.log('Browser CSV download handler exports exact values and per-record workbook or web sources.');
})().catch(error=>{console.error(error);process.exitCode=1;});
