const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.csv':'text/csv; charset=utf-8'};
const server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://local/').pathname);const file=path.resolve(ROOT,'.'+name);if(!file.startsWith(ROOT+path.sep)){res.writeHead(403);res.end();return;}try{const data=fs.readFileSync(file);res.writeHead(200,{'Content-Type':types[path.extname(file)]||'text/plain'});res.end(data);}catch(e){res.writeHead(404);res.end('Not found');}});
async function main(){await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});try{
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{const NativeDate=Date;class FixedDate extends NativeDate{constructor(...args){super(...(args.length?args:['2026-10-10T00:00:00Z']));}static now(){return new NativeDate('2026-10-10T00:00:00Z').getTime();}}window.Date=FixedDate;});
await page.goto(origin+'/earnings.html');await page.waitForSelector('#content:not([hidden])');assert.equal(await page.locator('#coverageCount').innerText(),'32');assert.equal(await page.locator('#scheduledCount').innerText(),'11');assert.equal(await page.locator('#unknownCount').innerText(),'21');assert.equal(await page.locator('#grid .ec-day').count(),42);assert.match(await page.locator('.site-nav a[aria-current=page]').innerText(),/财报日历/);
await page.selectOption('#lead','30');assert.equal(await page.locator('#reminders button').count(),11);if(process.env.SCREENSHOT_DIR){fs.mkdirSync(process.env.SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'财报日历-桌面.png'),fullPage:true});}
await page.click('[data-view=week]');assert.equal(await page.locator('#grid .ec-day').count(),7);await page.click('[data-view=list]');assert.equal(await page.locator('#rows tr').count(),32);
await page.fill('#search','601888');assert.equal(await page.locator('#rows tr').count(),1);await page.click('#rows [data-record]');await page.waitForSelector('dialog[open]');assert.match(await page.locator('#detailBody').innerText(),/2026-10-31/);assert.match(await page.locator('#detailBody').innerText(),/实际披露日\s*待公布/);await page.click('#watchCompany');await page.keyboard.press('Escape');await page.selectOption('#scope','watch');await page.fill('#search','');assert.equal(await page.locator('#rows tr').count(),1);await page.reload();await page.waitForSelector('#content:not([hidden])');assert.equal(await page.locator('#scope').inputValue(),'watch');assert.equal(await page.locator('#rows tr').count(),1);
await page.click('#reset');await page.selectOption('#period','2026H1');assert.equal(await page.locator('#disclosedCount').innerText(),'30');await page.fill('#search','海底捞');await page.click('#rows [data-record]');assert.match(await page.locator('#detailBody').innerText(),/通知发布 2026-08-12/);const official=await page.locator('#detailBody a').first().getAttribute('href');assert.match(official,/hkexnews.hk/);await page.keyboard.press('Escape');await page.click('#reset');await page.selectOption('#kind','forecast');assert.equal(await page.locator('#rows tr').count(),1);assert.match(await page.locator('#rows').innerText(),/已公告/);
await page.click('#reset');await page.check('#history');assert.equal(await page.locator('#rows tr').count(),50);assert.equal(await page.locator('#more').isVisible(),true);await page.click('#more');assert.equal(await page.locator('#rows tr').count(),74);
const download=page.waitForEvent('download');await page.click('#csv');assert.match((await download).suggestedFilename(),/\.csv$/);
await page.click('#reset');await page.selectOption('#period','2026Q3');const ics=page.waitForEvent('download');await page.click('#ics');assert.match((await ics).suggestedFilename(),/\.ics$/);
await page.selectOption('#period','2026FY');assert.equal(await page.locator('#unknownCount').innerText(),'32');assert.equal(await page.locator('#scheduledCount').innerText(),'0');await page.fill('#search','<script>alert(1)</script>');assert.match(await page.locator('#rows').innerText(),/没有匹配记录/);assert.equal(await page.locator('script:not([src])').count(),0);
await page.click('#reset');await page.selectOption('#period','2026Q3');await page.click('[data-view=month]');
await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);assert.equal(await page.locator('.site-nav a[href="earnings.html"]').isVisible(),true);if(process.env.SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'财报日历-手机.png'),fullPage:true});
await page.click('[data-view=week]');assert.equal(await page.locator('#grid .ec-day').count(),7);await page.click('[data-view=list]');await page.fill('#search','601888');await page.click('#rows [data-record]');await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);
const failure=await context.newPage();let broken=true;await failure.route('**/data/earnings-calendar.json',route=>broken?route.fulfill({status:503,body:'unavailable'}):route.continue());await failure.goto(origin+'/earnings.html');await failure.waitForSelector('#error:not([hidden])');assert.equal(await failure.locator('#content').isVisible(),false);broken=false;await failure.click('#retry');await failure.waitForSelector('#content:not([hidden])');
assert.deepEqual(errors,[]);await context.close();console.log('PASS: desktop/mobile month-week-list, filters, dates, provenance, watch persistence, URL restore, history pagination, downloads, empty state, keyboard and retry');
}finally{await browser.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
