const {test}=require('node:test');
const assert=require('node:assert/strict');
const F=require('../scripts/fedwatch-model.js');
const P=require('../scripts/prediction-model.js');
const snapshot={observedDate:'2026-10-08',probabilityUnit:'%',ranges:[{lower:3.5,upper:3.75,probability:0},{lower:3.75,upper:4,probability:82.8},{lower:4,upper:4.25,probability:17.2}]};
test('CME aggregates against policy without normalizing source values',()=>{assert.deepEqual(F.aggregate(snapshot,{range:[3.75,4]}),{cut:0,hold:82.8,hike:17.2});assert.equal(F.valid({...snapshot,ranges:snapshot.ranges.map(r=>({...r,probability:0}))}),false);assert.equal(F.valid({...snapshot,ranges:[{lower:3.5,upper:4,probability:50},{lower:3.75,upper:4.25,probability:50}]}),false);});
test('CME future observations and missing prior ranges are never shown as current or zero',()=>{assert.equal(F.snapshots({snapshots:[snapshot]},Date.parse('2026-10-07')).length,0);assert.equal(F.comparison(snapshot,{ranges:[snapshot.ranges[0]]})[1].change,null);assert.equal(F.aggregate(snapshot,{range:[3.8,4.05]}),null);});
test('Polymarket search retains all event choices and Chinese option names',()=>{const markets=[{id:'1',eventId:'event',eventComplete:true,category:'经济与利率',question:'hold',optionLabelZh:'维持不变',eventTitleZh:'美联储利率决策',endDate:'2026-12-01',outcomes:[{name:'Yes',probability:.8}]},{id:'2',eventId:'event',eventComplete:true,category:'经济与利率',question:'cut',optionLabelZh:'降息25基点',eventTitleZh:'美联储利率决策',endDate:'2026-12-01',outcomes:[{name:'Yes',probability:.2}]}];const groups=P.groups(markets,{query:'降息25',wholeEvents:true,now:Date.parse('2026-10-10')});assert.equal(groups.length,1);assert.equal(groups[0].markets.length,2);assert.equal(groups[0].title,'美联储利率决策');assert.equal(P.optionLabel(groups[0],markets[1]),'降息25基点');});

