'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const M=require('../scripts/gold-jewelry-model.js');
const original=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/gold-jewelry/observations.json'),'utf8'));
const clone=()=>structuredClone(original);
test('reviewed data retains ten-brand seed and unique dated close/average observations',()=>{assert.deepEqual(M.validate(original),[]);assert.equal(original.brands.length,10);assert.equal(original.quotes.filter(q=>q.id.endsWith('-20261008-jinjia')).length,10);assert.equal(original.benchmarks.find(b=>b.id==='sge-au9999-2026-09-28').price,900.89);assert.equal(original.benchmarks.find(b=>b.id==='sge-au9999-2026-09-30').price,907.32);assert.equal(M.benchmarkSeries(original.benchmarks,'close').length,22);assert.equal(M.benchmarkSeries(original.benchmarks,'weighted_average').length,22);});
test('calendar dates, nulls and NaN are not valid prices',()=>{assert.equal(M.validDate('2026-02-30'),false);assert.equal(M.numeric(null),false);for(const x of [null,NaN,Infinity,true,0]){const d=clone();d.quotes[0].price=x;assert.ok(M.validate(d).length);}});
test('missing brand/source, dates in future and duplicate rows are rejected',()=>{for(const mutate of [d=>delete d.quotes[0].brandId,d=>d.quotes[0].sourceId='missing',d=>d.quotes[0].quoteDate='2026-10-09',d=>d.quotes.push({...d.quotes[0],id:'duplicate'}),d=>d.benchmarks.push({...d.benchmarks[0],id:'duplicate'})]){const d=clone();mutate(d);assert.ok(M.validate(d).length);}});
test('aggregator cannot be promoted to primary and unknown fee status is not false',()=>{const d=clone();d.quotes[0].verification='verified_primary';assert.ok(M.validate(d).length);const e=clone();e.quotes[0].includesLabor='no';assert.ok(M.validate(e).length);});
test('September close never fills October 8 spread',()=>{for(const q of original.quotes)assert.equal(M.spread(q,original.benchmarks).value,null);});
// Synthetic numbers below are isolated TEST FIXTURES, not disclosure observations.
function fixture(){return [{brandId:'fixture',quoteDate:'2026-01-06',currency:'CNY',unit:'CNY/g',market:'CN',price:1100,purity:0.9999,includesTax:true,includesLabor:false,priceBasis:'posted_per_gram',verification:'verified_primary'},[{id:'fixture-benchmark',quoteDate:'2026-01-06',instrument:'Au99.99',priceType:'close',currency:'CNY',unit:'CNY/g',market:'CN',price:1000,purity:0.9999,verification:'primary'}]];}
test('same-date reference spread has explicit restrictions',()=>{const [q,b]=fixture();assert.equal(M.spread(q,b).value,100);assert.ok(Math.abs(M.spread(q,b).ratio-10)<1e-10);for(const patch of [{currency:'HKD'},{unit:'HKD/tael'},{market:'HK'},{quoteDate:'2026-01-07'},{verification:'pending_primary'},{priceBasis:'fixed_price'},{purity:null},{includesLabor:null},{includesTax:null}])assert.equal(M.spread({...q,...patch},b).value,null);assert.equal(M.spread(q,[...b,...b]).value,null);});
test('CSV keeps unknown values empty and protects spreadsheet formula strings',()=>{const out=M.csv([{brandName:'=HYPERLINK("test")',price:1249,purity:null,quoteDate:'2026-10-08'}]);assert.ok(out.includes('"\'=HYPERLINK'));assert.ok(out.includes('"1249"'));assert.ok(!out.includes('"null"'));});
const operations=JSON.parse(fs.readFileSync(path.join(__dirname,'../data/gold-jewelry/company-operations.json'),'utf8'));
test('operations retain official PDF identity, fiscal dates and scope',()=>{assert.deepEqual(M.validateOperations(operations),[]);const stores=operations.records.filter(r=>r.metric==='stores_end'&&r.periodEnd==='2026-03-31');assert.equal(stores.find(r=>r.channel==='全部').value,2880);assert.equal(stores.filter(r=>r.channel!=='全部').reduce((n,r)=>n+r.value,0),2880);assert.ok(operations.records.some(r=>r.metric==='sss_weight_yoy'&&r.value===-15));assert.ok(operations.records.some(r=>r.metric==='sss_amount_yoy'&&r.value===42));});
test('operations reject fake primary sources, impossible pages, negative end stores and duplicate scope',()=>{for(const change of [d=>d.sources[0].kind='aggregator',d=>d.records[0].pdfPage=999,d=>d.records[0].value=-1,d=>d.records[0].periodStart='2027-01-01',d=>d.records.push({...d.records[0],id:'different-id'})]){const d=structuredClone(operations);change(d);assert.ok(M.validateOperations(d).length);}});
test('official brand observation never overwrites third-party identity or enables a spread with unknown fees',()=>{const official=original.quotes.filter(r=>r.verification==='verified_primary');assert.equal(official.length,1);assert.equal(official[0].purity,.999);assert.equal(original.quotes.find(r=>r.id==='zlf-20261008-jinjia').verification,'pending_primary');assert.equal(M.spread(official[0],original.benchmarks).value,null);});
test('strict nullable fields and raw numeric CSV exports preserve unknowns',()=>{const d=clone();delete d.quotes[0].quoteTime;assert.ok(M.validate(d).length);assert.ok(M.tableCsv(['value','note'],[[-15,'@formula']]).includes('"-15","\'@formula"'));});
