'use strict';
const {chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),out=process.env.SITE_SCREENSHOT_DIR,results=[];
const server=http.createServer((req,res)=>{let file;try{file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));}catch{res.writeHead(400).end();return;}if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(file,(error,body)=>{if(error){res.writeHead(404).end();return;}res.writeHead(200,{'Content-Type':{'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'}[path.extname(file)]||'text/plain; charset=utf-8'}).end(body);});});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})});
 try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});await context.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue():route.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const file of fs.readdirSync(root).filter(f=>f.endsWith('.html'))){
   const start=Date.now(),before=errors.length;await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/'+file+(file==='database.html'?'#watch-assistant':''),{waitUntil:'domcontentloaded'});await page.waitForSelector('.site-nav');await page.waitForTimeout(['hotel-dashboard.html','company-database.html'].includes(file)?1800:600);
   assert.equal(await page.locator('.site-nav nav a').count(),7,file+' navigation');assert.equal(await page.locator('.site-nav').count(),1,file+' duplicate nav');assert.ok(await page.locator('h1:visible').count()>=1,file+' heading');assert.ok(await page.locator('.skip-link').count()>=1,file+' skip');
   for(const width of [1440,1024,768,390]){await page.setViewportSize({width,height:1000});await page.waitForTimeout(80);const dimensions=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(dimensions.scroll<=width+1,file+' overflow '+JSON.stringify(dimensions));if(out&&(width===1440||width===390)){fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,file.replace('.html','')+'-'+width+'.png'),fullPage:false});}}
   assert.deepEqual(errors.slice(before),[],file+' runtime errors');results.push({page:file,widths:[1440,1024,768,390],loadMs:Date.now()-start});console.log('PASS',file);
 }
 await page.setViewportSize({width:1440,height:1000});
 await page.goto(base+'/companies.html?company=601888.SH&sector=免税');await page.waitForURL(/quotes.html/);assert.equal(new URL(page.url()).searchParams.get('symbol'),'601888.SH');
 await page.goto(base+'/company-database.html?db=atour');await page.waitForSelector('#db-data:not([hidden])');assert.equal(await page.locator('#db-company-buttons button').count(),5);await page.locator('#db-rows [data-observation]').first().click();await page.waitForSelector('#db-source-dialog[open]');assert.match(await page.locator('#db-source-body').innerText(),/定位|单元格|来源/);await page.keyboard.press('Escape');assert.equal(await page.locator('dialog[open]').count(),0);const companyDownload=page.waitForEvent('download');await page.locator('#db-export').click();assert.match((await companyDownload).suggestedFilename(),/\.csv$/);await page.reload();await page.waitForSelector('#db-data:not([hidden])');assert.equal(new URL(page.url()).searchParams.get('db'),'atour');await page.locator('[data-db-company=juneyao]').click();await page.waitForSelector('#db-gap:not([hidden])');assert.equal(await page.locator('#db-data').isVisible(),false);
 let companyBroken=true;await page.route('**/data/companies/hotels/atour.json',route=>companyBroken?route.fulfill({status:503,body:'unavailable'}):route.continue());await page.goto(base+'/company-database.html?db=atour');await page.waitForSelector('#db-status button');companyBroken=false;await page.locator('#db-status button').click();await page.waitForSelector('#db-data:not([hidden])');await page.unroute('**/data/companies/hotels/atour.json');
 await page.goto(base+'/index.html?metric=revpar#sec-hotel');await page.waitForURL(/industry.html.*#hotel/);assert.equal(new URL(page.url()).searchParams.get('metric'),'revpar');
 await page.goto(base+'/industry.html#hotel');await page.waitForSelector('#content:not([hidden])');await page.locator('[data-years="1"]').click();await page.reload();await page.waitForSelector('#content:not([hidden])');assert.equal(await page.locator('[data-years="1"]').getAttribute('aria-pressed'),'true');
 await page.goto(base+'/dutyfree-dashboard.html');await page.waitForFunction(()=>document.querySelector('#hn-sales').textContent!=='—');await page.locator('[onclick="showSrc(\'provided_workbook_monthly\')"]').first().click();assert.equal(await page.locator('#srcmodal').evaluate(el=>el.open),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#srcmodal').evaluate(el=>el.open),false);await page.locator('[data-view=holidays]').click();assert.ok(await page.locator('#view-holidays').isVisible());
 await page.goto(base+'/dashboard.html?dataset=valuation');await page.waitForSelector('#table tbody tr');assert.equal(await page.locator('#table tbody tr').count(),32);await page.locator('#query').fill('不存在的名称');await page.waitForTimeout(200);assert.match(await page.locator('#table').innerText(),/暂无匹配/);await page.locator('#reset').click();assert.equal(await page.locator('#table tbody tr').count(),32);
 const jsonId=JSON.parse(fs.readFileSync(path.join(root,'data-manifest.json'),'utf8')).datasets.find(d=>d.file==='data/macro/snapshot.json').id;await page.locator('[data-dataset="'+jsonId+'"]').click();await page.waitForSelector('#json:not([hidden])');assert.equal(await page.locator('#export').isDisabled(),true);assert.ok(JSON.parse(await page.locator('#json').innerText()));
 let broken=true;await page.route('**/data/research/resource-index.json',route=>broken?route.fulfill({status:503,body:'unavailable'}):route.continue());await page.goto(base+'/search.html');await page.waitForSelector('#search-retry');broken=false;await page.locator('#search-retry').click();await page.waitForSelector('.resource-result');await page.unroute('**/data/research/resource-index.json');
 let csvBroken=true;await page.route(url=>decodeURI(url.pathname).endsWith('/商社-标的池与估值跟踪.csv'),route=>csvBroken?route.fulfill({status:503,body:'unavailable'}):route.continue());await page.goto(base+'/dashboard.html?dataset=valuation');await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('暂时无法'));csvBroken=false;await page.locator('#reload').click();await page.waitForSelector('#table tbody tr');
 assert.deepEqual(errors,[]);if(out)fs.writeFileSync(path.join(out,'全站浏览器验证.json'),JSON.stringify({pages:results,interactions:['retired company link redirects to coverage','legacy query routing','industry range restore','dutyfree sources and tabs','CSV and JSON datasets','empty and retry states'],externalNetwork:'blocked; quote network covered by recorded-response suite'},null,2));console.log('PASS: all page layouts and shared interaction regressions');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
