(function(root){
'use strict';
const KEY='sinolink-earnings-v1', MODEL={todo:'待更新',doing:'更新中',done:'已更新'};
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if(c==='\n'&&!quoted){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=c;}if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}const head=(rows.shift()||[]).map(x=>x.replace(/^\uFEFF/,'').trim());return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(head.map((h,i)=>[h,r[i]||''])));}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function validDate(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(v+'T00:00:00Z');return Number.isFinite(+d)&&d.toISOString().slice(0,10)===v;}
function validTime(v){return /^\d{4}-\d{2}-\d{2}T(?:[01]\d|2[0-3]):[0-5]\d$/.test(v)&&validDate(v.slice(0,10));}
function safeURL(v){try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch(e){return '';}}
function validateRecord(r){if(!r||typeof r!=='object'||Array.isArray(r))throw Error('记录格式错误');const out={};for(const k of ['expected','actual','meeting','meetingEnd','meetingUrl','sourceUrl','owner','deadline','model','minutes','questions','notes']){const v=r[k]??'';if(typeof v!=='string'||v.length>12000)throw Error('记录字段无效');if(v&&['expected','actual','deadline'].includes(k)&&!validDate(v))throw Error('日期无效');if(v&&['meeting','meetingEnd'].includes(k)&&!validTime(v))throw Error('会议时间无效');if(v&&['meetingUrl','sourceUrl'].includes(k)&&!safeURL(v))throw Error('链接仅支持 http / https');out[k]=v;}if(!['todo','doing','done',''].includes(out.model)||!['todo','done','na',''].includes(out.minutes))throw Error('进度无效');if(out.meetingEnd&&(!out.meeting||out.meetingEnd<=out.meeting))throw Error('会议结束时间必须晚于开始时间');if(r.complete!=null&&typeof r.complete!=='boolean')throw Error('完成状态无效');out.complete=r.complete===true;return out;}
function matches(r,view,day=today()){if(view==='pending')return !!r.actual&&r.actual<=day&&r.model!=='done';if(view==='done')return r.complete;if(view==='unknown')return !r.actual&&!r.expected;if(view==='overdue')return !!r.deadline&&r.deadline<day&&!r.complete;if(view==='week'){const t=Date.parse(r.meeting+'+08:00'),now=Date.now();return Number.isFinite(t)&&t>=now&&t<now+7*86400000;}return true;}
function csvCell(v){let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function icsText(v){return String(v||'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/[,;]/g,'\\$&');}
function calendar(records,period){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Sinolink//Earnings//CN','CALSCALE:GREGORIAN'];const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');for(const r of records){const events=[];const date=r.actual||r.expected;if(date)events.push({kind:'report',date,title:r.name+' 财报披露'+(r.actual?'':'（预约）')});if(r.deadline&&!r.complete)events.push({kind:'task',date:r.deadline,title:r.name+' 研究交付截止'});if(r.meeting)events.push({kind:'meeting',time:r.meeting,end:r.meetingEnd,title:r.name+' 业绩会'});for(const ev of events){lines.push('BEGIN:VEVENT','UID:'+r.code+'-'+period+'-'+ev.kind+'@sinolink-earnings','DTSTAMP:'+stamp,'SUMMARY:'+icsText(ev.title));if(ev.time){const utc=s=>new Date(s+'+08:00').toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');lines.push('DTSTART:'+utc(ev.time));if(ev.end)lines.push('DTEND:'+utc(ev.end));}else{lines.push('DTSTART;VALUE=DATE:'+ev.date.replace(/-/g,''));}lines.push('DESCRIPTION:'+icsText(period+'；负责人：'+(r.owner||'未分配')+'；'+(ev.kind==='meeting'?r.meetingUrl||'':'')),'END:VEVENT');}}lines.push('END:VCALENDAR');return lines.join('\r\n')+'\r\n';}
const api={parseCSV,validDate,validTime,validateRecord,matches,csvCell,calendar};if(typeof module==='object'&&module.exports){module.exports=api;return;}
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let pool=[],snapshot={records:[],updatedAt:''},records={},visible=[],editing='',storageFault=false;
const toast=message=>{$('toast').textContent=message;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',4500);};
function key(code){return $('period').value+'|'+code;}
function effective(c){const source=snapshot.records.find(r=>r.code===c.code&&r.period===$('period').value)||{};const local=records[key(c.code)]||{};return {...c,expected:'',actual:'',meeting:'',meetingEnd:'',meetingUrl:'',sourceUrl:'',model:'todo',minutes:'todo',complete:false,owner:'',deadline:'',questions:'',notes:'',...source,...local,code:c.code,name:c.name,source};}
function persist(next){if(storageFault){toast('原有记录读取异常；请先备份或恢复，避免覆盖原数据');return false;}try{localStorage.setItem(KEY,JSON.stringify({version:1,records:next}));records=next;return true;}catch(e){toast('保存失败：浏览器存储不可用或空间不足，请备份记录');return false;}}
function filterRows(all){return all.filter(r=>(!$('search').value||[r.name,r.code].some(s=>s.toLowerCase().includes($('search').value.toLowerCase())))&&(!$('sector').value||r.sector===$('sector').value)&&(!$('owner').value||r.owner.includes($('owner').value))&&matches(r,$('view').value));}
function render(){const all=pool.map(effective);for(const id of ['pending','week','overdue','done'])$(id).textContent=all.filter(r=>matches(r,id)).length;$('total').textContent=all.length;visible=filterRows(all);const next=r=>[r.deadline&&!r.complete?r.deadline:'',r.meeting?.slice(0,10),!r.actual?r.expected:''].filter(Boolean).sort()[0]||'9999';visible.sort((a,b)=>{const mode=$('sort').value;return mode==='name'?a.name.localeCompare(b.name,'zh'):mode==='report'?(b.actual||b.expected||'').localeCompare(a.actual||a.expected||''):next(a).localeCompare(next(b))||a.name.localeCompare(b.name,'zh');});$('count').textContent='当前 '+visible.length+' / '+all.length+' 家';$('rows').innerHTML=visible.length?visible.map(r=>{const report=r.actual||r.expected;const sourceLabel=r.actual===r.source.actual&&r.source.actual?'妙想 · 实际披露':r.actual?'手工 · 实际披露':r.expected?'手工 · 预约日期':'待核实';const overdue=matches(r,'overdue');return '<tr><td><strong>'+esc(r.name)+'</strong><small>'+esc(r.code)+' · '+esc(r.sector)+'</small></td><td>'+(report?esc(report):'<span class="badge">待核实</span>')+'<small>'+sourceLabel+'</small></td><td>'+(r.meeting?esc(r.meeting.replace('T',' ')):'<span class="badge">待登记</span>')+(safeURL(r.meetingUrl)?'<small><a target="_blank" rel="noopener" href="'+esc(safeURL(r.meetingUrl))+'">会议入口 ↗</a></small>':'')+'</td><td><span class="badge '+esc(r.model)+'">'+esc(MODEL[r.model]||MODEL.todo)+'</span><small>纪要：'+({todo:'待整理',done:'已整理',na:'不适用'}[r.minutes]||'待整理')+'</small></td><td><span class="badge '+(r.complete?'done':overdue?'warn':'')+'">'+(r.complete?'已完成':overdue?'逾期':'待跟进')+'</span><small>'+esc(r.deadline||'未设截止')+' · '+r.questions.split('\n').filter(x=>x.trim()).length+' 个问题</small></td><td>'+esc(r.owner||'未分配')+'</td><td><button class="manage" data-code="'+esc(r.code)+'">管理</button></td></tr>';}).join(''):'<tr><td class="empty" colspan="7">没有匹配的公司，请调整筛选条件。</td></tr>';}
function open(code){const r=effective(pool.find(c=>c.code===code));editing=code;$('editTitle').textContent=r.name;$('editPeriod').textContent=$('period').selectedOptions[0].textContent+' · '+r.code;$('sourceDetail').textContent=r.source.actual?'妙想查询快照：实际披露 '+r.source.actual+'；数据查询于 '+snapshot.updatedAt+'。下方可手工校正，原始日期保留在此。':'妙想尚未返回该报告期的有效披露日期；请依据公告补充。港股不默认设立三季报任务日期。';const form=$('editForm');for(const name of ['expected','actual','meeting','meetingEnd','meetingUrl','sourceUrl','owner','deadline','model','minutes','questions','notes'])form.elements[name].value=r[name]||(['model','minutes'].includes(name)?'todo':'');form.elements.complete.checked=r.complete;$('saveState').textContent='';$('editor').showModal();}
function download(content,name,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function validateBackup(payload){if(!payload||payload.version!==1||!payload.records||typeof payload.records!=='object'||Array.isArray(payload.records))throw Error('不是有效的工作台备份');const out={};for(const [k,r] of Object.entries(payload.records)){if(!/^20\d{2}(H1|Q3|FY)\|[A-Z0-9.]+$/.test(k))throw Error('备份报告期或代码无效');out[k]=validateRecord(r);}return out;}
$('rows').addEventListener('click',e=>{const b=e.target.closest('[data-code]');if(b)open(b.dataset.code);});$('close').onclick=()=>$('editor').close();
$('editForm').onsubmit=e=>{e.preventDefault();try{const form=e.currentTarget,r=Object.fromEntries(new FormData(form));r.complete=form.elements.complete.checked;const checked=validateRecord(r);if(persist({...records,[key(editing)]:checked})){$('editor').close();render();toast('已保存到当前浏览器');}}catch(err){$('saveState').textContent=err.message;}};
for(const id of ['period','sector','view','sort'])$(id).addEventListener('change',render);for(const id of ['search','owner'])$(id).addEventListener('input',render);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{$('view').value=b.dataset.view;render();});
$('backup').onclick=()=>{if(storageFault){download(localStorage.getItem(KEY)||'','财报季-原始记录备份.json','application/json');return;}download(JSON.stringify({version:1,exportedAt:new Date().toISOString(),records},null,2),'财报季-工作记录-'+today()+'.json','application/json');};$('restore').onclick=()=>$('backupFile').click();$('backupFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('备份不能超过 5 MB');const incoming=validateBackup(JSON.parse(await file.text()));if(!confirm('将恢复 '+Object.keys(incoming).length+' 条记录；同公司同报告期会被备份内容替换，其他记录保留。继续？'))return;storageFault=false;if(persist({...records,...incoming})){render();toast('备份恢复成功');}}catch(err){toast('恢复失败：'+err.message);}finally{e.target.value='';}};
$('csv').onclick=()=>{const heads=['公司','代码','报告期','板块','实际披露','预约披露','业绩会(北京时间)','会议结束','负责人','截止日期','模型进度','纪要','交付完成','待核实问题','备注'];const data=visible.map(r=>[r.name,r.code,$('period').value,r.sector,r.actual,r.expected,r.meeting,r.meetingEnd,r.owner,r.deadline,MODEL[r.model],r.minutes,r.complete?'是':'否',r.questions,r.notes]);download('\uFEFF'+[heads,...data].map(row=>row.map(csvCell).join(',')).join('\r\n'),'财报季-'+$('period').value+'.csv','text/csv;charset=utf-8');};$('calendar').onclick=()=>{if(!visible.some(r=>r.actual||r.expected||r.meeting||r.deadline&&!r.complete)){toast('当前清单还没有可导出的日期');return;}download(calendar(visible,$('period').value),'财报季-'+$('period').value+'.ics','text/calendar;charset=utf-8');};
async function fetchText(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(url,{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error('读取失败 '+r.status);return await r.text();}finally{clearTimeout(timer);}}
async function boot(){try{const saved=localStorage.getItem(KEY);if(saved)records=validateBackup(JSON.parse(saved));}catch(e){storageFault=true;toast('原有工作记录读取失败，请先备份原始记录后恢复');}try{const manifest=JSON.parse(await fetchText('data-manifest.json'));const path=manifest.datasets.find(x=>x.id==='valuation')?.file;if(!path)throw Error('未配置覆盖池');const [csv,seed]=await Promise.all([fetchText(path),fetchText('data/earnings-snapshot.json').catch(()=>null)]);pool=parseCSV(csv).filter(r=>r['证券代码']&&r['公司名称']).map(r=>({code:r['证券代码'],name:r['公司名称'],sector:r['子行业'],market:r['市场']}));if(seed)snapshot=JSON.parse(seed);$('sourceStatus').textContent=seed?'公开日期：东方财富妙想 MCP · 查询 '+snapshot.updatedAt+' · '+snapshot.records.length+' 条有效披露记录':'公开日期快照读取失败；可手工补充，个人记录不受影响';$('sector').innerHTML='<option value="">全部板块</option>'+[...new Set(pool.map(r=>r.sector))].map(s=>'<option>'+esc(s)+'</option>').join('');render();}catch(e){$('sourceStatus').textContent='数据加载失败，请刷新重试';$('rows').innerHTML='<tr><td colspan="7" class="empty">覆盖池加载失败。请检查网络后刷新。</td></tr>';}}
boot();
})(typeof window==='undefined'?globalThis:window);
