const assert=require('node:assert/strict'),fs=require('node:fs');
const M=require('./earnings-calendar-model.js'),D=require('./site-data.js'),U=require('./update-earnings-calendar.cjs');
const snapshot=M.validateSnapshot(JSON.parse(fs.readFileSync(__dirname+'/../data/earnings-calendar-archive.json','utf8'))),pool=D.csv(fs.readFileSync(__dirname+'/../data/商社-标的池与估值跟踪.csv','utf8')).map(r=>({code:r['证券代码'],name:r['公司名称'],sector:r['子行业'],market:r['市场']}));
assert.equal(pool.length,32);assert.equal(M.code('1179.HK'),'01179.HK');assert.equal(M.code('0780.HK'),'00780.HK');
assert.equal(M.validDate('2026-02-29'),false);assert.equal(M.validDate('2024-02-29'),true);
assert.equal(M.monthDays(2026,7).length,42);assert.equal(M.monthDays(2026,7)[0],'2026-07-27');assert.deepEqual(M.weekDays('2026-10-11'),['2026-10-05','2026-10-06','2026-10-07','2026-10-08','2026-10-09','2026-10-10','2026-10-11']);
const q3=M.rows(pool,snapshot,'2026Q3');assert.equal(q3.filter(r=>r.kind==='formal').length,32);assert.equal(q3.filter(r=>r.expected).length,11);assert.equal(q3.filter(r=>r.actual).length,0);assert.equal(q3.filter(r=>!r.expected&&r.kind==='formal').length,21);
const h1=M.rows(pool,snapshot,'2026H1');assert.equal(h1.filter(r=>r.actual).length,30);assert.equal(h1.filter(r=>r.code==='01179.HK'&&r.actual).length,1);
const ctm=h1.find(r=>r.code==='601888.SH'&&r.kind==='formal');assert.equal(ctm.actual,'2026-08-21');assert.equal(ctm.announcementDate,'2026-08-21');assert.equal(ctm.announcementPublishedAt,'2026-08-20 18:59:09');assert.match(ctm.url,/static.sse.com.cn/);
const hotpot=h1.find(r=>r.code==='06862.HK'&&r.kind==='formal');assert.equal(hotpot.expected,'2026-08-25');assert.equal(hotpot.reservations[0].announcedAt,'2026-08-12');assert.equal(M.eventsFor([hotpot],'announcement')[0].date,'2026-08-25');assert.equal(M.eventsFor([hotpot])[0].date,'2026-08-25');
const forecasts=snapshot.records.filter(r=>r.kind==='forecast');assert.ok(forecasts.length>0);assert.ok(forecasts.every(r=>!r.actual&&r.announcementDate&&r.url));assert.equal(M.status(forecasts[0],'2026-10-10'),'已公告');
assert.equal(M.status({kind:'formal',expected:'2026-10-09'},'2026-10-10'),'预约日已过');
assert.equal(M.upcoming(q3,'2026-10-10',7).length,0);assert.equal(M.upcoming(q3,'2026-10-10',30).length,11);
assert.equal(M.filter(q3,{search:'601888',today:'2026-10-10'}).length,1);assert.equal(M.filter(q3,{market:'港股',today:'2026-10-10'}).length,10);assert.equal(M.filter(q3,{watched:true,watch:['601888.SH'],today:'2026-10-10'}).length,1);
assert.equal(M.eventsFor([{kind:'formal',id:'unknown'}]).length,0);
assert.equal(M.url('javascript:alert(1)'), '');assert.equal(M.url('https://user:secret@example.com'),'');
const bad=structuredClone(snapshot);bad.records[0].actual='2027-01-01';assert.throws(()=>M.validateSnapshot(bad));const duplicate=structuredClone(snapshot);duplicate.records.push(duplicate.records[0]);assert.throws(()=>M.validateSnapshot(duplicate));const badForecast=structuredClone(snapshot);badForecast.records.find(r=>r.kind==='forecast').actual='2026-07-01';assert.throws(()=>M.validateSnapshot(badForecast));
const unsourced=structuredClone(snapshot);unsourced.records[0].sourceId='unknown';assert.throws(()=>M.validateSnapshot(unsourced));
const booked=q3.find(r=>r.code==='601888.SH');const change=structuredClone(booked);delete change.source;change.expected='2026-10-30';change.updatedAt='2026-10-10T08:30:00+08:00';const update={version:2,updatedAt:change.updatedAt,sources:[snapshot.sources.find(s=>s.id==='sse')],records:[change]};
const merged=U.mergeSnapshot(snapshot,update);assert.equal(merged.records.length,snapshot.records.length);assert.ok(merged.records.find(r=>r.id===change.id).history.some(h=>h.from==='2026-10-31'&&h.to==='2026-10-30'));
assert.throws(()=>U.mergeSnapshot(snapshot,{...update,records:[]}));const regression=structuredClone(ctm);regression.actual='';assert.throws(()=>U.mergeSnapshot(snapshot,{...update,records:[regression]}));
const ics=M.calendar([booked,hotpot,forecasts[0]],{today:'2026-10-10',days:7});assert.equal((ics.match(/BEGIN:VALARM/g)||[]).length,1);assert.match(ics,/DTSTART;VALUE=DATE:20261031/);assert.match(ics,/DTEND;VALUE=DATE:20261101/);assert.match(ics,/TRIGGER:-P7D/);assert.equal((ics.match(/BEGIN:VEVENT/g)||[]).length,3);for(const line of ics.split('\r\n'))assert.ok(Buffer.byteLength(line)<=75);
assert.match(M.csv([{...booked,name:'=HYPERLINK(\"bad\")'}],'2026-10-10'),/'=HYPERLINK/);
assert.equal(U.periodFromTitle('中国中免2025年度业绩快报公告'),'2025FY');assert.equal(U.periodFromTitle('公司2026年半年度报告'),'2026H1');
const fixture={period:'2026H1',url:'https://query.sse.com.cn/',row:{companyCode:'601888',publishDate0:'2026-08-21',actualDate:'2026-08-21',publishYear:'2026',bulletinType:'L012'}};
const notice={url:'https://query.sse.com.cn/',row:{SECURITY_CODE:'601888',TITLE:'中国中免2026年半年度报告',SSEDATE:'2026-08-21',URL:'/test.pdf'}};
assert.equal(U.fromSSE([fixture],[notice],'2026-10-10T00:00:00Z').records[0].url,'https://static.sse.com.cn/test.pdf');assert.throws(()=>U.fromSSE([{...fixture,period:'2026Q3'}],[notice],'2026-10-10T00:00:00Z'));
const C=require('./import-earnings-choice.cjs'),active=M.validateSnapshot(JSON.parse(fs.readFileSync(__dirname+'/../data/earnings-calendar.json','utf8'))),receipts=JSON.parse(fs.readFileSync(__dirname+'/../data/earnings-choice-receipts.json','utf8'));
assert.equal(active.primarySource,'choice-mcp');assert.ok(active.records.every(r=>r.sourceId==='choice-mcp'));assert.equal(active.records.length,84);
const recent=M.recent(pool,active,'2026-10-10');assert.equal(recent.length,32);assert.equal(recent.filter(c=>c.latest).length,32);assert.equal(recent.filter(c=>c.next).length,22);assert.equal(recent.filter(c=>!c.next&&!c.overdue).length,10);
assert.equal(recent[0].code,'09961.HK');assert.equal(recent[0].latest.actual,'2026-09-16');assert.equal(M.upcoming(recent.flatMap(c=>c.next?[c.next]:[]),'2026-10-10',30).length,21);
assert.equal(recent.find(c=>c.code==='ATAT.O').next.expected,'2026-11-24');assert.equal(recent.find(c=>c.code==='01179.HK').next,undefined);
assert.equal(M.recent(pool,active,'2026-11-01').find(c=>c.code==='601888.SH').overdue.expected,'2026-10-31');
assert.equal(M.recent(pool,active,'2027-01-01').find(c=>c.code==='601888.SH').next,undefined);assert.equal(M.recent(pool,active,'2027-01-01').find(c=>c.code==='601888.SH').latest.period,'2026H1');
assert.ok(M.recent(pool,{...active,records:[]},'2026-10-10').every(c=>!c.latest&&!c.next&&!c.overdue));
assert.equal(C.period('2025三季报'),'2025Q3');assert.equal(C.period('2026中报'),'2026H1');assert.equal(C.security('同程旅行(0780.HK)'),'00780.HK');
const replay=C.fromChoice(receipts,pool,active);assert.deepEqual(replay.records,active.records);
assert.ok(replay.records.every(r=>r.evidence.cells.every(c=>c.indicatorId&&c.columns&&c.rowValues&&c.query&&c.tool)));
const staleResponse=C.fromChoice({...receipts,envelopes:[receipts.envelopes.at(-1)]},pool,active);assert.ok(staleResponse.records.every(r=>r.period==='2025Q3'));assert.ok(!staleResponse.records.some(r=>r.period==='2026Q3'));
const invalid=structuredClone(receipts);invalid.envelopes[0].data[0].items[0][1]='2026-02-30';assert.throws(()=>C.fromChoice(invalid,pool,active));
const wrongIndicator=structuredClone(receipts);wrongIndicator.envelopes[0].data[0].meta.jumpUrlList[0].choiceUrl=wrongIndicator.envelopes[0].data[0].meta.jumpUrlList[0].choiceUrl.replace(/007104/g,'007105');assert.throws(()=>C.fromChoice(wrongIndicator,pool,active));
const wrongPeriod=structuredClone(receipts);wrongPeriod.envelopes[0].data[0].columns[1]='2025三季报';assert.throws(()=>C.fromChoice(wrongPeriod,pool,active));
const noMeta=structuredClone(receipts);delete noMeta.envelopes[0].data[0].meta;assert.throws(()=>C.fromChoice(noMeta,pool,active));
const futureActual=structuredClone(receipts);futureActual.envelopes[1].data[0].items[0][1]='2027-01-01';assert.throws(()=>C.fromChoice(futureActual,pool,active));
assert.throws(()=>C.fromChoice({...receipts,envelopes:[]},pool,active));
const partial=C.fromChoice({...receipts,envelopes:[receipts.envelopes[0]]},pool,active);assert.equal(C.mergeChoice(active,partial).records.length,84);
const erased=structuredClone(active);erased.records.find(r=>r.actual).actual='';assert.throws(()=>C.mergeChoice(active,erased));
console.log('PASS: Choice indicator/period/cell evidence, stale response isolation, recent defaults/year rollover, upcoming and overdue, partial history preservation, date types and safe exports');
