(function(){
 'use strict';
 const $=id=>document.getElementById(id),M=window.MacroModel,P=window.PredictionModel,F=window.FedwatchModel;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const n=v=>typeof v==='number'&&Number.isFinite(v)?new Intl.NumberFormat('zh-CN',{maximumFractionDigits:2}).format(v):'—';
 const pct=v=>typeof v==='number'&&Number.isFinite(v)?n(v)+'%':'—';
 const money=v=>typeof v==='number'&&Number.isFinite(v)?'$'+(v>=1e6?n(v/1e6)+'百万':v>=1e4?n(v/1e4)+'万':n(v)):'—';
 const when=v=>{const d=new Date(v);return v&&!Number.isNaN(d.getTime())?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hour12:false}).format(d):'未提供';};
 const day=v=>v?String(v).slice(0,10):'未提供';
 const anchor=(url,label)=>'<a target="_blank" rel="noopener" href="'+esc(M.safeUrl(url))+'">'+esc(label)+'</a>';
 const exportCsv=(rows,name)=>{const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(M.csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const params=new URLSearchParams(location.search);let pm,expanded=false,wired=false,cme,cmeLoading=false,cmeError=false;
 function keep(values){const p=new URLSearchParams(location.search);Object.entries(values).forEach(([k,v])=>v?p.set(k,v):p.delete(k));history.replaceState(null,'',location.pathname+'?'+p);}
 function pmRows(g,items){return items.map(m=>{const yes=P.affirmative(m),outcomes=yes?[yes]:m.outcomes;return outcomes.map(o=>{const change=Number.isFinite(o.previousProbability)?(o.probability-o.previousProbability)*100:null;return '<div class="forecast-outcome" data-chart-tooltip="'+esc('Polymarket · '+P.optionLabel(g,m)+' · '+(o.nameZh||o.name)+'\n概率：'+pct(o.probability*100)+(change===null?'':'\n较上次：'+n(change)+' 个百分点'))+'"><div class="forecast-outcome-label">'+esc(g.markets.length===1?(yes?'是':o.nameZh||o.name):P.optionLabel(g,m)+(yes?'':' · '+(o.nameZh||o.name)))+(m.liquidity!=null&&m.liquidity<10000?'<span class="forecast-badge caution">低流动性</span>':'')+'</div><strong>'+pct(o.probability*100)+'</strong><div class="forecast-probability-track"><i style="width:'+o.probability*100+'%"></i></div>'+(change!==null?'<small class="forecast-delta">较上次 '+(change>0?'+':'')+n(change)+' 个百分点</small>':'')+'</div>';}).join('');}).join('');}
 function renderPolymarket(data){
  pm=data;if(!wired){wired=true;$('prediction-search').value=params.get('predictionQuery')||'';$('prediction-category').value=params.has('predictionTopic')?(params.get('predictionTopic')==='all'?'':params.get('predictionTopic')): '经济与利率';$('prediction-sort').value=params.get('predictionSort')==='deadline'?'deadline':'volume';
   $('prediction-topics').onclick=e=>{const b=e.target.closest('[data-topic]');if(b){$('prediction-category').value=b.dataset.topic;expanded=false;drawPm();}};
   $('prediction-search').oninput=()=>{expanded=false;drawPm();};$('prediction-sort').onchange=()=>{expanded=false;drawPm();};$('prediction-more').onclick=()=>{expanded=!expanded;drawPm();};$('prediction-reset').onclick=()=>{$('prediction-search').value='';$('prediction-category').value='经济与利率';$('prediction-sort').value='volume';expanded=false;drawPm();};
  }drawPm();
 }
 function drawPm(){
  const topic=$('prediction-category').value,query=$('prediction-search').value,sort=$('prediction-sort').value;keep({predictionTopic:topic||'all',predictionQuery:query,predictionSort:sort});
  document.querySelectorAll('[data-topic]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.topic===topic)));
  const groups=P.groups(pm.markets,{category:topic,query,sort,wholeEvents:true}),visible=expanded?groups:groups.slice(0,6),all=P.groups(pm.markets,{wholeEvents:true}),stale=Date.now()-Date.parse(pm.fetchedAt)>24*3600000;
  $('prediction-status').textContent=(pm.status==='error'?'更新失败 · 保留快照 · ':stale?'历史快照 · ':'快照 · ')+day(pm.fetchedAt)+' '+when(pm.fetchedAt)+' 北京时间';
  $('prediction-overview').innerHTML='<span><b>'+groups.length+'</b> 个事件</span><span><b>'+groups.reduce((s,g)=>s+g.markets.length,0)+'</b> 个活跃合约</span><span>合约隐含概率</span>'+(pm.previousFetchedAt?'<span>对照快照 '+day(pm.previousFetchedAt)+' '+when(pm.previousFetchedAt)+' 北京时间</span>':'')+(all.length<new Set(pm.markets.map(m=>m.eventId||m.id)).size?'<span>已隐藏到期合约</span>':'');
  $('prediction-list').innerHTML=visible.map(g=>{const lead=P.affirmative(g.markets[0]);return '<article class="forecast-event"><div class="forecast-event-head"><span class="forecast-badge">'+esc(g.category)+'</span><span>'+g.markets.length+' 个合约'+(!g.complete?' · 部分收录':'')+'</span></div><h3>'+esc(g.title)+'</h3><div class="forecast-event-meta"><span>24h 成交 '+money(g.volume)+'</span><span>最早截止 '+day(g.endDate)+'</span></div>'+(g.markets.length>1?'<div class="forecast-column-head"><span>结果 / 独立合约</span><span>是的概率</span></div>':'')+pmRows(g,g.markets.slice(0,4))+(g.markets.length>4?'<details class="forecast-extra"><summary>其余 '+(g.markets.length-4)+' 个结果</summary>'+pmRows(g,g.markets.slice(4))+'</details>':'')+(g.markets.length===1&&lead?'<p class="forecast-no">否 '+pct(g.markets[0].outcomes.find(o=>o.name==='No')?.probability*100)+'</p>':'')+'<div class="forecast-event-footer">'+anchor(g.markets[0].url,'原始事件 ↗')+'<details><summary>合约明细</summary>'+g.markets.map(m=>'<div class="forecast-contract"><b>'+esc(m.questionZh||m.question)+'</b><p>'+esc(m.question)+'</p><p>截止 '+day(m.endDate)+' '+when(m.endDate)+' 北京时间</p><p>流动性 '+money(m.liquidity)+' · 价差 '+(Number.isFinite(m.spread)?n(m.spread*100)+'¢':'—')+'</p><p>源更新 '+when(m.updatedAt)+' 北京时间</p>'+anchor(m.url,'结算规则 ↗')+'</div>').join('')+'</details></div></article>';}).join('')||'<p class="portal-empty">暂无符合条件的活跃事件</p>';
  $('prediction-selection').textContent=pm.selectionNote||'部分活跃事件 · 原始合约价格 · 不归一化';$('prediction-more').hidden=groups.length<=6;$('prediction-more').textContent=expanded?'收起更多事件':'显示全部 '+groups.length+' 个事件';
  $('prediction-download').disabled=!groups.length;$('prediction-download').onclick=()=>exportCsv([['事件','原始事件标题','合约','英文原文','结果','隐含概率','24h成交USD','流动性USD','截止时间','源更新时间','快照时间','完整活跃事件收录','来源'],...groups.flatMap(g=>g.markets.flatMap(m=>m.outcomes.map(o=>[g.title,m.eventTitle||'',m.questionZh||m.question,m.question,o.nameZh||o.name,o.probability,m.volume24h,m.liquidity,m.endDate,m.updatedAt,pm.fetchedAt,g.complete,m.url])))],'polymarket-events.csv');
 }
 async function loadFedwatch(force=false){if(cmeLoading)return;if(cme&&!force){drawCme();return;}cmeLoading=true;$('fedwatch-status').textContent='正在读取…';try{const response=await fetch('data/gold-jewelry/macro.json',{cache:'no-cache',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('HTTP '+response.status);const value=await response.json();if(!Array.isArray(value.meetings)||!value.policy)throw new Error('格式错误');cme=value;cmeError=false;const meetings=value.meetings.filter(m=>Date.parse(m.meetingDate+'T23:59:59Z')>=Date.now()&&F.snapshots(m).length);$('fedwatch-meeting').innerHTML=meetings.map(m=>'<option value="'+esc(m.meetingDate)+'">'+esc(m.meetingDate)+'</option>').join('');if(meetings.some(m=>m.meetingDate===params.get('meeting')))$('fedwatch-meeting').value=params.get('meeting');$('fedwatch-meeting').onchange=()=>{setCompare();drawCme();};$('fedwatch-compare').onchange=drawCme;setCompare();drawCme();}catch{cmeError=true;if(cme)drawCme();else{$('fedwatch-status').textContent='CME 快照读取失败';$('fedwatch-content').innerHTML='<button id="fedwatch-retry" class="portal-button">重试读取</button>';$('fedwatch-retry').onclick=()=>loadFedwatch(true);}}finally{cmeLoading=false;}}
 function selectedCme(){const meeting=cme.meetings.find(m=>m.meetingDate===$('fedwatch-meeting').value);return {meeting,history:F.snapshots(meeting)};}
 function setCompare(){const {history}=selectedCme();$('fedwatch-compare').innerHTML='<option value="">不比较</option>'+history.slice(0,-1).reverse().map(s=>'<option value="'+esc(s.observedDate)+'">'+esc(s.observedDate)+'</option>').join('');$('fedwatch-compare').value=history.at(-2)?.observedDate||'';}
 function drawCme(){if(!cme)return;const {meeting,history}=selectedCme(),s=history.at(-1);$('fedwatch-download').disabled=!s;if(!s){$('fedwatch-status').textContent='暂无未来会议的有效概率快照';$('fedwatch-content').innerHTML='';return;}const previous=history.find(x=>x.observedDate===$('fedwatch-compare').value),buckets=F.aggregate(s,cme.policy),older=previous?F.aggregate(previous,cme.policy):null,rows=F.comparison(s,previous),source=cme.sources?.find(x=>x.id===s.sourceId);
  keep({meeting:meeting.meetingDate});$('fedwatch-status').textContent=(cmeError?'读取失败 · ':Date.now()-Date.parse(s.observedAt||s.observedDate+'T23:59:59Z')>24*3600000?'历史快照 · ':'快照 · ')+s.observedDate+(s.observedAt?' '+when(s.observedAt)+' 北京时间':' · 具体时点未提供');
  $('fedwatch-content').innerHTML='<div class="forecast-policy">当前目标区间 <b>'+cme.policy.range.map(n).join('–')+'%</b><span>生效 '+esc(cme.policy.decisionDate)+'</span></div><div class="fedwatch-kpis">'+[['cut','降息'],['hold','维持'],['hike','加息']].map(([key,label])=>{const value=buckets?.[key],change=older&&buckets?value-older[key]:null;return '<div class="fedwatch-kpi '+(key==='hold'?'primary':'')+'"><span>'+label+'</span><strong>'+pct(value)+'</strong><small>'+(change===null?'相对当前目标区间':(change>0?'+':'')+n(change)+' 个百分点 · 对照 '+previous.observedDate)+'</small></div>';}).join('')+'</div><section class="portal-panel"><div class="forecast-head"><h3>'+meeting.meetingDate+' · 目标利率分布</h3><span>概率 %'+(previous?' · 对照 '+previous.observedDate:'')+'</span></div><div class="fedwatch-distribution">'+rows.map(r=>'<div class="fedwatch-range" data-chart-tooltip="'+esc('CME FedWatch · '+meeting.meetingDate+'\n快照：'+s.observedDate+'\n目标区间：'+n(r.lower)+'–'+n(r.upper)+'%\n概率：'+pct(r.probability)+(r.change===null?'':'\n较 '+previous.observedDate+'：'+n(r.change)+' 个百分点'))+'"><span>'+n(r.lower)+'–'+n(r.upper)+'%</span><div><i style="width:'+r.probability+'%"></i></div><strong>'+pct(r.probability)+'</strong><small>'+(r.change===null?'—':(r.change>0?'+':'')+n(r.change)+' pp')+'</small></div>').join('')+'</div><details class="forecast-method"><summary>历史明细与来源</summary><div class="portal-table-scroll"><table class="portal-table"><thead><tr><th>快照日期</th><th>目标区间 %</th><th>概率 %</th><th>源时点</th></tr></thead><tbody>'+history.slice().reverse().flatMap(h=>h.ranges.map(r=>'<tr><td>'+h.observedDate+'</td><td>'+n(r.lower)+'–'+n(r.upper)+'</td><td>'+n(r.probability)+'</td><td>'+esc(h.observedAt||'未提供')+'</td></tr>')).join('')+'</tbody></table></div>'+anchor(source?.url||'https://www.cmegroup.com/fedwatch','CME FedWatch ↗')+' · 官方工具快照</details></section>';
  $('fedwatch-download').onclick=()=>exportCsv([['会议日期','快照日期','源时点','时区','目标下限%','目标上限%','概率%','提供者','来源'],...history.flatMap(h=>h.ranges.map(r=>[meeting.meetingDate,h.observedDate,h.observedAt||'',h.timezone,r.lower,r.upper,r.probability,'CME FedWatch',cme.sources?.find(x=>x.id===h.sourceId)?.url||'']))],'cme-fedwatch-'+meeting.meetingDate+'.csv');
 }
 window.ForecastDesk={renderPolymarket,loadFedwatch};
})();

