(async function(){
  'use strict';
  const $=id=>document.getElementById(id),R=GoldResearch,P=GoldJewelryModel;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=(v,n=1)=>R.finite(v)?v.toLocaleString('zh-CN',{minimumFractionDigits:n,maximumFractionDigits:n}):'—';
  const pct=v=>R.finite(v)?`${v>0?'+':''}${num(v)}%`:'—';
  const tone=v=>!R.finite(v)||v===0?'gj-neutral':v>0?'gj-positive':'gj-negative';
  const dateLabel=r=>r.basis==='jan_feb'?r.period.slice(0,4)+'·1—2月':r.period.replace('-','·');
  const link=(s,page)=>s?.url&&/^https:\/\//.test(s.url)?`<a href="${esc(s.url+(page?'#page='+page:''))}" target="_blank" rel="noopener">${esc(s.name||s.id)}${page?' · p'+page:''} ↗</a>`:esc(s?.name||'—');
  const table=(id,headers,rows)=>{$(id).innerHTML='<thead><tr>'+headers.map(h=>'<th scope="col">'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody>';};
  const select=(id,opts)=>{$(id).innerHTML=opts.map(([v,label])=>`<option value="${esc(v)}">${esc(label)}</option>`).join('');};
  const download=(name,headers,rows)=>{const u=URL.createObjectURL(new Blob([P.tableCsv(headers,rows)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
  const monthX=p=>{const [y,m]=p.split('-').map(Number);return y*12+m;};
  const quarterX=p=>{const [y,q]=p.split('-Q').map(Number);return y*4+q;};
  const dayX=p=>Date.parse(p+'T00:00:00Z')/86400000;
  const colors=['#5158aa','#c49851','#8e9cae'];
  function chart(id,series,{unit='%',title='',zero=true,gap=1}={}){
    const el=$(id),points=series.flatMap(s=>s.points),valid=points.filter(p=>R.finite(p.value));
    if(!valid.length){el.innerHTML='<div class="gj-empty">所选口径缺少可比较数据</div>';return;}
    const w=Math.max(300,el.clientWidth-28||650),h=250,L=48,T=22,B=38,RR=20;
    const minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),vs=valid.map(p=>p.value);
    let lo=Math.min(...vs,zero?0:Infinity),hi=Math.max(...vs,zero?0:-Infinity),pad=(hi-lo||Math.abs(hi)*.08||1)*.13;lo-=pad;hi+=pad;
    const x=v=>L+(v-minX)/(maxX-minX||1)*(w-L-RR),y=v=>T+(hi-v)/(hi-lo)*(h-T-B);
    let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}"><title>${esc(title)}</title><text x="${L}" y="12" fill="#8a93a3" font-size="10">${esc(unit)}</text>`;
    for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4;svg+=`<line x1="${L}" x2="${w-RR}" y1="${y(v)}" y2="${y(v)}" stroke="#edf0f5"/><text x="${L-8}" y="${y(v)+4}" text-anchor="end" fill="#8a93a3" font-size="10">${num(v,Math.abs(hi-lo)<5?1:0)}</text>`;}
    if(lo<0&&hi>0)svg+=`<line x1="${L}" x2="${w-RR}" y1="${y(0)}" y2="${y(0)}" stroke="#bcc2d2" stroke-dasharray="4 4"/>`;
    const labels=[...new Map(points.map(p=>[p.x,p.label])).entries()].sort((a,b)=>a[0]-b[0]),every=Math.max(1,Math.ceil(labels.length/Math.max(3,Math.floor(w/100))));
    labels.forEach(([xx,label],i)=>{if(i%every===0||i===labels.length-1)svg+=`<text x="${x(xx)}" y="${h-12}" text-anchor="${i===0?'start':i===labels.length-1?'end':'middle'}" fill="#8a93a3" font-size="10">${esc(label)}</text>`;});
    series.forEach((s,si)=>{let d='',prior=null;for(const p of s.points){if(!R.finite(p.value)){prior=null;continue;}d+=(prior&&p.x-prior.x<=gap?'L':'M')+x(p.x)+','+y(p.value)+' ';prior=p;}svg+=`<path d="${d}" fill="none" stroke="${s.color||colors[si]}" stroke-width="2.2"/>`;s.points.forEach((p,pi)=>{if(R.finite(p.value))svg+=`<circle class="gj-chart-point" tabindex="0" data-series="${si}" data-point="${pi}" cx="${x(p.x)}" cy="${y(p.value)}" r="3" fill="white" stroke="${s.color||colors[si]}" stroke-width="1.7" aria-label="${esc(p.label+' '+s.name+' '+num(p.value,2)+unit)}"><title>${esc(p.label+' '+s.name+' '+num(p.value,2)+unit)}</title></circle>`;});});
    el.innerHTML=svg+'</svg><div class="gj-legend">'+series.map((s,i)=>`<span><i style="background:${s.color||colors[i]}"></i>${esc(s.name)}</span>`).join('')+'</div><div class="gj-tooltip" hidden></div>';
    const tip=el.querySelector('.gj-tooltip');el.querySelectorAll('.gj-chart-point').forEach(circle=>{const show=()=>{const s=series[Number(circle.dataset.series)],p=s.points[Number(circle.dataset.point)];tip.innerHTML=`<b>${esc(p.label)}</b>${esc(s.name)}：${num(p.value,2)}${esc(unit)}${p.note?'<br>'+esc(p.note):''}`;tip.hidden=false;const box=circle.getBoundingClientRect(),rect=el.getBoundingClientRect();tip.style.left=Math.max(5,Math.min(box.left-rect.left+8,rect.width-230))+'px';tip.style.top=Math.max(0,box.top-rect.top-55)+'px';};circle.addEventListener('mouseenter',show);circle.addEventListener('focus',show);circle.addEventListener('mouseleave',()=>tip.hidden=true);circle.addEventListener('blur',()=>tip.hidden=true);});
  }
  try{
    const load=async path=>{const r=await fetch(path,{cache:'no-cache'});if(!r.ok)throw new Error('无法读取 '+path);return r.json();};
    const [data,prices,ops,audit]=await Promise.all([load('data/gold-jewelry/research.json'),load('data/gold-jewelry/observations.json'),load('data/gold-jewelry/company-operations.json'),load('data/gold-jewelry/verification.json')]);
    const errors=[...R.validate(data),...P.validate(prices),...P.validateOperations(ops)];if(errors.length)throw new Error('数据校验失败：'+errors.join('；'));
    const sources=new Map(data.sources.map(s=>[s.id,s])),ps=new Map(prices.sources.map(s=>[s.id,s])),os=new Map(ops.sources.map(s=>[s.id,s])),quarter=R.quarters(data.consumption),retail=data.retail.slice().sort((a,b)=>a.period.localeCompare(b.period)),consumption=data.consumption.slice().sort((a,b)=>a.period.localeCompare(b.period));
    const latest=retail.at(-1),c=consumption.at(-1),benchmark=P.benchmarkSeries(prices.benchmarks,'close').at(-1);
    let view='overview',retailMode='yoy';
    $('asof').innerHTML=`<b>核对 ${esc(data.checkedAt)}</b>零售 ${esc(latest.period)} · 用金 ${esc(c.period)}`;
    const stat=(label,value,meta,primary=false,cls='')=>`<article class="gj-stat ${primary?'primary':''}"><div class="gj-stat-label">${esc(label)}</div><div class="gj-stat-value ${cls}">${value}</div><div class="gj-stat-meta">${meta}</div></article>`;
    $('core-kpis').innerHTML=stat('金银珠宝零售额 · 当月同比',pct(latest.yoy),`${esc(latest.period)} · ${num(latest.amount,0)}亿元`,true,tone(latest.yoy))+stat('黄金首饰用金 · 累计同比',pct(c.yoy.jewelry),`${esc(c.year+'年上半年')} · ${num(c.values.jewelry)}吨`,false,tone(c.yoy.jewelry))+stat('金条及金币 · 累计同比',pct(c.yoy.bars),`${esc(c.year+'年上半年')} · ${num(c.values.bars)}吨`,false,tone(c.yoy.bars))+stat('Au99.99 · 收盘参考',num(benchmark.price,2)+'<small>元/克</small>',`${esc(benchmark.quoteDate)} · 官方交易日披露`);
    const rowSeries=(rows,key,name)=>[{name,points:rows.map(r=>({x:monthX(r.period),label:dateLabel(r),value:r[key],note:r.basis==='jan_feb'?'1—2月合并':''}))}];
    const volumeSeries=(rows,yoy,industrial=false)=>(industrial?R.categories:['jewelry','bars']).map(k=>({name:R.labels[k],color:colors[R.categories.indexOf(k)],points:rows.map(r=>({x:quarterX(r.period),label:r.period,value:(yoy?r.yoy:r.values)[k],note:r.basis==='cumulative'?'年初至季末累计':'单季口径；同比为计算值'}))}));
    let consecutive=0;for(let i=retail.length-1;i>=0&&retail[i].yoy<0;i--)consecutive++;
    const lp=data.financials.find(r=>r.id==='laopu');
    $('research-signals').innerHTML=`<article class="gj-signal"><b>需求：金额端仍承压</b><p>已收录月度同比连续${consecutive}期为负，${esc(latest.period)}累计同比${pct(latest.ytdYoy)}。继续跟踪月度拐点，零售额不直接代表金饰销量。</p></article><article class="gj-signal"><b>结构：投资金与金饰分开看</b><p>${esc(c.period)}金饰累计用金${pct(c.yoy.jewelry)}，金条金币${pct(c.yoy.bars)}。黄金消费总量不能替代珠宝消费景气。</p></article><article class="gj-signal"><b>公司：增长与资金占用并看</b><p>老铺收入同比${pct(R.metric(lp,'revenueYoy'))}，经营现金流 / 归母利润${num(R.cashConversion(lp))}%。继续看库存扩张与回款节奏。</p></article>`;
    function financeCell(r,key,percent=false){const m=r.metrics[key];if(!m)return '—';const text=percent?pct(m.value):num(m.value,2),quality=m.quality==='provider'?'<span class="gj-provider">转引</span>':'';return `<span class="${percent&&key.endsWith('Yoy')?tone(m.value):''}" title="${esc(sources.get(m.sourceId)?.name+(m.pdfPage?' PDF p'+m.pdfPage:''))}">${text}</span>${quality}`;}
    function financeTable(id,full=false){const heads=['公司','收入','收入同比','归母利润','利润同比',...(full?['毛利率','期末存货']:[]),'经营现金流','现金流 / 利润'];table(id,heads,data.financials.map(r=>[esc(r.name)+`<small>${esc(r.code)}</small>`,financeCell(r,'revenue'),financeCell(r,'revenueYoy',true),financeCell(r,'profit'),financeCell(r,'profitYoy',true),...(full?[financeCell(r,'grossMargin',true).replace('+',''),financeCell(r,'inventory')]:[]),financeCell(r,'cashflow'),num(R.cashConversion(r))+(R.finite(R.cashConversion(r))?'%':'')+(R.finite(R.cashConversion(r))&&[r.metrics.profit,r.metrics.cashflow].some(m=>m?.quality==='provider')?'<span class="gj-provider">转引计算</span>':'')]));}
    financeTable('overview-finance');financeTable('finance-table',true);
    const filteredRetail=()=>{const w=$('retail-window').value;if(w==='2026')return retail.filter(r=>r.period.startsWith('2026'));if(w==='12'){const end=monthX(latest.period);return retail.filter(r=>monthX(r.period)>end-12);}return retail;};
    function renderDemand(){const rows=filteredRetail(),names={yoy:'当月同比',amount:'当月金额',ytdYoy:'累计同比'};chart('retail-chart',rowSeries(rows,retailMode,names[retailMode]),{unit:retailMode==='amount'?'亿元':'%',title:'金银珠宝类零售额 '+names[retailMode]});$('retail-caption').textContent=rows[0].period+' — '+rows.at(-1).period+' · 1—2月合并';table('retail-table',['期间','当月金额 / 亿元','当月同比','累计金额 / 亿元','累计同比','原始来源'],rows.slice().reverse().map(r=>[esc(dateLabel(r)),num(r.amount,0),pct(r.yoy),num(r.ytdAmount,0),pct(r.ytdYoy),link(sources.get(r.sourceId))]));
      const mode=$('volume-mode').value,cumulative=mode.startsWith('cumulative'),yoy=mode.endsWith('yoy'),vs=cumulative?consumption:quarter;chart('volume-chart',volumeSeries(vs,yoy,true),{unit:yoy?'%':'吨',title:(cumulative?'累计':'单季')+'黄金消费'+(yoy?'同比':'量')});table('volume-table',['期间 / 口径','黄金首饰','金条及金币','工业及其他','计算依据 / 来源'],vs.slice().reverse().map(r=>[esc(r.period)+'<small>'+(cumulative?'年初至季末累计':r.quarter===1?'第一季':'累计量作差')+'</small>',...R.categories.map(k=>yoy?pct(r.yoy[k]):num(r.values[k],3)),cumulative?link(sources.get(r.sourceId)):(yoy?r.yoyInputSourceIds:r.inputSourceIds).map(s=>link(sources.get(s))).join('<br>')]));$('volume-note').textContent=cumulative?'累计同比和吨数沿用原始披露，不将累计量标为单季度。':'单季量＝本季累计−上季累计；第一季沿用累计量。缺上季累计或同比基期时留空；单季同比为计算值。2023Q4未取得Q3累计，因此单季量不展示。';
    }
    $('annual-composition').innerHTML=consumption.filter(r=>r.quarter===4).map(r=>{const total=R.categories.reduce((a,k)=>a+r.values[k],0);return `<div class="gj-composition-row"><b>${r.year}</b><div class="gj-stacked" aria-label="${esc(R.categories.map(k=>R.labels[k]+num(r.values[k],3)+'吨').join('，'))}">${R.categories.map((k,i)=>`<span style="width:${r.values[k]/total*100}%;background:${colors[i]}" title="${esc(R.labels[k])} ${num(r.values[k],3)}吨，占${num(r.values[k]/total*100)}%">${num(r.values[k],0)}<small>吨</small></span>`).join('')}</div></div>`;}).join('')+'<div class="gj-legend">'+R.categories.map((k,i)=>`<span><i style="background:${colors[i]}"></i>${esc(R.labels[k])}</span>`).join('')+'</div>';
    select('company-select',data.financials.map(r=>[r.id,r.name]));
    const prompts={laopu:['收入采用不含税人民币口径，利润采用IFRS归母利润；与含税Sales、非IFRS调整利润分别存储。','观察渠道变化：线上收入占比22.2%，同比171.9%；库存较2025年末增加'+num(R.inventoryGrowth(lp))+'%。库存周转271天为上半年口径，不与全年216天直接作同比。'],chj:['公告核验了收入、归母利润及经营现金流；毛利率、存货仍为妙想转引。','经营现金流明显高于归母利润；继续查全文中的存货变化、应付款和税费，解释现金释放来自哪里。'],cds:['收入、利润、毛利率、存货与经营现金流来自妙想结构化回执，待半年度报告原文复核。','补齐收入同比与直营/加盟拆分，进一步区分渠道结构和金价对收入的影响。'],lfx:['收入及利润同比下滑；当前毛利率、存货为妙想转引，公告复核尚未完成。','继续核查批发与零售收入、加盟渠道库存和黄金租借。尚未取得经营现金流，不用现金余额代填。'],cg:['收入和归母利润均为妙想转引；金条与金饰收入结构需结合报告进一步拆分。','金条业务的收入和毛利率口径与珠宝零售不同；尚未取得经营现金流，不用现金余额代填。']};
    function renderCompany(){const r=data.financials.find(c=>c.id===$('company-select').value),m=r.metrics;const referenced=[...new Set(Object.values(m).filter(Boolean).map(x=>x.sourceId))];$('company-focus').innerHTML=`<div><h3>${esc(r.name)} · ${r.period}</h3>${prompts[r.id].map(p=>'<p>'+esc(p)+'</p>').join('')}<p>${referenced.map(id=>link(sources.get(id))).join('<br>')}</p></div><div class="gj-focus-stats"><span>毛利率<strong>${num(R.metric(r,'grossMargin'))}%</strong></span><span>期末存货 / 亿元<strong>${num(R.metric(r,'inventory'),2)}</strong></span><span>经营现金流 / 亿元<strong>${num(R.metric(r,'cashflow'),2)}</strong></span><span>现金流 / 归母利润<strong>${num(R.cashConversion(r))}${R.finite(R.cashConversion(r))?'%':''}</strong></span></div>`;}
    select('operation-company',ops.companies.map(r=>[r.id,r.name]));
    let selectedOps=[];
    function operationPeriods(){const rows=ops.records.filter(r=>r.companyId===$('operation-company').value),periods=[...new Map(rows.map(r=>[r.periodStart+'|'+r.periodEnd,r])).entries()].sort((a,b)=>b[1].periodEnd.localeCompare(a[1].periodEnd)||a[1].periodType.localeCompare(b[1].periodType));select('operation-period',periods.map(([key,r])=>[key,r.fiscalLabel+' · '+r.periodStart+' — '+r.periodEnd]));renderOperations();}
    function renderOperations(){
      selectedOps=ops.records.filter(r=>r.companyId===$('operation-company').value&&r.periodStart+'|'+r.periodEnd===$('operation-period').value);
      const highlights=selectedOps.filter(r=>['sss_amount_yoy','sss_weight_yoy','fixed_price_gold_rsv_share','fixed_price_jewelry_rsv_share'].includes(r.metric)||['stores_end','stores_net'].includes(r.metric)&&r.channel==='全部');
      $('operations-summary').innerHTML=highlights.map(r=>`<span>${esc(P.operationLabels[r.metric])}<b class="${tone(r.metric.includes('yoy')?r.value:null)}">${r.metric.includes('yoy')?pct(r.value):num(r.value,r.unit==='家'?0:1)+esc(r.unit)}</b>${esc(r.scope)}</span>`).join('');
      if($('operation-company').value==='ctf')for(const [key,label] of [['stores_opened','内地新开 · 城市层级合计'],['stores_closed','内地关闭 · 城市层级合计']]){const rows=selectedOps.filter(r=>r.metric===key);if(rows.length===4)$('operations-summary').innerHTML+=`<span>${esc(label)}<b>${num(rows.reduce((a,r)=>a+r.value,0),0)}家</b>根据四个城市层级计算</span>`;}
      table('operations-table',['指标','数值','地区 / 渠道','产品与品牌范围','期间','原始公告'],selectedOps.map(r=>[esc(P.operationLabels[r.metric]),num(r.value,r.unit==='家'?0:1)+esc(r.unit),esc(r.region+' / '+r.channel),esc(r.scope),esc(r.fiscalLabel)+`<small>${esc(r.periodStart+' — '+r.periodEnd)}</small>`,link(os.get(r.sourceId),r.pdfPage)]));
    }
    let selectedBenchmark=[],selectedQuotes=[],selectedBrandHistory=[];
    const groups=new Map();for(const q of prices.quotes){const key=JSON.stringify(['brandId','market','city','product','priceBasis','purity','includesLabor','includesTax','currency','unit','sourceId','verification'].map(k=>q[k]));if(!groups.has(key))groups.set(key,[]);groups.get(key).push(q);}
    const brandName=id=>prices.brands.find(b=>b.id===id)?.name||id;
    const groupList=[...groups.values()].sort((a,b)=>a[0].verification.localeCompare(b[0].verification)||brandName(a[0].brandId).localeCompare(brandName(b[0].brandId)));
    select('brand-series',groupList.map((rows,i)=>[String(i),brandName(rows[0].brandId)+' · '+(rows[0].verification==='verified_primary'?'官方指导价':'第三方转引')+' · '+(rows[0].purity?rows[0].purity*1000+'‰':'纯度未披露')+' · '+rows.length+'期']));
    select('quote-brand',[['all','全部10品牌'],...prices.brands.map(b=>[b.id,b.name])]);
    select('quote-date',[...[...new Set(prices.quotes.map(r=>r.quoteDate))].sort().reverse().map(d=>[d,d]),['all','全部已收录日期']]);
    function renderPrices(){
      const start=$('price-start').value,end=$('price-end').value,interval=P.historyWindow(prices.quotes,start,end);
      if(interval.error){$('price-range-note').textContent=interval.error;selectedBenchmark=[];selectedQuotes=[];selectedBrandHistory=[];for(const id of ['benchmark-chart','brand-chart'])$(id).innerHTML='<div class="gj-empty">'+esc(interval.error)+'</div>';for(const id of ['benchmark-table','quotes-table'])$(id).innerHTML='';$('benchmark-export').disabled=true;$('quotes-export').disabled=true;$('brand-history-export').disabled=true;return;}
      selectedBenchmark=P.historyWindow(P.benchmarkSeries(prices.benchmarks,$('benchmark-type').value),start,end).rows;const type=$('benchmark-type').value==='close'?'收盘价':'加权平均价';
      chart('benchmark-chart',[{name:'Au99.99 '+type,points:selectedBenchmark.map(r=>({x:dayX(r.quoteDate),label:r.quoteDate,value:r.price}))}],{unit:'元/克',zero:false,title:'上金所Au99.99 '+type});
      const summary=P.historySummary(selectedBenchmark);$('benchmark-caption').textContent=summary?summary.count+'个交易日 · '+summary.start+' — '+summary.end+' · 最新 '+num(summary.last,2)+'元/克'+(summary.change===null?' · 单点无涨跌':' · 首末变化 '+pct(summary.percent)):'所选区间未收录观测';
      $('price-range-note').textContent='区间包含端点；首末变化采用实际观测日，不补日历端点。';
      table('benchmark-table',['日期','合约 / 口径','元/克','原始披露'],selectedBenchmark.slice().reverse().map(r=>[esc(r.quoteDate),esc(r.instrument+' / '+type),num(r.price,2),link(ps.get(r.sourceId))]));
      const original=groupList[Number($('brand-series').value)],rows=P.historyWindow(original,start,end).rows;
      selectedBrandHistory=rows;selectedQuotes=interval.rows.filter(r=>($('quote-date').value==='all'||r.quoteDate===$('quote-date').value)&&($('quote-brand').value==='all'||r.brandId===$('quote-brand').value));
      chart('brand-chart',[{name:brandName(original[0].brandId)+' · '+(original[0].verification==='verified_primary'?'官方':'第三方'),points:rows.map(r=>({x:dayX(r.quoteDate),label:r.quoteDate,value:r.price,note:'挂牌价，税费及工费未披露'}))}],{unit:'元/克',zero:false,title:'固定来源与口径的品牌挂牌价历史'});
      table('quotes-table',['品牌 / 日期','挂牌价 · 元/克','纯度 / 工费 / 税','同日参考差','来源与核验'],selectedQuotes.slice().reverse().map(r=>{const s=ps.get(r.sourceId),sp=P.spread(r,prices.benchmarks);return [esc(brandName(r.brandId))+`<small>${esc(r.quoteDate)}</small>`,num(r.price,2),esc((r.purity?r.purity*1000+'‰':'未披露')+' / '+(r.includesLabor===null?'工费未披露':r.includesLabor?'含工费':'不含工费')+' / '+(r.includesTax===null?'税未披露':r.includesTax?'含税':'不含税')),num(sp.value,2)+`<small>${esc(sp.reason)}</small>`,link(s)+`<small>${r.verification==='verified_primary'?'原始来源已核验':'第三方转引 · 待官网复核'}</small>`];}));
      $('benchmark-export').disabled=!selectedBenchmark.length;$('quotes-export').disabled=!selectedQuotes.length;$('brand-history-export').disabled=!selectedBrandHistory.length;
    }
    table('coverage-table',['模块','期间','覆盖','来源状态'],[['零售金额','2025.01—02 至 2026.08',retail.length+'期','国家统计局原始发布'],['黄金消费量','2023全年 至 2026H1',consumption.length+'期累计披露','中国黄金协会原文；单季另作差'],['公司财务','2026.01—06','5家公司','老铺及潮宏基部分字段原始公告；其余逐字段转引'],['公司经营','FY2025 / FY2026 / Q4','周大福、六福；31条字段','港交所公告，附PDF页码'],['上金所Au99.99','2026.09.01—10.08','22交易日；两种价格口径','原始日行情'],['品牌报价','2026.09.29—10.08','10品牌；100条转引+1条官方','各序列独立保留；9品牌官方待核验']].map(r=>r.map(esc)));
    $('method-notes').innerHTML=data.limitations.map(p=>'<li>'+esc(p)+'</li>').join('');table('sources-table',['来源','披露期间','发布时间','来源类型','回执指纹'],data.sources.map(s=>[link(s),esc(s.period),esc(s.publishedAt||'未提供'),s.quality==='primary'?'原始披露':'妙想转引 · 待公告复核',`<span title="${esc(s.sha256)}">${esc(s.sha256.slice(0,14))}…</span>`]));
    table('audit-table',['品牌','核验结果','原始来源入口'],audit.brandChecks.map(r=>[esc(brandName(r.brandId)),`<span class="gj-audit-note">${esc(r.note)}</span>`,link({url:r.attemptedPrimaryUrl,name:'官网'})]));
    $('mcp-note').innerHTML='<p>已通过妙想远程MCP实际完成初始化、工具发现与查数；当前会话未验证桌面动态挂载。密钥和原始付费响应留在本机，公开数据仅保留经复核的字段与回执指纹。</p><p>本轮使用宏观查数和A股、港股财务工具。需求回到国家统计局与黄金协会核验；财务按字段、原币与期间复核后入库。混入的地方统计、现金余额、港币换算值和不对应的指标被排除。</p>';
    function renderView(){if(view==='overview'){chart('overview-retail',rowSeries(retail,'yoy','当月零售额同比'),{title:'全国金银珠宝类零售额同比'});chart('overview-volume',volumeSeries(quarter.filter(r=>r.year>=2025),true),{title:'金饰与金条金币单季用金同比'});}if(view==='demand')renderDemand();if(view==='companies')renderCompany();if(view==='prices')renderPrices();}
    const allowed=['overview','demand','companies','prices','sources'];
    function setView(next,update=true){view=allowed.includes(next)?next:'overview';document.querySelectorAll('.gj-view').forEach(s=>s.hidden=s.id!=='view-'+view);document.querySelectorAll('.gj-tabs button').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));});if(update)history.replaceState(null,'','#'+view);renderView();}
    document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.go)));
    document.querySelectorAll('#retail-mode button').forEach(b=>b.addEventListener('click',()=>{retailMode=b.dataset.mode;document.querySelectorAll('#retail-mode button').forEach(a=>{a.classList.toggle('active',a===b);a.setAttribute('aria-pressed',String(a===b));});renderDemand();}));
    $('retail-window').addEventListener('change',renderDemand);$('volume-mode').addEventListener('change',renderDemand);$('company-select').addEventListener('change',renderCompany);$('operation-company').addEventListener('change',operationPeriods);$('operation-period').addEventListener('change',renderOperations);$('benchmark-type').addEventListener('change',renderPrices);$('brand-series').addEventListener('change',renderPrices);$('quote-brand').addEventListener('change',renderPrices);$('quote-date').addEventListener('change',renderPrices);
    $('demand-export').addEventListener('click',()=>{const mode=$('volume-mode').value,cumulative=mode.startsWith('cumulative'),vs=cumulative?consumption:quarter;download('黄金珠宝-需求.csv',['模块','期间','口径','指标','数值','单位','同比','同比口径','来源URL'],[...filteredRetail().map(r=>['零售',r.period,r.basis,'金银珠宝类零售额',r.amount,'亿元',r.yoy,'统计局原始公布',sources.get(r.sourceId).url]),...vs.flatMap(r=>R.categories.map(k=>['消费量',r.period,r.basis,R.labels[k],r.values[k],'吨',r.yoy[k],cumulative?'协会原始公布':'单季同比计算值',(cumulative?[r.sourceId]:r.yoyInputSourceIds).map(id=>sources.get(id).url).join(' | ')]))]);});
    $('finance-export').addEventListener('click',()=>download('黄金珠宝-2026H1财务.csv',['公司','期间开始','期间结束','币种','指标','数值','单位','来源状态','来源','URL','PDF页码'],data.financials.flatMap(r=>Object.entries(r.metrics).map(([k,m])=>[r.name,r.periodStart,r.periodEnd,r.currency,k,m?.value??null,['revenueYoy','profitYoy','grossMargin','onlineShare','onlineRevenueYoy'].includes(k)?'%':k==='inventoryDays'?'天':'亿元',m?.quality??'missing',m?sources.get(m.sourceId).name:'',m?sources.get(m.sourceId).url:null,m?.pdfPage]))));
    $('operations-export').addEventListener('click',()=>download('黄金珠宝-经营指标.csv',['公司','期间开始','期间结束','财年','地区','渠道','范围','指标','数值','单位','URL','PDF页码'],selectedOps.map(r=>[ops.companies.find(c=>c.id===r.companyId).name,r.periodStart,r.periodEnd,r.fiscalLabel,r.region,r.channel,r.scope,P.operationLabels[r.metric],r.value,r.unit,os.get(r.sourceId).url,r.pdfPage])));
    $('benchmark-export').addEventListener('click',()=>download('上金所-Au99.99.csv',['日期','合约','价格口径','数值','单位','原始URL'],selectedBenchmark.map(r=>[r.quoteDate,r.instrument,r.priceType,r.price,'CNY/g',ps.get(r.sourceId).url])));
    function downloadQuotes(name,rows){const enriched=rows.map(r=>({...r,brandName:brandName(r.brandId),sourceName:ps.get(r.sourceId).name,sourceUrl:ps.get(r.sourceId).url,capturedDate:ps.get(r.sourceId).capturedDate}));const u=URL.createObjectURL(new Blob([P.csv(enriched)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
    $('quotes-export').addEventListener('click',()=>downloadQuotes('品牌金价-筛选报价.csv',selectedQuotes));
    $('brand-history-export').addEventListener('click',()=>downloadQuotes('品牌金价-所选历史.csv',selectedBrandHistory));
    $('price-start').addEventListener('change',renderPrices);$('price-end').addEventListener('change',renderPrices);$('price-reset').addEventListener('click',()=>{$('price-start').value='';$('price-end').value='';renderPrices();});
    operationPeriods();renderPrices();$('dashboard').hidden=false;const old={ 'brand-panel':'prices','benchmark-panel':'prices','industry-panel':'demand','company-panel':'companies','source-panel':'sources'};setView(old[location.hash.slice(1)]||location.hash.slice(1)||'overview');window.addEventListener('hashchange',()=>setView(location.hash.slice(1),false));let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(renderView,160);});
  }catch(error){$('load-error').textContent=error.message||'读取失败，请刷新页面。';$('load-error').hidden=false;$('asof').textContent='数据加载失败';}
})();
