(async function(){
  'use strict';
  const $=id=>document.getElementById(id),R=GoldResearch,P=GoldJewelryModel,M=GoldMacro;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=(v,n=1)=>R.finite(v)?v.toLocaleString('zh-CN',{minimumFractionDigits:n,maximumFractionDigits:n}):'—';
  const pct=v=>R.finite(v)?`${v>0?'+':''}${num(v)}%`:'—';
  const tone=v=>!R.finite(v)||v===0?'gj-neutral':v>0?'gj-positive':'gj-negative';
  const dateLabel=r=>r.basis==='jan_feb'?r.period.slice(0,4)+'·1—2月':r.period.replace('-','·');
  const link=(s,page)=>s?.url&&/^https:\/\//.test(s.url)?`<a href="${esc(s.url+(page?'#page='+page:''))}" target="_blank" rel="noopener">${esc(s.name||s.id)}${page?' · p'+page:''} ↗</a>`:esc(s?.name||'—');
  const table=(id,headers,rows)=>{$(id).innerHTML='<thead><tr>'+headers.map(h=>'<th scope="col">'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody>';};
  const select=(id,opts)=>{$(id).innerHTML=opts.map(([v,label])=>`<option value="${esc(v)}">${esc(label)}</option>`).join('');};
  const download=(name,headers,rows)=>{const u=URL.createObjectURL(new Blob([P.tableCsv(headers,rows)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
  const monthX=p=>{const [y,m]=p.split('-').map(Number);return y*12+m;};
  const quarterX=p=>{const [y,q]=p.split('-Q').map(Number);return y*4+q;};
  const dayX=p=>Date.parse(p+'T00:00:00Z')/86400000;
  const colors=['#5158aa','#c49851','#8e9cae'];
  function chart(id,series,{unit='%',title='',zero=true,gap=1}={}){
    const el=$(id),points=series.flatMap(s=>s.points),valid=points.filter(p=>R.finite(p.value));
    if(!valid.length){el.innerHTML='<div class="gj-empty">所选口径缺少可比较数据</div>';return;}
    const w=Math.max(300,el.clientWidth-28||650),h=250,L=48,T=22,B=38,RR=20;
    const minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),vs=valid.map(p=>p.value);
    let lo=Math.min(...vs,zero?0:Infinity),hi=Math.max(...vs,zero?0:-Infinity);
    const rawStep=(hi-lo||Math.abs(hi)*.08||1)/4,power=10**Math.floor(Math.log10(rawStep)),step=([1,2,2.5,5,10].find(n=>n>=rawStep/power)||10)*power;
    lo=Math.floor(lo/step)*step;hi=Math.ceil(hi/step)*step;if(hi===lo){lo-=step;hi+=step;}
    const x=v=>L+(v-minX)/(maxX-minX||1)*(w-L-RR),y=v=>T+(hi-v)/(hi-lo)*(h-T-B);
    let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(title)}"><title>${esc(title)}</title><text x="${L}" y="12" fill="#8a93a3" font-size="10">${esc(unit)}</text>`;
    for(let v=lo;v<=hi+step/100;v+=step){svg+=`<line x1="${L}" x2="${w-RR}" y1="${y(v)}" y2="${y(v)}" stroke="#edf0f5"/><text x="${L-8}" y="${y(v)+4}" text-anchor="end" fill="#8a93a3" font-size="10">${num(v,step<1?2:step<5?1:0)}</text>`;}
    if(lo<0&&hi>0)svg+=`<line x1="${L}" x2="${w-RR}" y1="${y(0)}" y2="${y(0)}" stroke="#bcc2d2" stroke-dasharray="4 4"/>`;
    const labels=[...new Map(points.map(p=>[p.x,p.label])).entries()].sort((a,b)=>a[0]-b[0]),every=Math.max(1,Math.ceil(labels.length/Math.max(3,Math.floor(w/100))));
    labels.forEach(([xx,label],i)=>{if(i===0||i===labels.length-1||(i%every===0&&x(maxX)-x(xx)>=72))svg+=`<text x="${x(xx)}" y="${h-12}" text-anchor="${i===0?'start':i===labels.length-1?'end':'middle'}" fill="#8a93a3" font-size="10">${esc(label)}</text>`;});
    series.forEach((s,si)=>{let d='',prior=null;for(const p of s.points){if(!R.finite(p.value)){prior=null;continue;}d+=(prior&&p.x-prior.x<=gap?'L':'M')+x(p.x)+','+y(p.value)+' ';prior=p;}svg+=`<path d="${d}" fill="none" stroke="${s.color||colors[si]}" stroke-width="2.2"/>`;s.points.forEach((p,pi)=>{if(R.finite(p.value))svg+=`<circle class="gj-chart-point" tabindex="0" data-series="${si}" data-point="${pi}" cx="${x(p.x)}" cy="${y(p.value)}" r="3" fill="white" stroke="${s.color||colors[si]}" stroke-width="1.7" aria-label="${esc(p.label+' '+s.name+' '+num(p.value,2)+unit)}"><title>${esc(p.label+' '+s.name+' '+num(p.value,2)+unit)}</title></circle>`;});});
    el.innerHTML=svg+'</svg><div class="gj-legend">'+series.map((s,i)=>`<span><i style="background:${s.color||colors[i]}"></i>${esc(s.name)}</span>`).join('')+'</div>';
    const dates=[...new Map(points.map(p=>[p.x,p.label])).entries()].sort((a,b)=>a[0]-b[0]);
    SiteCharts.attach(el,dates.map(([date,label])=>({x:x(date),text:label+'\n'+series.map(s=>{
      const p=s.points.find(p=>p.x===date);return s.name+'：'+(R.finite(p?.value)?num(p.value,2)+unit:'—')+(p?.note?' · '+p.note:'');
    }).join('\n')})));

  }
  try{
    const load=async path=>{const r=await fetch(path,{cache:'no-cache'});if(!r.ok)throw new Error('无法读取 '+path);return r.json();};
    const [data,prices,ops,audit,macro]=await Promise.all([load('data/gold-jewelry/research.json'),load('data/gold-jewelry/observations.json'),load('data/gold-jewelry/company-operations.json'),load('data/gold-jewelry/verification.json'),load('data/gold-jewelry/macro.json')]);
    const errors=[...R.validate(data),...P.validate(prices),...P.validateOperations(ops),...M.validate(macro)];if(errors.length)throw new Error('数据校验失败：'+errors.join('；'));
    const sources=new Map(data.sources.map(s=>[s.id,s])),ps=new Map(prices.sources.map(s=>[s.id,s])),os=new Map(ops.sources.map(s=>[s.id,s])),quarter=R.quarters(data.consumption),retail=data.retail.slice().sort((a,b)=>a.period.localeCompare(b.period)),consumption=data.consumption.slice().sort((a,b)=>a.period.localeCompare(b.period));
    const latest=retail.at(-1),c=consumption.at(-1),benchmark=P.benchmarkSeries(prices.benchmarks,'close').at(-1);
    let view='overview',retailMode='yoy';
    const ms=new Map(macro.sources.map(s=>[s.id,s]));
    $('asof').innerHTML=`<b>核对 ${esc(data.checkedAt)}</b>金价 ${esc(benchmark.quoteDate)} · 宏观 ${esc(macro.checkedAt)}`;
    const stat=(label,value,meta,primary=false,cls='')=>`<article class="gj-stat ${primary?'primary':''}"><div class="gj-stat-label">${esc(label)}</div><div class="gj-stat-value ${cls}">${value}</div><div class="gj-stat-meta">${meta}</div></article>`;
    $('demand-kpis').innerHTML=stat('金银珠宝零售额 · 当月同比',pct(latest.yoy),`${esc(latest.period)} · ${num(latest.amount,0)}亿元`,true,tone(latest.yoy))+stat('黄金首饰用金 · 累计同比',pct(c.yoy.jewelry),`${esc(c.year+'年上半年')} · ${num(c.values.jewelry)}吨`,false,tone(c.yoy.jewelry))+stat('金条及金币 · 累计同比',pct(c.yoy.bars),`${esc(c.year+'年上半年')} · ${num(c.values.bars)}吨`,false,tone(c.yoy.bars))+stat('Au99.99 · 收盘参考',num(benchmark.price,2)+'<small>元/克</small>',`${esc(benchmark.quoteDate)} · 官方交易日披露`);
    const rowSeries=(rows,key,name)=>[{name,points:rows.map(r=>({x:monthX(r.period),label:dateLabel(r),value:r[key],note:r.basis==='jan_feb'?'1—2月合并':''}))}];
    const volumeSeries=(rows,yoy,industrial=false)=>(industrial?R.categories:['jewelry','bars']).map(k=>({name:R.labels[k],color:colors[R.categories.indexOf(k)],points:rows.map(r=>({x:quarterX(r.period),label:r.period,value:(yoy?r.yoy:r.values)[k],note:r.basis==='cumulative'?'年初至季末累计':'单季口径；同比为计算值'}))}));
    const lp=data.financials.find(r=>r.id==='laopu');
    function financeCell(r,key,percent=false){const m=r.metrics[key];if(!m)return '—';const text=percent?pct(m.value):num(m.value,2),quality=m.quality==='provider'?'<span class="gj-provider">转引</span>':'';return `<span class="${percent&&key.endsWith('Yoy')?tone(m.value):''}" title="${esc(sources.get(m.sourceId)?.name+(m.pdfPage?' PDF p'+m.pdfPage:''))}">${text}</span>${quality}`;}
    function financeTable(id,full=false){const heads=['公司','收入','收入同比','归母利润','利润同比',...(full?['毛利率','期末存货']:[]),'经营现金流','现金流 / 利润'];table(id,heads,data.financials.map(r=>[esc(r.name)+`<small>${esc(r.code)}</small>`,financeCell(r,'revenue'),financeCell(r,'revenueYoy',true),financeCell(r,'profit'),financeCell(r,'profitYoy',true),...(full?[financeCell(r,'grossMargin',true).replace('+',''),financeCell(r,'inventory')]:[]),financeCell(r,'cashflow'),num(R.cashConversion(r))+(R.finite(R.cashConversion(r))?'%':'')+(R.finite(R.cashConversion(r))&&[r.metrics.profit,r.metrics.cashflow].some(m=>m?.quality==='provider')?'<span class="gj-provider">转引计算</span>':'')]));}
    financeTable('finance-table',true);
    const filteredRetail=()=>{const w=$('retail-window').value;if(w==='2026')return retail.filter(r=>r.period.startsWith('2026'));if(w==='12'){const end=monthX(latest.period);return retail.filter(r=>monthX(r.period)>end-12);}return retail;};
    function renderDemand(){const rows=filteredRetail(),names={yoy:'当月同比',amount:'当月金额',ytdYoy:'累计同比'};chart('retail-chart',rowSeries(rows,retailMode,names[retailMode]),{unit:retailMode==='amount'?'亿元':'%',title:'金银珠宝类零售额 '+names[retailMode]});$('retail-caption').textContent=rows[0].period+' — '+rows.at(-1).period+' · 1—2月合并';table('retail-table',['期间','当月金额 / 亿元','当月同比','累计金额 / 亿元','累计同比','原始来源'],rows.slice().reverse().map(r=>[esc(dateLabel(r)),num(r.amount,0),pct(r.yoy),num(r.ytdAmount,0),pct(r.ytdYoy),link(sources.get(r.sourceId))]));
      const mode=$('volume-mode').value,cumulative=mode.startsWith('cumulative'),yoy=mode.endsWith('yoy'),vs=cumulative?consumption:quarter;chart('volume-chart',volumeSeries(vs,yoy,true),{unit:yoy?'%':'吨',title:(cumulative?'累计':'单季')+'黄金消费'+(yoy?'同比':'量')});table('volume-table',['期间 / 口径','黄金首饰','金条及金币','工业及其他','计算依据 / 来源'],vs.slice().reverse().map(r=>[esc(r.period)+'<small>'+(cumulative?'年初至季末累计':r.quarter===1?'第一季':'累计量作差')+'</small>',...R.categories.map(k=>yoy?pct(r.yoy[k]):num(r.values[k],3)),cumulative?link(sources.get(r.sourceId)):(yoy?r.yoyInputSourceIds:r.inputSourceIds).map(s=>link(sources.get(s))).join('<br>')]));
    }
    $('annual-composition').innerHTML=consumption.filter(r=>r.quarter===4).map(r=>{const total=R.categories.reduce((a,k)=>a+r.values[k],0);return `<div class="gj-composition-row"><b>${r.year}</b><div class="gj-stacked" aria-label="${esc(R.categories.map(k=>R.labels[k]+num(r.values[k],3)+'吨').join('，'))}">${R.categories.map((k,i)=>`<span style="width:${r.values[k]/total*100}%;background:${colors[i]}" title="${esc(R.labels[k])} ${num(r.values[k],3)}吨，占${num(r.values[k]/total*100)}%">${num(r.values[k],0)}<small>吨</small></span>`).join('')}</div></div>`;}).join('')+'<div class="gj-legend">'+R.categories.map((k,i)=>`<span><i style="background:${colors[i]}"></i>${esc(R.labels[k])}</span>`).join('')+'</div>';
    select('company-select',data.financials.map(r=>[r.id,r.name]));
    const metricNames={revenue:'收入',revenueYoy:'收入同比',profit:'归母利润',profitYoy:'归母利润同比',grossMargin:'毛利率',inventory:'期末存货',cashflow:'经营现金流',inventoryDays:'库存周转天数',onlineShare:'线上收入占比',onlineRevenueYoy:'线上收入同比',inventoryPrevious:'上年末存货'};
    function renderCompany(){const r=data.financials.find(c=>c.id===$('company-select').value);$('company-focus').innerHTML='<table id="company-field-table" class="gj-table"></table>';table('company-field-table',['指标','数值','来源状态','原始来源 / 页码'],Object.entries(r.metrics).map(([key,m])=>[esc(metricNames[key]||key),m?num(m.value,2)+(['revenueYoy','profitYoy','grossMargin','onlineShare','onlineRevenueYoy'].includes(key)?'%':key==='inventoryDays'?'天':'亿元'):'—',m?m.quality==='primary'?'原始公告':'妙想转引':'未收录',m?link(sources.get(m.sourceId),m.pdfPage):'—']));}
    select('operation-company',ops.companies.map(r=>[r.id,r.name]));
    let selectedOps=[];
    function operationPeriods(){const rows=ops.records.filter(r=>r.companyId===$('operation-company').value),periods=[...new Map(rows.map(r=>[r.periodStart+'|'+r.periodEnd,r])).entries()].sort((a,b)=>b[1].periodEnd.localeCompare(a[1].periodEnd)||a[1].periodType.localeCompare(b[1].periodType));select('operation-period',periods.map(([key,r])=>[key,r.fiscalLabel+' · '+r.periodStart+' — '+r.periodEnd]));renderOperations();}
    function renderOperations(){
      selectedOps=ops.records.filter(r=>r.companyId===$('operation-company').value&&r.periodStart+'|'+r.periodEnd===$('operation-period').value);
      const highlights=selectedOps.filter(r=>['sss_amount_yoy','sss_weight_yoy','fixed_price_gold_rsv_share','fixed_price_jewelry_rsv_share'].includes(r.metric)||['stores_end','stores_net'].includes(r.metric)&&r.channel==='全部');
      $('operations-summary').innerHTML=highlights.map(r=>`<span>${esc(P.operationLabels[r.metric])}<b class="${tone(r.metric.includes('yoy')?r.value:null)}">${r.metric.includes('yoy')?pct(r.value):num(r.value,r.unit==='家'?0:1)+esc(r.unit)}</b>${esc(r.scope)}</span>`).join('');
      if($('operation-company').value==='ctf')for(const [key,label] of [['stores_opened','内地新开 · 城市层级合计'],['stores_closed','内地关闭 · 城市层级合计']]){const rows=selectedOps.filter(r=>r.metric===key);if(rows.length===4)$('operations-summary').innerHTML+=`<span>${esc(label)}<b>${num(rows.reduce((a,r)=>a+r.value,0),0)}家</b>计算值</span>`;}
      table('operations-table',['指标','数值','地区 / 渠道','产品与品牌范围','期间','原始公告'],selectedOps.map(r=>[esc(P.operationLabels[r.metric]),num(r.value,r.unit==='家'?0:1)+esc(r.unit),esc(r.region+' / '+r.channel),esc(r.scope),esc(r.fiscalLabel)+`<small>${esc(r.periodStart+' — '+r.periodEnd)}</small>`,link(os.get(r.sourceId),r.pdfPage)]));
    }
    let selectedBenchmark=[],selectedQuotes=[],selectedBrandHistory=[];
    const groups=new Map();for(const q of prices.quotes){const key=JSON.stringify(['brandId','market','city','product','priceBasis','purity','includesLabor','includesTax','currency','unit','sourceId','verification'].map(k=>q[k]));if(!groups.has(key))groups.set(key,[]);groups.get(key).push(q);}
    const brandName=id=>prices.brands.find(b=>b.id===id)?.name||id;
    const groupList=[...groups.values()].sort((a,b)=>a[0].verification.localeCompare(b[0].verification)||brandName(a[0].brandId).localeCompare(brandName(b[0].brandId)));
    select('brand-series',groupList.map((rows,i)=>[String(i),brandName(rows[0].brandId)+' · '+(rows[0].verification==='verified_primary'?'官方指导价':'第三方转引')+' · '+(rows[0].purity?rows[0].purity*1000+'‰':'纯度未披露')+' · '+rows.length+'期']));
    select('quote-brand',[['all','全部10品牌'],...prices.brands.map(b=>[b.id,b.name])]);
    select('quote-date',[...[...new Set(prices.quotes.map(r=>r.quoteDate))].sort().reverse().map(d=>[d,d]),['all','全部已收录日期']]);
    function renderPrices(){
      const start=$('price-start').value,end=$('price-end').value,interval=P.historyWindow(prices.quotes,start,end);
      if(interval.error){$('price-range-note').textContent=interval.error;selectedBenchmark=[];selectedQuotes=[];selectedBrandHistory=[];for(const id of ['benchmark-chart','brand-chart'])$(id).innerHTML='<div class="gj-empty">'+esc(interval.error)+'</div>';for(const id of ['benchmark-table','quotes-table'])$(id).innerHTML='';$('benchmark-export').disabled=true;$('quotes-export').disabled=true;$('brand-history-export').disabled=true;return;}
      selectedBenchmark=P.historyWindow(P.benchmarkSeries(prices.benchmarks,$('benchmark-type').value),start,end).rows;const type=$('benchmark-type').value==='close'?'收盘价':'加权平均价';
      chart('benchmark-chart',[{name:'Au99.99 '+type,points:selectedBenchmark.map(r=>({x:dayX(r.quoteDate),label:r.quoteDate,value:r.price}))}],{unit:'元/克',zero:false,title:'上金所Au99.99 '+type});
      const summary=P.historySummary(selectedBenchmark);$('benchmark-caption').textContent=summary?summary.count+'个交易日 · '+summary.start+' — '+summary.end+' · 最新 '+num(summary.last,2)+'元/克'+(summary.change===null?' · 单点无涨跌':' · 首末变化 '+pct(summary.percent)):'所选区间未收录观测';
      $('price-range-note').textContent='';
      table('benchmark-table',['日期','合约 / 口径','元/克','原始披露'],selectedBenchmark.slice().reverse().map(r=>[esc(r.quoteDate),esc(r.instrument+' / '+type),num(r.price,2),link(ps.get(r.sourceId))]));
      const original=groupList[Number($('brand-series').value)],rows=P.historyWindow(original,start,end).rows;
      selectedBrandHistory=rows;selectedQuotes=interval.rows.filter(r=>($('quote-date').value==='all'||r.quoteDate===$('quote-date').value)&&($('quote-brand').value==='all'||r.brandId===$('quote-brand').value));
      chart('brand-chart',[{name:brandName(original[0].brandId)+' · '+(original[0].verification==='verified_primary'?'官方':'第三方'),points:rows.map(r=>({x:dayX(r.quoteDate),label:r.quoteDate,value:r.price,note:'挂牌价，税费及工费未披露'}))}],{unit:'元/克',zero:false,title:'固定来源与口径的品牌挂牌价历史'});
      table('quotes-table',['品牌 / 日期','挂牌价 · 元/克','纯度 / 工费 / 税','来源与核验'],selectedQuotes.slice().reverse().map(r=>{const s=ps.get(r.sourceId);return [esc(brandName(r.brandId))+`<small>${esc(r.quoteDate)}</small>`,num(r.price,2),esc((r.purity?r.purity*1000+'‰':'未披露')+' / '+(r.includesLabor===null?'工费未披露':r.includesLabor?'含工费':'不含工费')+' / '+(r.includesTax===null?'税未披露':r.includesTax?'含税':'不含税')),link(s)+`<small>${r.verification==='verified_primary'?'原始来源已核验':'第三方转引 · 待官网复核'}</small>`];}));
      $('benchmark-export').disabled=!selectedBenchmark.length;$('quotes-export').disabled=!selectedQuotes.length;$('brand-history-export').disabled=!selectedBrandHistory.length;
    }
    table('sources-table',['来源','披露期间','发布时间','来源类型'],data.sources.map(s=>[link(s),esc(s.period),esc(s.publishedAt||'未提供'),s.quality==='primary'?'原始披露':'妙想转引 · 待公告复核']));
    table('audit-table',['品牌','核验结果','原始来源入口'],audit.brandChecks.map(r=>[esc(brandName(r.brandId)),`<span class="gj-audit-note">${r.primaryStatus==='separate_verified_observation'?'已收录官方观测':'未获官方报价'}</span>`,link({url:r.attemptedPrimaryUrl,name:'官网'})]));
    const seriesById=new Map(macro.series.map(s=>[s.id,s])),nextMeeting=macro.meetings[0],firstSnapshot=M.latestSnapshot(nextMeeting);
    const real=seriesById.get('real10'),dxy=seriesById.get('dxy'),today=new Date().toISOString().slice(0,10);
    const delta=(s)=>{const end=s.observations.at(-1).date,anchor=end.slice(0,7)+'-01',monthEnd=new Date(Date.parse(anchor+'T00:00:00Z')-86400000).toISOString().slice(0,10);return M.changeSince(s,monthEnd);};
    const changeLabel=s=>{const d=delta(s);return d?'较'+d.from+' '+(s.unit==='%'?(d.bp>0?'+':'')+num(d.bp,0)+'bp':s.id==='usdcny'?(d.absolute>0?'+':'')+num(d.absolute,4):pct(d.percent)):'基期未收录';};
    $('core-kpis').innerHTML=stat('Au99.99 · 收盘价',num(benchmark.price,2)+'<small>元/克</small>',esc(benchmark.quoteDate)+' · 上金所',true)+stat('10月会议 · 加息概率',num(M.probabilities(firstSnapshot,macro.policy.range).hike)+'<small>%</small>',esc(firstSnapshot.observedDate)+' · CME原始快照')+stat('美国10年实际利率',num(real.observations.at(-1).value,2)+'<small>%</small>',esc(real.observations.at(-1).date+' · '+changeLabel(real))+'<br><span class="gj-provider">妙想转引</span>')+stat('美元指数 DXY',num(dxy.observations.at(-1).value,3),esc(dxy.observations.at(-1).date+' · '+changeLabel(dxy))+'<br><span class="gj-provider">妙想转引</span>');
    select('fed-meeting',macro.meetings.map(m=>[m.meetingDate,m.meetingDate+'会议']));
    function renderFed(){
      const meeting=macro.meetings.find(m=>m.meetingDate===$('fed-meeting').value),snapshot=M.latestSnapshot(meeting),probs=M.probabilities(snapshot,macro.policy.range),week=meeting.snapshots[0],old=M.probabilities(week,macro.policy.range),move=probs.hike-old.hike,age=M.ageDays(snapshot.observedDate,today),past=meeting.meetingDate<today;
      $('policy-current').innerHTML='当前目标区间 '+macro.policy.range.map(v=>num(v,2)).join('—')+'% · '+esc(macro.policy.decisionDate)+'决议 '+link({...ms.get(macro.policy.sourceId),name:'决议原文'});
      $('fed-probability').innerHTML=`<div class="gj-fed-heading"><span>${meeting.meetingDate==='2026-10-28'?'10月会议':'截至12月会议'} · 高于当前利率的概率</span><strong>${num(probs.hike)}<small>%</small></strong><p>较${esc(week.observedDate)} ${move>0?'+':''}${num(move)}个百分点 ${past?'<b class="gj-stale">会议已结束 · 历史快照</b>':age>3?'<b class="gj-stale">历史快照 · 距今'+age+'天</b>':''}</p></div><div class="gj-probability-rows">${snapshot.ranges.filter(r=>r.probability>0).map(r=>`<div class="gj-probability-row" data-chart-tooltip="${esc('CME FedWatch · '+meeting.meetingDate+'\n快照：'+snapshot.observedDate+'\n目标区间：'+num(r.lower,2)+'—'+num(r.upper,2)+'%\n概率：'+num(r.probability)+'%')}"><span>${num(r.lower,2)}—${num(r.upper,2)}%<small>${r.lower===macro.policy.range[0]?'维持':r.lower>macro.policy.range[0]?'累计加息'+Math.round((r.lower-macro.policy.range[0])*100)+'bp':'累计降息'+Math.round((macro.policy.range[0]-r.lower)*100)+'bp'}</small></span><div><i style="width:${r.probability}%;background:${r.lower===macro.policy.range[0]?'#aab0c4':'#5158aa'}"></i></div><b>${num(r.probability)}%</b></div>`).join('')}</div><div class="gj-prob-total"><span>降息 ${num(probs.cut)}%</span><span>维持 ${num(probs.hold)}%</span><span>加息 ${num(probs.hike)}%</span></div>`;
      table('fed-history-table',['CME观测日 · CT',...snapshot.ranges.map(r=>num(r.lower,2)+'—'+num(r.upper,2)+'%')],meeting.snapshots.slice().reverse().map(s=>[esc(s.observedDate)+(s.observedAt?'<small>'+esc(s.observedAt.slice(11,19))+' CT</small>':'<small>原表未披露具体时刻</small>'),...snapshot.ranges.map(r=>{const v=s.ranges.find(t=>t.lower===r.lower&&t.upper===r.upper);return v?num(v.probability)+'%':'—';})]));
      $('policy-sep').innerHTML='<p>'+esc(macro.projections.asOf)+' · 年末利率中位数</p><div>'+macro.projections.points.map(p=>'<span>'+p.year+'年<strong>'+num(p.value)+'%</strong></span>').join('')+'</div><p>'+link(ms.get(macro.projections.sourceId))+'</p>';
      $('fed-source').innerHTML=link(ms.get(snapshot.sourceId))+' · '+esc(snapshot.observedDate+' '+snapshot.observedAt.slice(11,19))+' CT（UTC'+esc(snapshot.observedAt.slice(-6))+'）';
    }
    select('macro-indicator',macro.series.map(s=>[s.id,s.name]));
    function renderMacro(){const s=seriesById.get($('macro-indicator').value),last=s.observations.at(-1),window=$('macro-window').value,rows=s.observations.filter(r=>window==='all'||dayX(r.date)>dayX(last.date)-Number(window));$('macro-caption').textContent=rows[0].date+' — '+last.date+' · 妙想 / Choice 转引';$('macro-latest').innerHTML='<strong>'+num(last.value,s.id==='usdcny'?4:2)+'</strong><span>'+esc(s.unit+' · '+changeLabel(s))+'</span>';chart('macro-chart',[{name:s.name,points:rows.map(r=>({x:dayX(r.date),label:r.date,value:r.value,note:'妙想转引 · '+s.reportedPublisher}))}],{unit:s.unit,title:s.name+'历史',zero:false,gap:3});$('macro-mechanism').innerHTML=link(ms.get(s.sourceId));}
    const flows=new Map(macro.flows.map(r=>[r.id,r])),etf=flows.get('etf-flows'),holdings=flows.get('etf-holdings'),cb=flows.get('central-banks'),position=flows.get('managed-money');
    $('gold-flows').innerHTML=[etf,cb].map(r=>'<div><span>'+esc(r.name)+'</span><strong>+'+num(r.value,0)+'<small>'+esc(r.unit)+'</small></strong><p>'+esc(r.periodEnd.slice(0,7))+' · '+link(ms.get(r.sourceId))+'</p></div>').join('');
    table('position-table',['观察项','数值','统计时点'],[[esc(holdings.name),num(holdings.value,0)+'吨<small>9月增加67吨</small>',esc(holdings.periodEnd)],[esc(position.name)+'<small>WGC转引CFTC</small>',num(position.value,0)+'吨<small>9月减少84吨</small>',esc(position.periodEnd)]]);
    const timeCN=value=>new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value));
    const upcoming=macro.events.filter(r=>Date.parse(r.scheduledAt)>=Date.now());
    $('macro-events').innerHTML=upcoming.length?upcoming.map(r=>'<article><time>'+esc(timeCN(r.scheduledAt))+'</time><div><b>'+esc(r.name)+'</b></div>'+link(ms.get(r.sourceId))+'</article>').join(''):'<p class="gj-empty">已收录日历事件已结束，请查看官方最新日历。</p>';
    $('macro-releases').innerHTML=macro.releases.map(r=>'<div><span>'+esc(r.name+(['cpi','corecpi'].includes(r.id)?' · 未季调':['payroll','unemployment'].includes(r.id)?' · 季调':''))+'</span><strong>'+(r.id==='payroll'&&r.value>0?'+':'')+num(r.value,r.id==='payroll'?0:1)+'<small>'+esc(r.unit)+'</small></strong><p>'+esc(r.periodEnd.slice(0,7))+' · '+esc(r.publishedAt)+'发布 · '+link({...ms.get(r.sourceId),name:r.id==='corepce'?'BEA':'BLS'})+'</p></div>').join('');
    const qualityName={primary:'原始发布',provider:'妙想 / Choice 转引',compiled:'机构转引'};
    table('macro-sources-table',['来源','核验状态','发布 / 核对日期'],macro.sources.map(s=>[link(s),esc(qualityName[s.quality]),esc(s.publishedAt||s.checkedAt)+(s.publishedAt?'发布':'核对')]));
    $('fed-meeting').addEventListener('change',renderFed);$('macro-indicator').addEventListener('change',renderMacro);$('macro-window').addEventListener('change',renderMacro);
    $('macro-export').addEventListener('click',()=>download('黄金-金价驱动.csv',['模块','指标','统计日或期间末','发布日期或观测时刻','目标会议或年末','口径','数值','单位','来源状态','URL'],[
      ...macro.series.flatMap(s=>s.observations.map(r=>['历史序列',s.name,r.date,'','',s.originalName,r.value,s.unit,qualityName[s.quality],ms.get(s.sourceId).url])),
      ...macro.meetings.flatMap(m=>m.snapshots.flatMap(s=>s.ranges.map(r=>['会议预期','目标利率区间概率',s.observedDate,s.observedAt||'具体时刻未披露',m.meetingDate,r.lower+'—'+r.upper+'%（利率）；观测时区America/Chicago',r.probability,'%',qualityName[s.quality],ms.get(s.sourceId).url]))),
      ['政策事实','联邦基金目标利率下限',macro.policy.decisionDate,'','','当前目标区间',macro.policy.range[0],'%',qualityName[macro.policy.quality],ms.get(macro.policy.sourceId).url],
      ['政策事实','联邦基金目标利率上限',macro.policy.decisionDate,'','','当前目标区间',macro.policy.range[1],'%',qualityName[macro.policy.quality],ms.get(macro.policy.sourceId).url],
      ...macro.projections.points.map(r=>['官员预测','SEP年末利率中位数',macro.projections.asOf,macro.projections.asOf,r.year,macro.projections.basis,r.value,'%',qualityName[macro.projections.quality],ms.get(macro.projections.sourceId).url]),
      ...[...macro.releases,...macro.flows].map(r=>['统计发布',r.name,r.periodEnd,r.publishedAt,'',r.basis,r.value,r.unit,qualityName[r.quality],ms.get(r.sourceId).url])
    ]));
    function renderView(){if(view==='overview'){renderMacro();renderFed();}if(view==='demand')renderDemand();if(view==='companies')renderCompany();if(view==='prices')renderPrices();}
    const allowed=['overview','demand','companies','prices','sources'];
    function setView(next,update=true){view=allowed.includes(next)?next:'overview';document.querySelectorAll('.gj-view').forEach(s=>s.hidden=s.id!=='view-'+view);document.querySelectorAll('.gj-tabs button').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));});if(update)history.replaceState(null,'','#'+view);renderView();}
    document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.go)));
    document.querySelectorAll('#retail-mode button').forEach(b=>b.addEventListener('click',()=>{retailMode=b.dataset.mode;document.querySelectorAll('#retail-mode button').forEach(a=>{a.classList.toggle('active',a===b);a.setAttribute('aria-pressed',String(a===b));});renderDemand();}));
    $('retail-window').addEventListener('change',renderDemand);$('volume-mode').addEventListener('change',renderDemand);$('company-select').addEventListener('change',renderCompany);$('operation-company').addEventListener('change',operationPeriods);$('operation-period').addEventListener('change',renderOperations);$('benchmark-type').addEventListener('change',renderPrices);$('brand-series').addEventListener('change',renderPrices);$('quote-brand').addEventListener('change',renderPrices);$('quote-date').addEventListener('change',renderPrices);
    $('demand-export').addEventListener('click',()=>{const mode=$('volume-mode').value,cumulative=mode.startsWith('cumulative'),vs=cumulative?consumption:quarter;download('黄金-需求.csv',['模块','期间','口径','指标','数值','单位','同比','同比口径','来源URL'],[...filteredRetail().map(r=>['零售',r.period,r.basis,'金银珠宝类零售额',r.amount,'亿元',r.yoy,'统计局原始公布',sources.get(r.sourceId).url]),...vs.flatMap(r=>R.categories.map(k=>['消费量',r.period,r.basis,R.labels[k],r.values[k],'吨',r.yoy[k],cumulative?'协会原始公布':'单季同比计算值',(cumulative?[r.sourceId]:r.yoyInputSourceIds).map(id=>sources.get(id).url).join(' | ')]))]);});
    $('finance-export').addEventListener('click',()=>download('黄金-2026H1财务.csv',['公司','期间开始','期间结束','币种','指标','数值','单位','来源状态','来源','URL','PDF页码'],data.financials.flatMap(r=>Object.entries(r.metrics).map(([k,m])=>[r.name,r.periodStart,r.periodEnd,r.currency,k,m?.value??null,['revenueYoy','profitYoy','grossMargin','onlineShare','onlineRevenueYoy'].includes(k)?'%':k==='inventoryDays'?'天':'亿元',m?.quality??'missing',m?sources.get(m.sourceId).name:'',m?sources.get(m.sourceId).url:null,m?.pdfPage]))));
    $('operations-export').addEventListener('click',()=>download('黄金-经营指标.csv',['公司','期间开始','期间结束','财年','地区','渠道','范围','指标','数值','单位','URL','PDF页码'],selectedOps.map(r=>[ops.companies.find(c=>c.id===r.companyId).name,r.periodStart,r.periodEnd,r.fiscalLabel,r.region,r.channel,r.scope,P.operationLabels[r.metric],r.value,r.unit,os.get(r.sourceId).url,r.pdfPage])));
    $('benchmark-export').addEventListener('click',()=>download('上金所-Au99.99.csv',['日期','合约','价格口径','数值','单位','原始URL'],selectedBenchmark.map(r=>[r.quoteDate,r.instrument,r.priceType,r.price,'CNY/g',ps.get(r.sourceId).url])));
    function downloadQuotes(name,rows){const enriched=rows.map(r=>({...r,brandName:brandName(r.brandId),sourceName:ps.get(r.sourceId).name,sourceUrl:ps.get(r.sourceId).url,capturedDate:ps.get(r.sourceId).capturedDate}));const u=URL.createObjectURL(new Blob([P.csv(enriched)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
    $('quotes-export').addEventListener('click',()=>downloadQuotes('品牌金价-筛选报价.csv',selectedQuotes));
    $('brand-history-export').addEventListener('click',()=>downloadQuotes('品牌金价-所选历史.csv',selectedBrandHistory));
    $('price-start').addEventListener('change',renderPrices);$('price-end').addEventListener('change',renderPrices);$('price-reset').addEventListener('click',()=>{$('price-start').value='';$('price-end').value='';renderPrices();});
    operationPeriods();renderPrices();$('dashboard').hidden=false;const old={ 'brand-panel':'prices','benchmark-panel':'prices','industry-panel':'demand','company-panel':'companies','source-panel':'sources'};setView(old[location.hash.slice(1)]||location.hash.slice(1)||'overview');window.addEventListener('hashchange',()=>setView(location.hash.slice(1),false));let timer;window.addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(renderView,160);});
  }catch(error){$('load-error').innerHTML='数据暂时无法读取。 <button class="portal-button" id="gold-retry" type="button">重试</button>';$('gold-retry').onclick=()=>location.reload();$('load-error').hidden=false;$('asof').textContent='数据加载失败';}
})();

