(async function(){
  'use strict';const D=SiteData,$=id=>document.getElementById(id);let manifest,rows=[],points=[],metric='',page=1;const size=18;
  const configs={hotel:{name:'酒店',id:'hotel_industry_weekly',detail:'hotel-dashboard.html',metrics:[['revpar','全国 RevPAR','元'],['adr','平均房价','元'],['occupancy_rate','入住率','%']],date:r=>r.end_date,keep:r=>r.region==='全国'&&r.segment==='全部'},dutyfree:{name:'免税',id:'dutyfree_monthly',detail:'dutyfree-dashboard.html',metrics:[['shopping_sales_cny_100m','离岛免税销售额','亿元'],['shoppers_10k','购物人数','万人'],['items_10k','购物件数','万件']],date:r=>r.period_id,keep:()=>true},gold:{name:'黄金珠宝',id:'gold',metrics:null,date:r=>(r['数据日期']||'').slice(0,10),keep:()=>true},dining:{name:'餐饮茶饮',id:'dining',metrics:[['餐饮收入(亿元)','全国餐饮收入','亿元'],['餐饮收入同比增速(%)','餐饮收入同比','%'],['限额以上餐饮(亿元)','限额以上餐饮收入','亿元']],date:r=>r['月份'],keep:()=>true},overseas:{name:'跨境出海',id:'crossborder',metrics:null,date:r=>(r['数据日期']||'').slice(0,10),keep:()=>true}};
  let key='hotel',generation=0;
  function buildMetrics(c){return c.metrics||[...new Set(rows.map(r=>r['指标名称']).filter(Boolean))].map(v=>[v,v,rows.find(r=>r['指标名称']===v)?.['单位']||'']);}
  function derive(){
    const c=configs[key],m=buildMetrics(c).find(x=>x[0]===metric),selected=rows.filter(c.keep);
    const hotelIndex=new Map(selected.map(r=>[r.year+'-'+r.week,r]));
    const yoyFields={shopping_sales_cny_100m:'sales_yoy_pct',shoppers_10k:'shoppers_yoy_pct',items_10k:'items_yoy_pct','餐饮收入(亿元)':'餐饮收入同比增速(%)','限额以上餐饮(亿元)':'限额以上同比增速(%)'};
    points=selected.filter(r=>c.metrics||r['指标名称']===metric).map(r=>{
      let value=D.number(r[c.metrics?metric:'数值']),yoy=r['同比(%)']??r[yoyFields[metric]];
      if(key==='hotel'){const prior=hotelIndex.get((Number(r.year)-1)+'-'+r.week),old=D.number(prior?.[metric]);yoy=old!=null&&old!==0&&value!=null?(value/old-1)*100:null;if(metric==='occupancy_rate'&&value!=null)value*=100;}
      return {date:c.date(r),value,yoy,source:r['数据来源']||r.source||'仓库原始数据'};
    }).filter(r=>r.date).sort((a,b)=>a.date.localeCompare(b.date));
    const range=Number($('range').value);if(range)points=points.slice(-range);const last=points.at(-1),first=points[0];$('metric-title').textContent=m?.[1]||metric;$('metric-note').textContent=(m?.[2]||'')+' · '+(key==='hotel'?'全国 / 全部档次 · 周度 · 同周号相对同比，未作节假日错期调整':key==='dining'?'月度':'源数据口径');$('chart').innerHTML=D.trend(points,(m?.[1]||metric)+'历史趋势');$('stats').innerHTML=[['最新值',D.fmt(last?.value)+' '+(m?.[2]||''),'按所选指标口径'],['数据截至',last?.date||'—','源数据日期'],['同比变化',D.number(last?.yoy)==null?'—':D.fmt(last.yoy)+'%','缺失时显示 —'],['观测记录',points.length+' 条',(first?.date||'—')+' 起']].map(x=>'<div class="portal-stat"><span>'+D.esc(x[0])+'</span><strong>'+D.esc(x[1])+'</strong><small>'+D.esc(x[2])+'</small></div>').join('');renderTable();
  }
  function renderTable(){const all=points.slice().reverse(),count=Math.max(1,Math.ceil(all.length/size));page=Math.min(page,count);$('history').innerHTML=all.slice((page-1)*size,page*size).map(p=>'<tr><td>'+D.esc(p.date)+'</td><td>'+D.fmt(p.value,2)+'</td><td>'+D.fmt(p.yoy,2)+'</td><td>'+D.esc(p.source)+'</td></tr>').join('')||'<tr><td colspan="4">暂无已收录数据</td></tr>';$('page-label').textContent=page+' / '+count+' · '+all.length+' 条';$('prev').disabled=page<=1;$('next').disabled=page>=count;}
  async function select(){const requested=location.hash.slice(1);key=configs[requested]?requested:'hotel';const c=configs[key],turn=++generation;$('sector-tabs').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.key===key)));$('page-title').textContent=c.name+'行业数据';$('status').textContent='正在读取'+c.name+'数据…';$('content').hidden=true;try{const source=manifest.datasets.find(d=>d.id===c.id);const loaded=await D.table(source.file);if(turn!==generation)return;rows=loaded;const metrics=buildMetrics(c);metric=metrics.find(m=>/Au9999/.test(m[0]))?.[0]||metrics[0]?.[0]||'';$('metric').innerHTML=metrics.map(m=>'<option value="'+D.esc(m[0])+'">'+D.esc(m[1])+'</option>').join('');$('metric').value=metric;$('download').href=source.file;$('specialist').hidden=!c.detail;$('specialist').href=c.detail||'#';$('specialist').textContent='进入'+c.name+'专题 ↗';page=1;derive();$('content').hidden=false;$('status').textContent='';}catch(e){if(turn!==generation)return;$('status').innerHTML='暂时无法读取该行业数据。<button class="portal-button" id="retry-industry">重试</button>';$('retry-industry').onclick=select;}}
  $('sector-tabs').onclick=e=>{const b=e.target.closest('button');if(b)location.hash=b.dataset.key;};$('metric').onchange=e=>{metric=e.target.value;page=1;derive();};$('range').onchange=()=>{page=1;derive();};$('prev').onclick=()=>{page--;renderTable();};$('next').onclick=()=>{page++;renderTable();};addEventListener('hashchange',()=>{if(manifest)select();});try{manifest=await D.json('data-manifest.json');select();}catch(e){$('status').innerHTML='数据目录读取失败。<button class="portal-button" onclick="location.reload()">重新加载</button>';}
})();
