(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.QuotesModel=api;})(typeof window==='object'?window:{},function(){
  'use strict';
  const markets={CN:{label:'A股',currency:'CNY',timeLabel:'北京时间',timeZone:'Asia/Shanghai'},HK:{label:'港股',currency:'HKD',timeLabel:'香港时间',timeZone:'Asia/Hong_Kong'},US:{label:'美股',currency:'USD',timeLabel:'来源市场时间',timeZone:'America/New_York'}};
  function market(code){return /\.HK$|^HSI\.HI$/i.test(code)?'HK':/\.(O|N)$/i.test(code)?'US':'CN';}
  function number(value){if(value==null||String(value).trim()==='')return null;const n=Number(value);return Number.isFinite(n)?n:null;}
  function timestamp(value){let s=String(value||'').trim();if(/^\d{14}$/.test(s))s=s.replace(/^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})$/,'$1-$2-$3 $4:$5:$6');else s=s.replace(/\//g,'-');const match=s.match(/^(\d{4}-\d{2}-\d{2})(?:[ T](\d{2}:\d{2}(?::\d{2})?))?$/);if(!match)return '';const [y,m,d]=match[1].split('-').map(Number),day=new Date(Date.UTC(y,m-1,d));if(day.getUTCFullYear()!==y||day.getUTCMonth()!==m-1||day.getUTCDate()!==d)return '';if(match[2]){const [h,min,sec=0]=match[2].split(':').map(Number);if(h>23||min>59||sec>59)return '';}return match[1]+(match[2]?' '+match[2]:'');}
  function parse(raw,code,retrievedAt){if(typeof raw!=='string')return null;const f=raw.split('~'),price=number(f[3]),asOf=timestamp(f[30]);if(f.length<35||price==null||price<=0||!asOf)return null;const positive=i=>{const n=number(f[i]);return n!=null&&n>0?n:null;};const providerCode=market(code)==='US'&&/^[A-Z][A-Z0-9.-]*$/.test(f[2])&&f[2].split('.')[0]===code.split('.')[0]?'us'+f[2]:null;return {code,name:f[1],market:market(code),providerCode,price,previousClose:positive(4),open:positive(5),change:number(f[31]),percent:number(f[32]),high:positive(33),low:positive(34),asOf,retrievedAt,failed:false};}
  function accept(previous,incoming){
    if(!previous)return {...incoming,unchanged:false};
    // Source timestamps, never the local retrieval clock, identify a new observation.
    if(incoming.asOf<previous.asOf)return {...previous,failed:false,unchanged:true};
    return {...incoming,unchanged:incoming.asOf===previous.asOf};
  }
  function dayFor(code,now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:markets[market(code)].timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(now);}
  function state(quote,now=new Date()){if(!quote)return '暂无报价';if(quote.failed)return '读取失败 · 上次报价';if(quote.unchanged)return '来源时间未更新 · 保留报价';return quote.asOf.slice(0,10)===dayFor(quote.code,now)?'当日报价':'上次报价';}
  function filter(companies,quotes,f){const q=(f.q||'').trim().toLowerCase(),watch=new Set(f.watchlist||[]);const rows=companies.filter(c=>(!f.onlyWatch||watch.has(c.code))&&(!f.market||market(c.code)===f.market)&&(!f.sector||f.sector.split(',').includes(c.sector))&&(!q||[c.name,c.code,...(c.aliases||[])].join(' ').toLowerCase().includes(q)));return rows.sort((a,b)=>{if(f.sort==='name'||f.sort==='name-desc')return a.name.localeCompare(b.name,'zh')*(f.sort==='name-desc'?-1:1);const x=quotes[a.code]?.percent,y=quotes[b.code]?.percent;if(!Number.isFinite(x))return Number.isFinite(y)?1:a.name.localeCompare(b.name,'zh');if(!Number.isFinite(y))return -1;return (f.sort==='change-asc'?x-y:y-x)||a.name.localeCompare(b.name,'zh');});}
  function watchlist(value,companies){const allowed=new Set(companies.map(c=>c.code));return Array.isArray(value)?[...new Set(value.filter(code=>typeof code==='string'&&allowed.has(code)))]:[];}
  function movingAverage(rows,window){return rows.map((r,i)=>{if(i+1<window)return null;const values=rows.slice(i+1-window,i+1).map(row=>number(row[2]));return values.every(v=>v!=null&&v>0)?values.reduce((a,b)=>a+b,0)/window:null;});}
  const aliases={'中国中免':'中免','华住集团-S':'华住','携程集团-S':'携程','亚朵集团':'亚朵','百胜中国':'百胜中国'};
  function researchKeyword(company){return aliases[company.name]||company.name;}
  function relatedResearch(dbs,company){const term=researchKeyword(company),seen=new Set();return (dbs||[]).flatMap(db=>(db.rows||[]).map(row=>({kind:db.id,title:row['标题']||'',published:row['时间']||row['日期']||'',company:row['相关标的']||'',url:row['原文链接']||''}))).filter(row=>{const key=row.url||row.title+'|'+row.published;if(seen.has(key)||![row.title,row.company].some(text=>text.includes(term)))return false;seen.add(key);return true;}).sort((a,b)=>b.published.localeCompare(a.published)).slice(0,3);}
  function breadth(companies,quotes){const valid=companies.map(c=>quotes[c.code]).filter(Boolean);return {total:companies.length,valid:valid.length,up:valid.filter(q=>q.percent>0).length,down:valid.filter(q=>q.percent<0).length,flat:valid.filter(q=>q.percent===0).length,missing:companies.length-valid.length,percentMissing:valid.filter(q=>q.percent==null).length};}
  function candles(rows){return rows.filter(r=>Array.isArray(r)&&r.length>=5&&/^\d{4}-\d{2}-\d{2}$/.test(r[0])&&timestamp(r[0])===r[0]&&r.slice(1,5).every(v=>number(v)!=null&&number(v)>0)&&Number(r[3])>=Math.max(Number(r[1]),Number(r[2]),Number(r[4]))&&Number(r[4])<=Math.min(Number(r[1]),Number(r[2]),Number(r[3]))).sort((a,b)=>a[0].localeCompare(b[0]));}
  function adjustment(data,code,period,isIndex){if(isIndex)return '指数';const series=data?.data?.[code];return Array.isArray(series?.['qfq'+period])&&series['qfq'+period].length?'前复权':'源数据';}
  function intraday(rows,code){const windows=market(code)==='US'?[[570,960]]:market(code)==='HK'?[[570,720],[780,960]]:[[570,690],[780,900]];const valid=rows.filter(r=>{if(!r||!/^\d{12}$/.test(r[0])||!timestamp(String(r[0]).replace(/^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})$/,'$1-$2-$3 $4:$5'))||!(number(r[2])>0))return false;const time=Number(r[0].slice(8,10))*60+Number(r[0].slice(10,12));return windows.some(([start,end])=>time>=start&&time<=end);}).sort((a,b)=>a[0].localeCompare(b[0]));const session=valid.at(-1)?.[0].slice(0,8);return valid.filter(r=>r[0].startsWith(session));}
  // Square-ish cells, a bounded viewport, and no unreadable tiny tiles for large pools.
  function heatLayout(count,width=600){const columns=Math.min(width<400?4:8,Math.max(1,Math.ceil(Math.sqrt(count||1))),Math.max(1,Math.floor(width/64)));return {columns,pageSize:columns*columns,height:Math.min(560,Math.max(180,width))};}
  function csv(companies,quotes){const field=v=>'"'+String(v??'').replace(/"/g,'""').replace(/^[=+@\-\t\r]/,"'$&")+'"';const rows=[['公司','证券代码','行业','市场','币种','最新价','涨跌额','涨跌幅(%)','前收','开盘','最高','最低','来源报价时间','最近读取时间','状态'],...companies.map(c=>{const q=quotes[c.code],m=markets[market(c.code)];return [c.name,c.code,c.sector,m.label,m.currency,q?.price,q?.change,q?.percent,q?.previousClose,q?.open,q?.high,q?.low,q?.asOf,q?.retrievedAt,q?.failed?'读取失败 · 保留上次报价':q?'来源报价（可能延迟）':'暂无报价'];})];return '\uFEFF'+rows.map(row=>row.map(v=>typeof v==='number'&&Number.isFinite(v)?String(v):field(v)).join(',')).join('\r\n');}
  function directory(data){if(!Array.isArray(data?.companies)||!data.companies.length)throw Error('Invalid coverage directory');const seen=new Set();return data.companies.map(c=>{if(!c||!/^\d{6}\.(SH|SZ)$|^\d{4,5}\.HK$|^[A-Z][A-Z0-9-]*\.(O|N)$/.test(c.code)||typeof c.name!=='string'||!c.name.trim()||typeof c.sector!=='string'||!c.sector.trim()||seen.has(c.code))throw Error('Invalid or duplicate coverage identity');seen.add(c.code);return {...c,aliases:Array.isArray(c.aliases)?c.aliases.filter(a=>typeof a==='string'):[]};});}
  return {markets,market,number,timestamp,parse,accept,dayFor,state,filter,watchlist,movingAverage,researchKeyword,relatedResearch,breadth,candles,adjustment,intraday,heatLayout,csv,directory};
});
