const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/quotes.js','utf8');
function rig(extra=false,query=''){
  const nodes=new Map(),events={},scripts=[],intervals=new Map(),timeouts=new Map();let id=0,time=0;
  function node(name){if(!nodes.has(name))nodes.set(name,{hidden:name==='content',checked:true,value:'',dataset:{},style:{},innerHTML:'',textContent:'',scrollTop:0,clientWidth:900,querySelectorAll:()=>[],querySelector:()=>null,setAttribute(){},focus(){},scrollIntoView(){}});return nodes.get(name);}
  const rowNodes=new Map();node('rows').appendChild=n=>{rowNodes.delete(n.dataset.company);rowNodes.set(n.dataset.company,n);};let lastRows='';node('rows').querySelectorAll=selector=>{if(selector!=='tr[data-company]')return [];const html=node('rows').innerHTML;if(html!==lastRows){lastRows=html;rowNodes.clear();for(const m of html.matchAll(/tr data-company="([^"]+)"/g))rowNodes.set(m[1],{dataset:{company:m[1]},children:Array.from({length:9},()=>({innerHTML:'',textContent:'',dataset:{},className:''}))});}return [...rowNodes.values()];};
  const document={hidden:false,body:{dataset:{siteSection:'quotes'}},activeElement:null,getElementById:node,addEventListener:(k,fn)=>events[k]=fn,createElement:()=>{const s={remove(){s.removed=true;}};return s;},head:{appendChild:s=>scripts.push(s)}};
  class Clock extends Date{constructor(...args){super(...(args.length?args:[1791511200000+time]));}static now(){return time;}}
  const ctx={document,console,AbortController,DOMException,URLSearchParams,Date:Clock,Intl,location:{search:query,pathname:'/quotes.html'},history:{replaceState(){}},localStorage:{getItem:()=>null,setItem(){}},matchMedia:()=>({matches:false}),addEventListener:(k,fn)=>events[k]=fn,setTimeout:(fn,ms)=>{timeouts.set(++id,{fn,ms});return id;},clearTimeout:id=>timeouts.delete(id),setInterval:(fn,ms)=>{intervals.set(++id,{fn,ms});return id;},clearInterval:id=>intervals.delete(id),QuotesModel:require('./quotes-model.js'),SinolinkKline:require('./market-kline.js'),SiteData:{esc:String,json:async url=>url==='data-manifest.json'?{datasets:[{id:'valuation',file:'v.csv'}]}:{dbs:[]},table:async()=>[{'证券代码':'600519.SH','公司名称':'测试公司','子行业':'餐饮'},...(extra?[{'证券代码':'600754.SH','公司名称':'第二公司','子行业':'酒店'}]:[])]}};
  // Build the poller in the same fake clock/timer realm as the browser.
  ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/quotes-poller.js','utf8'),ctx);vm.runInContext(source,ctx);
  const settle=async()=>{for(let i=0;i<15;i++)await Promise.resolve();};
  function respond(stamp='20261009100000',percent='1',second=null){const s=scripts.find(x=>!x.removed&&x.src.includes('qt.gtimg.cn'));assert.ok(s);for(const q of ['sh600519','sh000001','sz399006','hkHSI',...(second===null?[]:['sh600754'])]){const f=Array(50).fill('');f[1]='测试';f[3]='100';f[4]='99';f[30]=stamp;f[31]='1';f[32]=q==='sh600754'?second:percent;f[33]='101';f[34]='98';ctx['v_'+q]=f.join('~');}s.onload();}
  return {ctx,node,events,scripts,intervals,timeouts,settle,respond,cells:()=>node('rows').querySelectorAll('tr[data-company]')[0].children,setTime:t=>time=t};
}
test('real page wiring uses one-second requests, source seconds, lifecycle cancellation and recovery',async()=>{const r=rig();await r.settle();r.respond();await r.settle();assert.equal([...r.intervals.values()][0].ms,1000);assert.match(r.cells()[4].innerHTML,/10:00:00/);const tick=[...r.intervals.values()][0].fn;r.setTime(500);await tick();assert.match(r.node('status').textContent,/自动更新/);await r.node('refresh').onclick();assert.equal(r.scripts.filter(s=>s.src.includes('qt.gtimg.cn')).length,1);r.setTime(1000);tick();await r.settle();const live=r.scripts.filter(s=>!s.removed);r.ctx.document.hidden=true;r.events.visibilitychange();await r.settle();assert.equal(r.intervals.size,0);assert.ok(live.every(s=>s.removed));r.setTime(30000);r.ctx.document.hidden=false;r.events.visibilitychange();await r.settle();r.respond();await r.settle();assert.match(r.cells()[4].innerHTML,/10:00:00/);assert.doesNotMatch(r.cells()[4].innerHTML,/来源时间未更新|保留报价/);r.events.pagehide();await r.settle();assert.equal(r.intervals.size,0);r.setTime(60000);r.events.pageshow();await r.settle();assert.equal(r.intervals.size,1);r.respond('20261009100001');await r.settle();assert.match(r.cells()[4].innerHTML,/10:00:01/);r.events.pagehide();});
test('hidden load pauses automatic requests; returning resumes and manual requests share the cadence',async()=>{const r=rig();r.ctx.document.hidden=true;await r.settle();assert.equal(r.scripts.length,0);assert.equal(r.intervals.size,0);r.ctx.document.hidden=false;r.events.visibilitychange();await r.settle();assert.equal(r.intervals.size,1);r.respond();await r.settle();await r.node('refresh').onclick();assert.equal(r.scripts.filter(s=>s.src.includes('qt.gtimg.cn')).length,1);r.events.pagehide();});

test('clicking price, change, source time or row whitespace selects the company; favorite stays independent',async()=>{const r=rig(true);await r.settle();r.respond();await r.settle();assert.match(r.node('rows').innerHTML,/tr data-company="600754.SH"/);for(const area of ['price','percent','time','whitespace']){const target={closest:selector=>selector==='tr[data-company]'?{dataset:{company:'600754.SH'}}:null};r.node('rows').onclick({target});assert.equal(r.node('quote-title').textContent,'第二公司',area);r.node('rows').onclick({target:{closest:selector=>selector==='tr[data-company]'?{dataset:{company:'600519.SH'}}:null}});}r.node('rows').onclick({target:{closest:selector=>selector==='[data-watch]'?{dataset:{watch:'600754.SH'}}:{dataset:{company:'600754.SH'}}}});assert.equal(r.node('quote-title').textContent,'测试公司');assert.match(r.node('rows').innerHTML,/移除自选：第二公司/);r.events.pagehide();await r.settle();});

test('quote updates preserve row and chart controls, ordering and research/control removal',async()=>{const r=rig();await r.settle();const snapshot=r.node('rows').innerHTML,header=r.node('table-head').innerHTML;r.respond();await r.settle();const cell=r.cells()[2];assert.match(cell.innerHTML,/100.00/);r.setTime(1000);[...r.intervals.values()][0].fn();await r.settle();r.respond('20261009100001');await r.settle();assert.equal(r.cells()[2],cell);assert.equal(r.node('rows').innerHTML,snapshot);assert.equal(r.node('table-head').innerHTML,header);const html=fs.readFileSync(__dirname+'/../quotes.html','utf8');assert.doesNotMatch(html,/auto-refresh|related-research|research-link/);r.events.pagehide();});

test('list rows have no period buttons and retain whole-row selection',async()=>{const r=rig(true);await r.settle();r.respond();await r.settle();assert.doesNotMatch(r.node('rows').innerHTML,/data-row-period|quotes-row-periods/);r.node('rows').onclick({target:{closest:s=>s==='tr[data-company]'?{dataset:{company:'600754.SH'}}:null}});assert.equal(r.node('quote-title').textContent,'第二公司');r.events.pagehide();});

test('heatmap color follows live percentage without replacing tiles',async()=>{const r=rig();await r.settle();const label={textContent:''},value={textContent:''},tile={dataset:{code:'600519.SH'},style:{},querySelector:s=>s==='span'?value:label};r.node('heatmap').querySelectorAll=()=>[tile];r.respond();await r.settle();assert.equal(value.textContent,'+1.00%');assert.match(tile.style.background,/354 58% 86%/);assert.match(tile.title,/2026-10-09 10:00:00/);r.setTime(1000);[...r.intervals.values()][0].fn();await r.settle();r.respond('20261009100001','-4');await r.settle();assert.equal(value.textContent,'-4.00%');assert.match(tile.style.background,/164 47% 48%/);assert.equal(tile.style.color,'#fff');r.events.pagehide();});
test('live quote percentages reorder existing rows without rebuilding the table',async()=>{const r=rig(true);await r.settle();r.respond('20261009100000','1','0');await r.settle();const original=r.node('rows').querySelectorAll('tr[data-company]');assert.equal(original[0].dataset.company,'600519.SH');r.setTime(1000);[...r.intervals.values()][0].fn();await r.settle();r.respond('20261009100001','1','5');await r.settle();const ranked=r.node('rows').querySelectorAll('tr[data-company]');assert.equal(ranked[0].dataset.company,'600754.SH');assert.equal(ranked[0],original[1]);r.events.pagehide();});

test('heatmap is the default while an explicit list link remains usable',async()=>{for(const [query,view] of [['','heat'],['?view=list','list'],['?view=heat','heat']]){const r=rig(false,query);await r.settle();assert.equal(r.node('workspace').dataset.view,view);assert.equal(r.node('list-view').hidden,view==='heat');assert.equal(r.node('heat-view').hidden,view==='list');r.events.pagehide();await r.settle();}});
