const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/quotes.js','utf8');
function rig(){
  const nodes=new Map(),events={},scripts=[],intervals=new Map(),timeouts=new Map();let id=0,time=0;
  function node(name){if(!nodes.has(name))nodes.set(name,{hidden:name==='content',checked:true,value:'',dataset:{},style:{},innerHTML:'',textContent:'',scrollTop:0,clientWidth:900,querySelectorAll:()=>[],querySelector:()=>null,setAttribute(){},focus(){},scrollIntoView(){}});return nodes.get(name);}
  const document={hidden:false,body:{dataset:{siteSection:'quotes'}},activeElement:null,getElementById:node,addEventListener:(k,fn)=>events[k]=fn,createElement:()=>{const s={remove(){s.removed=true;}};return s;},head:{appendChild:s=>scripts.push(s)}};
  class Clock extends Date{constructor(...args){super(...(args.length?args:[1791511200000+time]));}static now(){return time;}}
  const ctx={document,console,AbortController,DOMException,URLSearchParams,Date:Clock,Intl,location:{search:'',pathname:'/quotes.html'},history:{replaceState(){}},localStorage:{getItem:()=>null,setItem(){}},matchMedia:()=>({matches:false}),addEventListener:(k,fn)=>events[k]=fn,setTimeout:(fn,ms)=>{timeouts.set(++id,{fn,ms});return id;},clearTimeout:id=>timeouts.delete(id),setInterval:(fn,ms)=>{intervals.set(++id,{fn,ms});return id;},clearInterval:id=>intervals.delete(id),QuotesModel:require('./quotes-model.js'),SinolinkKline:require('./market-kline.js'),SiteData:{esc:String,json:async url=>url==='data-manifest.json'?{datasets:[{id:'valuation',file:'v.csv'}]}:{dbs:[]},table:async()=>[{'证券代码':'600519.SH','公司名称':'测试公司','子行业':'餐饮'}]}};
  // Build the poller in the same fake clock/timer realm as the browser.
  ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/quotes-poller.js','utf8'),ctx);vm.runInContext(source,ctx);
  const settle=async()=>{for(let i=0;i<15;i++)await Promise.resolve();};
  function respond(stamp='20261009100000'){const s=scripts.find(x=>!x.removed&&x.src.includes('qt.gtimg.cn'));assert.ok(s);for(const q of ['sh600519','sh000001','sz399006','hkHSI']){const f=Array(50).fill('');f[1]='测试';f[3]='100';f[4]='99';f[30]=stamp;f[31]='1';f[32]='1';f[33]='101';f[34]='98';ctx['v_'+q]=f.join('~');}s.onload();}
  return {ctx,node,events,scripts,intervals,timeouts,settle,respond,setTime:t=>time=t};
}
test('real page wiring uses one-second checks, source seconds, lifecycle cancellation and recovery',async()=>{const r=rig();await r.settle();r.respond();await r.settle();assert.equal([...r.intervals.values()][0].ms,1000);assert.match(r.node('rows').innerHTML,/10:00:00/);const tick=[...r.intervals.values()][0].fn;r.setTime(1000);await tick();assert.match(r.node('status').textContent,/14秒后/);await r.node('refresh').onclick();assert.equal(r.scripts.filter(s=>s.src.includes('qt.gtimg.cn')).length,1);r.setTime(15000);tick();await r.settle();const live=r.scripts.filter(s=>!s.removed);r.ctx.document.hidden=true;r.events.visibilitychange();await r.settle();assert.equal(r.intervals.size,0);assert.ok(live.every(s=>s.removed));r.setTime(30000);r.ctx.document.hidden=false;r.events.visibilitychange();await r.settle();r.respond();await r.settle();assert.match(r.node('rows').innerHTML,/来源时间未更新/);r.events.pagehide();await r.settle();assert.equal(r.intervals.size,0);r.setTime(60000);r.events.pageshow();await r.settle();assert.equal(r.intervals.size,1);r.respond('20261009100001');await r.settle();assert.match(r.node('rows').innerHTML,/10:00:01/);r.events.pagehide();});
test('hidden initial load and disabled auto prevent timers, while manual refresh remains throttled',async()=>{const r=rig();r.ctx.document.hidden=true;await r.settle();assert.equal(r.scripts.length,0);assert.equal(r.intervals.size,0);r.node('auto-refresh').checked=false;r.ctx.document.hidden=false;r.events.visibilitychange();await r.settle();assert.equal(r.intervals.size,0);const read=r.node('refresh').onclick();await r.settle();r.respond();await read;await r.settle();assert.equal(r.intervals.size,0);await r.node('refresh').onclick();assert.equal(r.scripts.filter(s=>s.src.includes('qt.gtimg.cn')).length,1);r.events.pagehide();});
