const {test}=require('node:test');
const assert=require('node:assert/strict');
const P=require('./quotes-poller.js'),M=require('./quotes-model.js');
function harness(request){let time=0,active=true,ticks=0,scheduled=new Map(),id=0;const poller=P.create({request,isActive:()=>active,now:()=>time,onTick:()=>ticks++,setTimer:(fn,ms)=>{assert.equal(ms,1000);scheduled.set(++id,fn);return id;},clearTimer:id=>scheduled.delete(id)});return {poller,scheduled,setTime:v=>time=v,setActive:v=>active=v,get ticks(){return ticks;}};}
test('successful requests start every 1000ms; manual clicks cannot exceed the cadence',async()=>{let calls=0;const h=harness(async()=>{calls++;return true;});h.poller.sync();await Promise.resolve();await Promise.resolve();h.setTime(999);await h.poller.check();assert.equal(calls,1);for(let t=1000;t<=5000;t+=1000){h.setTime(t);await h.poller.check();await h.poller.check();assert.equal(calls,t/1000+1);}h.poller.stop();assert.equal(h.scheduled.size,0);});
test('slow requests never overlap even after request interval elapses',async()=>{let calls=0,finish;const h=harness(()=>{calls++;return new Promise(r=>finish=r);});const first=h.poller.check();h.setTime(60000);await h.poller.check();assert.equal(calls,1);finish(true);await first;const second=h.poller.check();assert.equal(calls,2);finish(true);await second;});
test('hidden/inactive modules never request; pause cancels in flight and timers',async()=>{let calls=0,signal,finish;const h=harness(s=>{calls++;signal=s;return new Promise(r=>finish=r);});h.setActive(false);h.poller.sync();assert.equal(calls,0);assert.equal(h.scheduled.size,0);h.setActive(true);h.poller.sync();assert.equal(calls,1);h.setActive(false);h.poller.sync();assert.equal(signal.aborted,true);assert.equal(h.scheduled.size,0);finish(true);await Promise.resolve();await Promise.resolve();h.setActive(true);h.setTime(500);h.poller.resume();assert.equal(calls,1);h.poller.stop();});
test('pagehide stop stays stopped; pageshow resume retains interval',async()=>{let calls=0;const h=harness(async()=>{calls++;return true;});await h.poller.check();h.poller.stop();h.setTime(30000);await h.poller.check();assert.equal(calls,1);h.poller.resume();await Promise.resolve();assert.equal(calls,2);h.poller.stop();});
test('failed and partial reads back off, including manual checks',async()=>{let calls=0;const h=harness(async()=>{calls++;return false;});await h.poller.check();assert.equal(h.poller.state().nextAt,30000);h.setTime(15000);await h.poller.check();assert.equal(calls,1);h.setTime(30000);await h.poller.check();assert.equal(h.poller.state().nextAt,90000);});
test('network rejection backs off and recovery clears failure count',async()=>{let fail=true;const h=harness(async()=>{if(fail)throw Error('network');return true;});await h.poller.check();assert.equal(h.poller.state().failures,1);fail=false;h.setTime(30000);await h.poller.check();assert.equal(h.poller.state().failures,0);});
test('retrieval clock never promotes repeated or older source timestamps',()=>{const a={code:'600519.SH',price:100,asOf:'2026-10-09 10:00:00',retrievedAt:'first',failed:true};const repeated=M.accept(a,{...a,retrievedAt:'later',failed:false});assert.equal(repeated.asOf,a.asOf);assert.match(M.state(repeated),/来源时间未更新/);assert.equal(M.accept(a,{...a,price:90,asOf:'2026-10-09 09:59:00'}).price,100);const newer=M.accept(a,{...a,asOf:'2026-10-09 10:00:01',failed:false});assert.equal(newer.unchanged,false);assert.equal(newer.asOf,'2026-10-09 10:00:01');});
