(async function(){
  'use strict';
  const D=SiteData,M=QuotesModel,K=SinolinkKline,$=id=>document.getElementById(id),esc=D.esc,size=10,params=new URLSearchParams(location.search);
  const benchmarks=[{code:'000001.SH',name:'上证指数',index:true},{code:'399006.SZ',name:'创业板指',index:true},{code:'HSI.HI',name:'恒生指数',index:true}];
  let companies=[],quotes={},filtered=[],page=1,view=params.get('view')==='heat'?'heat':'list',pending=false,timer=null,selected=null,period='day',chartRequest=0,lastRead='',failed=false,chartSession='';
  const tone=v=>Number.isFinite(v)?v>0?'quotes-up':v<0?'quotes-down':'quotes-flat':'quotes-flat';
  const fmt=(v,n=2)=>v==null?'—':Number(v).toLocaleString('zh-CN',{minimumFractionDigits:n,maximumFractionDigits:n}),signed=(v,suffix='',n=2)=>v==null?'—':(v>0?'+':'')+fmt(v,n)+suffix;
  const meta=c=>M.markets[M.market(c.code)],price=(q,c)=>fmt(q?.price,!c.index&&M.market(c.code)==='HK'?3:2);
  function filters(){return {q:$('search').value,market:$('market').value,sector:$('sector').value,sort:$('sort').value};}
  function saveUrl(){const f=filters(),p=new URLSearchParams();for(const key of ['q','market','sector'])if(f[key])p.set(key,f[key]);if(f.sort!=='change-desc')p.set('sort',f.sort);if(view!=='list')p.set('view',view);if(selected)p.set('symbol',selected.code);history.replaceState(null,'',location.pathname+(p.size?'?'+p:''));}
  function timeText(q){return q?esc(q.asOf.slice(5,16))+'<small>'+esc(M.state(q))+'</small>':'—<small>暂无报价</small>';}
  function renderBenchmarks(){ $('benchmarks').innerHTML=benchmarks.map(c=>{const q=quotes[c.code];return '<button class="quotes-benchmark" type="button" data-code="'+c.code+'"><span>'+c.name+'</span><strong>'+price(q,c)+'</strong><span class="quotes-percent '+tone(q?.percent)+'">'+signed(q?.percent,'%')+'</span><small>'+ (q?esc(q.asOf.slice(5,16))+' · '+esc(M.state(q)):(pending?'正在取得报价':'暂无报价'))+'</small></button>';}).join(''); }
  function render(){
    filtered=M.filter(companies,quotes,filters());const b=M.breadth(filtered,quotes),count=Math.max(1,Math.ceil(filtered.length/size));page=Math.min(page,count);
    const breadth=b.valid?' · '+b.up+'涨 / '+b.down+'跌 / '+b.flat+'平'+(b.percentMissing?' · '+b.percentMissing+'只涨跌幅缺失':''):'';
    $('range-summary').textContent=filtered.length+' 家公司 · '+b.valid+' 家已取得报价'+breadth+(b.missing?' · '+b.missing+'家待取得':'');
    const focusCode=document.activeElement?.closest('#rows [data-code]')?.dataset.code;
    $('rows').innerHTML=filtered.slice((page-1)*size,page*size).map(c=>{const q=quotes[c.code],info=meta(c);return '<tr><td><button class="quotes-name" data-code="'+esc(c.code)+'" type="button">'+esc(c.name)+'</button><small class="quotes-symbol">'+esc(c.code)+' · '+info.label+'<br>'+esc(c.sector)+'</small></td><td><span class="quotes-price">'+price(q,c)+'<small>'+info.currency+'</small></span></td><td class="quotes-percent '+tone(q?.percent)+'">'+signed(q?.percent,'%')+'</td><td class="quotes-time">'+timeText(q)+'</td></tr>';}).join('')||'<tr><td colspan="4" class="portal-empty">没有符合条件的公司，请调整筛选。</td></tr>';
    if(focusCode){const button=Array.from($('rows').querySelectorAll('[data-code]')).find(b=>b.dataset.code===focusCode);button?.focus({preventScroll:true});}
    $('page-label').textContent=page+' / '+count+' · '+filtered.length+' 家';$('prev').disabled=page<=1;$('next').disabled=page>=count;
    $('heatmap').innerHTML=filtered.map(c=>{const q=quotes[c.code],pct=q?.percent,alpha=Number.isFinite(pct) ? .07+Math.min(Math.abs(pct),10)*.025:0,bg=Number.isFinite(pct)?(pct>=0?'rgba(190,76,92,':'rgba(40,127,112,')+alpha+')':'#f1f2f6';return '<button class="quotes-heat-tile" style="background:'+bg+'" data-code="'+esc(c.code)+'" type="button"><strong>'+esc(c.name)+'</strong><span class="'+tone(pct)+'">'+signed(pct,'%')+'</span><small>'+meta(c).label+' · '+price(q,c)+' '+meta(c).currency+'<br>'+ (q?esc(q.asOf.slice(5,16))+' · '+esc(M.state(q)):'暂无报价')+'</small></button>';}).join('')||'<p class="portal-empty">没有符合条件的公司。</p>';
    $('list-view').hidden=view!=='list';$('heat-view').hidden=view!=='heat';$('views').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));renderBenchmarks();saveUrl();
    if(selected&&$('quote-dialog').open)renderOverview();
  }
  function quoteRequest(codes){return new Promise((resolve,reject)=>{
    const mapping=codes.map(code=>[code,K.quoteCode(code)]).filter(([,q])=>/^(?:sh\d{6}|sz\d{6}|hk(?:\d{5}|HSI)|us[A-Z][A-Z0-9.-]*)$/.test(q)),tag=document.createElement('script');
    mapping.forEach(([,q])=>{try{delete window['v_'+q];}catch(e){window['v_'+q]=undefined;}});
    let done=false;const cleanup=()=>{clearTimeout(timeout);tag.onload=tag.onerror=null;tag.remove();mapping.forEach(([,q])=>{try{delete window['v_'+q];}catch(e){}});};
    const timeout=setTimeout(()=>{if(done)return;done=true;cleanup();reject(Error('timeout'));},10000);
    tag.charset='gbk';tag.src='https://qt.gtimg.cn/q='+mapping.map(([,q])=>q).join(',')+'&_='+Date.now();
    tag.onload=()=>{if(done)return;done=true;const retrievedAt=new Date().toISOString(),result={};mapping.forEach(([code,q])=>{const parsed=M.parse(window['v_'+q],code,retrievedAt);if(parsed)result[code]=parsed;});cleanup();resolve(result);};
    tag.onerror=()=>{if(done)return;done=true;cleanup();reject(Error('network'));};document.head.appendChild(tag);
  });}
  function connection(){const automatic=$('auto-refresh').checked&&!document.hidden;$('status').dataset.error=String(failed);$('status').textContent=failed?'腾讯行情连接未完成，已取得的上次报价保留显示；可点击“刷新报价”重试。':'腾讯行情 · 最近读取 '+lastRead+'（北京时间） · '+(automatic?'每15秒刷新':'自动刷新已暂停')+' · 证券报价时间见各行';}
  async function refresh(){if(pending||!companies.length)return;pending=true;$('refresh').disabled=true;$('refresh').textContent='读取中…';if(!lastRead)$('status').textContent='正在同步腾讯报价…';renderBenchmarks();const codes=companies.concat(benchmarks).map(c=>c.code);try{const incoming=await quoteRequest(codes);codes.forEach(code=>{if(incoming[code])quotes[code]=incoming[code];else if(quotes[code])quotes[code].failed=true;});failed=Object.keys(incoming).length<codes.length;if(Object.keys(incoming).length)lastRead=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date());}
    catch(e){failed=true;Object.values(quotes).forEach(q=>q.failed=true);}finally{pending=false;$('refresh').disabled=false;$('refresh').textContent='刷新报价';connection();render();if(selected&&$('quote-dialog').open&&period==='minute'&&quotes[selected.code]&&!quotes[selected.code].failed)loadChart();}}
  function automatic(){clearInterval(timer);timer=null;if($('auto-refresh').checked&&!document.hidden&&companies.length)timer=setInterval(refresh,15000);if(lastRead||failed)connection();}
  function renderOverview(){const q=quotes[selected.code],info=meta(selected);$('quote-overview').innerHTML='<div><div class="quotes-large-price">'+price(q,selected)+'<small>'+ (selected.index?'点':info.currency)+'</small></div><p class="quotes-large-change '+tone(q?.percent)+'">'+signed(q?.change)+' / '+signed(q?.percent,'%')+'</p><p class="quotes-quote-note">'+(q?esc(q.asOf)+' · '+info.timeLabel+'<br>'+esc(M.state(q))+' · 腾讯报价可能延迟':'暂无已取得的有效报价')+'</p></div><div class="quotes-ohlc">'+[['前收',q?.previousClose],['开盘',q?.open],['最高',q?.high],['最低',q?.low]].map(([label,value])=>'<div><span>'+label+'</span><strong>'+fmt(value,info.currency==='HKD'?3:2)+'</strong></div>').join('')+'</div>';$('provider-link').href='https://gu.qq.com/'+K.quoteCode(selected.code);$('company-link').hidden=!!selected.index;$('company-link').href='companies.html?company='+encodeURIComponent(selected.code);}
  function jsonp(url){return new Promise((resolve,reject)=>{const name='__quotes_chart_'+Date.now()+'_'+Math.floor(Math.random()*1e6),s=document.createElement('script');let done=false;const cleanup=()=>{clearTimeout(timeout);s.onload=s.onerror=null;s.remove();try{delete window[name];}catch(e){}};const timeout=setTimeout(()=>{if(done)return;done=true;cleanup();reject(Error('走势请求超时，请重试。'));},12000);s.charset='gbk';s.src=url+'&_var='+name+'&r='+Date.now();s.onload=()=>{if(done)return;done=true;const data=window[name];cleanup();if(data?.data)resolve(data);else reject(Error('来源暂未返回该证券的走势。'));};s.onerror=()=>{if(done)return;done=true;cleanup();reject(Error('走势连接失败，请重试。'));};document.head.appendChild(s);});}
  function dateLabel(raw){const s=String(raw);return /^\d{12}$/.test(s)?s.slice(0,4)+'-'+s.slice(4,6)+'-'+s.slice(6,8)+' '+s.slice(8,10)+':'+s.slice(10,12):s;}
  function draw(rows,isMinute,company){
    const q=quotes[company.code],sameDate=q&&q.asOf.slice(0,10)===dateLabel(rows.at(-1)[0]).slice(0,10),baseline=isMinute&&sameDate?q.previousClose:null,values=isMinute?rows.map(r=>Number(r[2])):rows.flatMap(r=>[Number(r[3]),Number(r[4])]);if(baseline)values.push(baseline);
    const low=Math.min(...values),high=Math.max(...values),pad=(high-low||Math.max(1,high*.01))*.12,lo=low-pad,hi=high+pad,w=800,h=210,left=70,top=20,y=v=>top+h-(v-lo)/(hi-lo)*h;
    const x=(r,i)=>isMinute?left+K.sessionAxis(company.code,r).minute/K.sessionAxis(company.code,r).total*w:left+(i+.5)*w/rows.length;
    const grid=[0,1,2,3].map(i=>{const value=hi-(hi-lo)*i/3;return '<line x1="70" y1="'+y(value)+'" x2="870" y2="'+y(value)+'" stroke="#eceef4"/><text x="58" y="'+(y(value)+4)+'" text-anchor="end">'+fmt(value,2)+'</text>';}).join('');
    let marks;if(isMinute){const coords=rows.map((r,i)=>x(r,i)+','+y(Number(r[2]))).join(' ');marks=(baseline?'<line x1="70" x2="870" y1="'+y(baseline)+'" y2="'+y(baseline)+'" stroke="#b2b7c4" stroke-dasharray="4 4"/>':'')+'<polyline points="'+coords+'" fill="none" stroke="#5158aa" stroke-width="2.3" stroke-linejoin="round"/>'+rows.map((r,i)=>'<circle cx="'+x(r,i)+'" cy="'+y(Number(r[2]))+'" r="2" fill="#5158aa"><title>'+esc(dateLabel(r[0])+'：'+fmt(r[2],3))+'</title></circle>').join('');}
    else {const width=Math.max(1,w/rows.length*.62);marks=rows.map((r,i)=>{const open=Number(r[1]),close=Number(r[2]),color=close>=open?'#b94c5c':'#287f70';return '<g><title>'+esc(r[0]+' 开 '+fmt(open,3)+' 收 '+fmt(close,3)+' 高 '+fmt(r[3],3)+' 低 '+fmt(r[4],3))+'</title><line x1="'+x(r,i)+'" x2="'+x(r,i)+'" y1="'+y(Number(r[3]))+'" y2="'+y(Number(r[4]))+'" stroke="'+color+'"/><rect x="'+(x(r,i)-width/2)+'" y="'+Math.min(y(open),y(close))+'" width="'+width+'" height="'+Math.max(1,Math.abs(y(open)-y(close)))+'" fill="'+color+'"/></g>';}).join('');}
    const ticks=[0,Math.floor((rows.length-1)/2),rows.length-1].map((i,n)=>'<text x="'+(n===0?70:n===2?870:470)+'" y="265" text-anchor="'+(n===0?'start':n===2?'end':'middle')+'">'+esc(isMinute?String(rows[i][0]).slice(8,10)+':'+String(rows[i][0]).slice(10,12):rows[i][0])+'</text>').join('');
    return '<svg class="quotes-chart" viewBox="0 0 910 285" role="img" aria-label="'+esc(company.name+' '+(isMinute?'分时走势':company.index?'指数K线':'前复权K线')+'，价格单位'+(company.index?'点':meta(company).currency))+'"><title>'+esc(company.name+'：'+dateLabel(rows[0][0])+' 至 '+dateLabel(rows.at(-1)[0]))+'</title>'+grid+marks+ticks+'</svg>';
  }
  async function loadChart(){if(!selected)return;const request=++chartRequest,company=selected,mode=period,qc=quotes[company.code]?.providerCode||K.quoteCode(company.code),isMinute=mode==='minute';$('periods').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.period===mode)));$('chart-status').textContent='正在读取腾讯走势…';$('chart').innerHTML='';$('chart-detail').textContent='';
    const url=isMinute?'https://proxy.finance.qq.com/ifzqgtimg/appstock/app/minute/query?code='+encodeURIComponent(qc):'https://web.ifzq.gtimg.cn/appstock/app/fqkline/get?param='+encodeURIComponent(qc+','+mode+',,,'+(mode==='day'?150:100)+(company.index?'':',qfq'));
    try{const data=await jsonp(url);if(request!==chartRequest||!$('quote-dialog').open)return;const rows=isMinute?M.intraday(K.normalize(data,'m1'),company.code):M.candles(K.normalize(data,mode)).slice(mode==='day'?-120:-80);if(rows.length<2)throw Error('来源暂未返回足够的有效走势数据。');chartSession=dateLabel(rows.at(-1)[0]).slice(0,10);$('chart').innerHTML=draw(rows,isMinute,company);$('chart-status').textContent=(isMinute?'最近交易日分时（常规时段） · '+chartSession:(company.index?'指数':'前复权')+(mode==='day'?'日K':'周K')+' · '+rows.length+' 条记录')+' · '+ (company.index?'点':meta(company).currency);const latest=rows.at(-1);$('chart-detail').textContent='走势范围：'+dateLabel(rows[0][0])+' — '+dateLabel(latest[0])+'；最新收盘 / 分时价 '+fmt(latest[2],3)+(quotes[company.code]&&quotes[company.code].asOf.slice(0,10)!==chartSession?'。走势与报价日期不同，分别以来源时间为准。':'。');}
    catch(e){if(request!==chartRequest||!$('quote-dialog').open)return;$('chart-status').textContent='';$('chart').innerHTML='<div class="quotes-chart-empty">'+esc(e.message)+'<br>可切换周期或点击“刷新走势”。</div>';}
  }
  function open(code){const c=companies.concat(benchmarks).find(c=>c.code===code);if(!c)return;selected=c;period='day';chartSession='';$('quote-title').textContent=c.name;$('quote-subtitle').textContent=c.code+' · '+meta(c).label+(c.sector?' · '+c.sector:'');renderOverview();if(!$('quote-dialog').open)$('quote-dialog').showModal();saveUrl();loadChart();}
  $('rows').onclick=$('heatmap').onclick=$('benchmarks').onclick=e=>{const button=e.target.closest('[data-code]');if(button)open(button.dataset.code);};
  $('views').onclick=e=>{const button=e.target.closest('[data-view]');if(button){view=button.dataset.view;render();}};
  $('search').oninput=()=>{page=1;render();};for(const id of ['market','sector','sort'])$(id).onchange=()=>{page=1;render();};$('prev').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};$('refresh').onclick=refresh;$('auto-refresh').onchange=automatic;
  $('periods').onclick=e=>{const button=e.target.closest('[data-period]');if(button){period=button.dataset.period;loadChart();}};$('chart-retry').onclick=loadChart;$('close-dialog').onclick=()=>$('quote-dialog').close();$('quote-dialog').addEventListener('close',()=>{chartRequest++;selected=null;saveUrl();});
  document.addEventListener('visibilitychange',()=>{automatic();if(!document.hidden&&$('auto-refresh').checked)refresh();});addEventListener('pagehide',()=>clearInterval(timer));
  try{const manifest=await D.json('data-manifest.json'),dataset=manifest.datasets.find(d=>d.id==='valuation');companies=(await D.table(dataset.file)).map(r=>({code:r['证券代码'],name:r['公司名称'],sector:r['子行业']})).filter(c=>c.code&&c.name);$('sector').innerHTML='<option value="">全部行业</option>'+[...new Set(companies.map(c=>c.sector))].map(s=>'<option>'+esc(s)+'</option>').join('');for(const id of ['search','market','sector','sort']){const val=params.get(id==='search'?'q':id);if(val!=null)$(id).value=val;}if(!$('sort').value)$('sort').value='change-desc';$('content').hidden=false;render();await refresh();automatic();const symbol=params.get('symbol');if(symbol)open(symbol);}
  catch(e){$('status').dataset.error='true';$('status').innerHTML='覆盖公司目录暂时无法读取。<button class="portal-button" type="button" id="retry">重新加载</button>';$('retry').onclick=()=>location.reload();}
})();
