(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.QuotesModel=api;})(typeof window==='object'?window:{},function(){
  'use strict';
  const markets={CN:{label:'A股',currency:'CNY',timeLabel:'北京时间',timeZone:'Asia/Shanghai'},HK:{label:'港股',currency:'HKD',timeLabel:'香港时间',timeZone:'Asia/Hong_Kong'},US:{label:'美股',currency:'USD',timeLabel:'来源市场时间',timeZone:'America/New_York'}};
  function market(code){return /\.HK$|^HSI\.HI$/i.test(code)?'HK':/\.(O|N)$/i.test(code)?'US':'CN';}
  function number(value){if(value==null||String(value).trim()==='')return null;const n=Number(value);return Number.isFinite(n)?n:null;}
  function timestamp(value){let s=String(value||'').trim();if(/^\d{14}$/.test(s))s=s.replace(/^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})$/,'$1-$2-$3 $4:$5:$6');else s=s.replace(/\//g,'-');const match=s.match(/^(\d{4}-\d{2}-\d{2})(?:[ T](\d{2}:\d{2}(?::\d{2})?))?$/);if(!match)return '';const [y,m,d]=match[1].split('-').map(Number),day=new Date(Date.UTC(y,m-1,d));if(day.getUTCFullYear()!==y||day.getUTCMonth()!==m-1||day.getUTCDate()!==d)return '';if(match[2]){const [h,min,sec=0]=match[2].split(':').map(Number);if(h>23||min>59||sec>59)return '';}return match[1]+(match[2]?' '+match[2]:'');}
  function parse(raw,code,retrievedAt){if(typeof raw!=='string')return null;const f=raw.split('~'),price=number(f[3]),asOf=timestamp(f[30]);if(f.length<35||price==null||price<=0||!asOf)return null;const positive=i=>{const n=number(f[i]);return n!=null&&n>0?n:null;};const providerCode=market(code)==='US'&&/^[A-Z][A-Z0-9.-]*$/.test(f[2])&&f[2].split('.')[0]===code.split('.')[0]?'us'+f[2]:null;return {code,name:f[1],market:market(code),providerCode,price,previousClose:positive(4),open:positive(5),change:number(f[31]),percent:number(f[32]),high:positive(33),low:positive(34),asOf,retrievedAt,failed:false};}
  function dayFor(code,now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:markets[market(code)].timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(now);}
  function state(quote,now=new Date()){if(!quote)return '暂无报价';if(quote.failed)return '读取失败 · 上次报价';return quote.asOf.slice(0,10)===dayFor(quote.code,now)?'当日报价':'上次报价';}
  function filter(companies,quotes,f){const q=(f.q||'').trim().toLowerCase();const rows=companies.filter(c=>(!f.market||market(c.code)===f.market)&&(!f.sector||c.sector===f.sector)&&(!q||[c.name,c.code].join(' ').toLowerCase().includes(q)));return rows.sort((a,b)=>{if(f.sort==='name')return a.name.localeCompare(b.name,'zh');const x=quotes[a.code]?.percent,y=quotes[b.code]?.percent;if(!Number.isFinite(x))return Number.isFinite(y)?1:a.name.localeCompare(b.name,'zh');if(!Number.isFinite(y))return -1;return (f.sort==='change-asc'?x-y:y-x)||a.name.localeCompare(b.name,'zh');});}
  function breadth(companies,quotes){const valid=companies.map(c=>quotes[c.code]).filter(Boolean);return {total:companies.length,valid:valid.length,up:valid.filter(q=>q.percent>0).length,down:valid.filter(q=>q.percent<0).length,flat:valid.filter(q=>q.percent===0).length,missing:companies.length-valid.length,percentMissing:valid.filter(q=>q.percent==null).length};}
  function candles(rows){return rows.filter(r=>r&&/^\d{4}-\d{2}-\d{2}$/.test(r[0])&&r.slice(1,5).every(v=>number(v)!=null&&number(v)>0)&&Number(r[3])>=Math.max(Number(r[1]),Number(r[2]),Number(r[4]))&&Number(r[4])<=Math.min(Number(r[1]),Number(r[2]),Number(r[3]))).sort((a,b)=>a[0].localeCompare(b[0]));}
  function adjustment(data,code,period,isIndex){if(isIndex)return '指数';const series=data?.data?.[code];return Array.isArray(series?.['qfq'+period])&&series['qfq'+period].length?'前复权':'源数据';}
  function intraday(rows,code){const windows=market(code)==='US'?[[570,960]]:market(code)==='HK'?[[570,720],[780,960]]:[[570,690],[780,900]];const valid=rows.filter(r=>{if(!r||!/^\d{12}$/.test(r[0])||!(number(r[2])>0))return false;const time=Number(r[0].slice(8,10))*60+Number(r[0].slice(10,12));return windows.some(([start,end])=>time>=start&&time<=end);}).sort((a,b)=>a[0].localeCompare(b[0]));const session=valid.at(-1)?.[0].slice(0,8);return valid.filter(r=>r[0].startsWith(session));}
  return {markets,market,number,timestamp,parse,dayFor,state,filter,breadth,candles,adjustment,intraday};
});
