(async function(){
  'use strict';const D=SiteData,$=id=>document.getElementById(id);let entries=[],filtered=[],kind='views',page=1,manifest,sync={};const size=12,archive=new Set(),batches=new Map();let articleRequest=0;
  function entry(r,k){const published=r['时间']||r['日期']||'';return {kind:k,title:r['标题']||'',published,date:published.slice(0,10),content:r['内容']||r['摘要']||'',author:r['作者']||r['类型']||'纪要文库',sector:r['覆盖板块']||r['命中关键词']||'',company:r['相关标的']||'',url:D.link(r['原文链接']||r['下载链接']),file:r['文件名']||'',batch:r['更新批次']||'',truncated:!!r['正文已截断'],state:r['内容状态']||''};}
  function unique(records){const seen=new Set();return records.filter(r=>{const key=(r.url||r.published+'|'+r.title)+'|'+r.file;if(seen.has(key))return false;seen.add(key);return true;});}
  async function batchRows(path){if(!batches.has(path))batches.set(path,D.table(path).catch(e=>{batches.delete(path);throw e;}));return batches.get(path);}
  function render(){const kw=$('search').value.trim().toLowerCase(),from=$('from').value,to=$('to').value;filtered=entries.filter(r=>r.kind===kind&&(!kw||(r.title+' '+r.content+' '+r.company+' '+r.sector).toLowerCase().includes(kw))&&(!from||r.date>=from)&&(!to||r.date<=to)).sort((a,b)=>$('sort').value==='asc'?a.published.localeCompare(b.published):b.published.localeCompare(a.published));const pages=Math.max(1,Math.ceil(filtered.length/size));page=Math.min(page,pages);$('results').innerHTML=filtered.slice((page-1)*size,page*size).map((r,i)=>'<article class="portal-research-item"><div class="portal-research-meta"><time>'+D.esc(r.published.replace('T',' ')||'日期待补充')+'</time><span>'+D.esc(r.author)+'</span><span class="portal-tag">'+D.esc(r.kind==='minutes'?(r.state||'纪要'):'观点')+'</span></div><button class="portal-research-title" data-entry="'+((page-1)*size+i)+'">'+D.esc(r.title||'未命名内容')+' ↗</button><p class="portal-research-summary">'+D.esc(r.content)+'</p></article>').join('')||'<div class="portal-empty">当前筛选没有内容</div>';$('count').textContent=filtered.length+' 条结果';$('page-label').textContent=page+' / '+pages;$('prev').disabled=page<=1;$('next').disabled=page>=pages;$('archive').hidden=archive.has(kind)||kind==='minutes';$('source-note').textContent=archive.has(kind)||kind==='minutes'?'已读取该分类的全部已收录记录':'展示近期索引；更早内容可按需读取历史库';const latest=entries.filter(r=>r.kind===kind).map(r=>r.published).sort().at(-1)||'';$('freshness').textContent='内容截至 '+latest.replace('T',' ')+' · 最近同步 '+(sync.syncedAt||'尚无同步记录').slice(0,19).replace('T',' ');}
  async function open(index){const r=filtered[index];if(!r)return;const request=++articleRequest;$('article-title').textContent=r.title;$('article-meta').textContent=r.published.replace('T',' ')+' · '+r.author+(r.company?' · '+r.company:'');$('article-body').textContent=r.content||'暂无正文';$('article-note').textContent=r.state||(r.truncated?'当前为近期索引摘要，完整内容可查看原文。':'');$('article-source').hidden=!r.url;$('article-source').href=r.url||'#';$('article-source').textContent=r.kind==='minutes'?(r.state?'查看纪要附件 ↗':'下载纪要 ↗'):'查看原文 ↗';$('article-dialog').showModal();if(r.batch&&Object.values(sync.files||{}).flat().includes(r.batch)){ $('article-note').textContent='正在读取完整正文…';try{const records=await batchRows(r.batch);const full=records.map(row=>entry(row,r.kind)).find(row=>row.url===r.url&&row.file===r.file);if(request!==articleRequest)return;if(!full)throw Error('record missing');$('article-body').textContent=full.content;$('article-note').textContent=full.state||'完整正文 · 来源：'+(sync.sourceName||'知识星球');}catch(e){if(request===articleRequest)$('article-note').textContent='完整正文暂时无法读取，请打开原文。';}}}
  function select(k){kind=k;page=1;$('research-tabs').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kind===kind)));render();}
  $('research-tabs').onclick=e=>{const b=e.target.closest('[data-kind]');if(b)select(b.dataset.kind);};$('search').value=new URLSearchParams(location.search).get('q')||'';$('search').oninput=()=>{page=1;render();};[$('from'),$('to'),$('sort')].forEach(el=>el.onchange=()=>{page=1;render();});$('clear').onclick=()=>{$('from').value=$('to').value='';$('search').value='';page=1;render();};$('results').onclick=e=>{const b=e.target.closest('[data-entry]');if(b)open(Number(b.dataset.entry));};$('close-article').onclick=()=>{articleRequest++;$('article-dialog').close();};$('article-dialog').addEventListener('cancel',()=>articleRequest++);$('prev').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};
  $('archive').onclick=async()=>{const requested=kind,button=$('archive');button.disabled=true;button.textContent='正在读取历史库…';try{const source=manifest.datasets.find(d=>d.id===requested);const [all,...updates]=await Promise.all([D.table(source.file),...(sync.files?.[requested]||[]).map(batchRows)]);const combined=unique(updates.flat().concat(all.filter(r=>!(sync.assignedTopics?.[requested === 'views' ? 'all_views' : 'views']||[]).includes((D.link(r['原文链接']).match(/\/topic\/(\d+)/)||[])[1]))).map(r=>entry(r,requested)));entries=entries.filter(r=>r.kind!==requested).concat(combined);archive.add(requested);render();}catch(e){$('status').textContent='历史库未能读取，可重试；近期内容仍可浏览。';}finally{button.disabled=false;button.textContent='读取更早内容（历史库较大）';}};
  try{manifest=await D.json('data-manifest.json');const [recent,minutes,updates]=await Promise.all([D.json('data/research/recent.json'),D.table(manifest.datasets.find(d=>d.id==='minutes').file),D.json('data/research/updates/manifest.json')]);sync=updates;const minuteUpdates=(await Promise.all((sync.files?.minutes||[]).map(batchRows))).flat();entries=recent.dbs.filter(db=>db.id!=='minutes').flatMap(db=>db.rows.map(r=>entry(r,db.id))).concat(unique(minuteUpdates.concat(minutes).map(r=>entry(r,'minutes'))));$('status').textContent='';$('content').hidden=false;select('views');}catch(e){$('status').innerHTML='研究文库暂时无法读取。<button class="portal-button" onclick="location.reload()">重试</button>';}
})();
