const assert=require('node:assert/strict'),L=require('./research-library-model.js');
const file={name:'免税20260930.mp3',format:'audio',date:'2026-10-01',sectors:['dutyfree'],processing:{status:'awaiting_file',textAvailable:false}};
assert(L.matches(file,{format:'audio',sector:'dutyfree',from:'2026-10-01',to:'2026-10-01'}));
assert(!L.matches(file,{sector:'travel'}));assert(!L.matches(file,{state:'reviewed'}));
assert(L.matches({...file,processing:{status:'transcript_draft',searchText:'购物人次的变化'}},{q:'人次',state:'transcript_draft'}));
assert(!L.briefMatches({status:'draft',sector:'dutyfree',date:'2026-10-01'},{sector:'dutyfree'}));
assert(L.briefMatches({status:'reviewed',sector:'dutyfree',date:'2026-10-01',watch:['购物人次']},{q:'人次'}));
assert.equal(L.duration(3719),'61分59秒');assert.equal(L.bytes(1048576),'1.0 MB');
assert(L.safeLocalPath('data/research/processed/zsxq-file-123.json'));
for(const path of ['../private.json','https://example.com/a.json','data/research/processed/../secret.json','data/research/processed/a.json?token=x'])assert(!L.safeLocalPath(path));
console.log('Consumption catalog filters, transcript search, draft visibility and safe content paths passed.');
const stored={...file,sha256:'a'.repeat(64),storage:{provider:'onedrive',status:'uploaded',verifiedSha256:'a'.repeat(64),audience:'private',openUrl:'https://1drv.ms/b/example'}};
assert(L.hasStoredOriginal(stored));assert.equal(L.storageLink(stored),'');
const shared={...stored,storage:{...stored.storage,audience:'clients',permissionsReviewed:true}};
assert.equal(L.storageLink(shared),'https://1drv.ms/b/example');
for(const openUrl of ['javascript:alert(1)','https://1drv.ms.evil.example/file','https://graph.microsoft.com/file?token=secret','https://onedrive.live.com/file?download=1','https://name:secret@1drv.ms/file'])assert.equal(L.storageLink({...shared,storage:{...shared.storage,openUrl}}),'');
assert(!L.hasStoredOriginal({...stored,sha256:'b'.repeat(64)}));
assert.equal(L.storageLink({...shared,storage:{...shared.storage,permissionsReviewed:false}}),'');
console.log('Private OneDrive originals, source checksum binding and approved share links passed.');
