const assert=require('node:assert/strict'),L=require('./research-library-model.js');
const file={name:'免税20260930.mp3',format:'audio',date:'2026-10-01',sectors:['dutyfree'],processing:{status:'awaiting_file',textAvailable:false}};
assert(L.matches(file,{format:'audio',sector:'dutyfree',from:'2026-10-01',to:'2026-10-01'}));
assert(!L.matches(file,{sector:'travel'}));assert(!L.matches(file,{state:'reviewed'}));
assert(L.matches({...file,processing:{status:'transcript_draft',searchText:'购物人次的变化'}},{q:'人次',state:'transcript_draft'}));
assert(!L.briefMatches({status:'draft',sector:'dutyfree',date:'2026-10-01'},{sector:'dutyfree'}));
assert(L.briefMatches({status:'reviewed',sector:'dutyfree',date:'2026-10-01',watch:['购物人次']},{q:'人次'}));
assert.equal(L.duration(3719),'61分59秒');assert.equal(L.bytes(1048576),'1.0 MB');
assert.equal(L.bytes(20480),'20 KB');
assert(L.safeLocalPath('data/research/processed/zsxq-file-123.json'));
for(const path of ['../private.json','https://example.com/a.json','data/research/processed/../secret.json','data/research/processed/a.json?token=x'])assert(!L.safeLocalPath(path));
console.log('Consumption catalog filters, transcript search, draft visibility and safe content paths passed.');
const stored={...file,sha256:'a'.repeat(64),storage:{provider:'onedrive',status:'uploaded',verifiedSha256:'a'.repeat(64),audience:'private',openUrl:'https://1drv.ms/b/example'}};
assert(L.hasStoredOriginal(stored));assert.equal(L.storageLink(stored),'');
const shared={...stored,storage:{...stored.storage,audience:'clients',permissionsReviewed:true}};
assert.equal(L.storageLink(shared),'https://1drv.ms/b/example');
for(const openUrl of ['javascript:alert(1)','https://1drv.ms.evil.example/file','https://graph.microsoft.com/file?token=secret','https://onedrive.live.com/file?download=1','https://name:secret@1drv.ms/file'])assert.equal(L.storageLink({...shared,storage:{...shared.storage,openUrl}}),'');
assert(!L.hasStoredOriginal({...stored,sha256:'b'.repeat(64)}));
assert.equal(L.storageLink({...shared,storage:{...shared.storage,permissionsReviewed:false}}),'');
console.log('Private OneDrive originals, source checksum binding and approved share links passed.');
assert(L.matches(stored,{scope:'archived'}));assert(!L.matches(file,{scope:'archived'}));
const uncertain={...stored,date:'',dateStatus:'needs_review',company:'行动教育',processing:{status:'needs_review',summary:'收款与收入分开'}};
assert(L.matches(uncertain,{q:'行动教育',scope:'archived'}));
assert(!L.matches(uncertain,{to:'2026-10-08'}));assert(!L.matches(uncertain,{from:'2026-01-01'}));
assert.equal(L.entry(uncertain).published,'');
console.log('Archived-first scope, company search and uncertain date filters passed.');
const legacy={kind:'minutes',title:'旧纪要标题',file:'会议.docx',url:'https://example.com/old.docx'};
const imported=L.entry({...stored,id:'onedrive-docx-test',name:'会议.docx',sourceType:'onedrive_document',sourceTopics:[],published:'2026-09-18',sourceUrl:''});
const merged=L.mergeEntries([legacy,{...legacy,file:'另一份.mp3',state:'会议音频，未转写'}],[imported],()=> '');
assert.equal(merged.length,2);assert(merged.includes(imported));assert.deepEqual(imported.legacyTitles,['旧纪要标题']);
assert.equal(imported.url,'');
const mixed={...legacy,file:'会议.docx；未入库.docx'};
const partial=L.mergeEntries([mixed],[imported],()=> '');
assert.equal(partial.length,2);assert.equal(partial[0].file,'未入库.docx');assert(!partial.includes(mixed));
console.log('Legacy meeting duplicates merge without publishing owner links or hiding unrelated attachments.');
assert.equal(L.storageLink({...shared,storage:{...shared.storage,downloadAllowed:false}}),'');
assert.equal(L.storageLink({...shared,storage:{...shared.storage,expiresAt:'2000-01-01T00:00:00Z'}}),'');
assert.equal(L.storageLink({...shared,storage:{...shared.storage,expiresAt:'invalid-date'}}),'');
console.log('Blocked and expired customer downloads stay hidden.');
const metadataOnly={...file,sha256:'',storage:{provider:'onedrive',status:'uploaded',metadataVerified:true,verificationMethod:'provider_metadata_version',cloudVersion:'c'.repeat(64),audience:'public',permissionsReviewed:true,downloadAllowed:true,openUrl:'https://1drv.ms/b/checked'}};
assert(L.hasStoredOriginal(metadataOnly));assert.equal(L.storageLink(metadataOnly),'https://1drv.ms/b/checked');
assert(!L.hasStoredOriginal({...metadataOnly,storage:{...metadataOnly.storage,metadataVerified:false}}));
assert(!L.hasStoredOriginal({...metadataOnly,storage:{...metadataOnly.storage,cloudVersion:''}}));
assert(!L.hasStoredOriginal({...metadataOnly,sha256:'d'.repeat(64)}));
console.log('Metadata-only originals retain permission checks and do not pretend to verify file bytes.');
assert.deepEqual(L.preview({preview:'原文开头'}),{text:'原文开头',truncated:false});
assert.equal(Array.from(L.preview({preview:'😀'.repeat(510)}).text).length,500);
assert(L.preview({preview:'原文',previewTruncated:true}).truncated);
assert.equal(L.preview({type:'meeting_summary',summary:'生成的摘要'}).text,'');
assert.equal(L.preview({type:'pdf',pages:[{text:'第一段'},{text:'第二段'}]}).text,'第一段\n\n第二段');
assert.equal(L.preview({type:'transcript',segments:[{text:'实际转写'}]}).text,'实际转写');
console.log('Minute previews use source text, stop at 500 characters and never substitute a generated summary.');

