const assert=require('node:assert/strict'),M=require('./research-model.js');
const row={kind:'views',title:'酒店经营更新',company:'首旅酒店',sector:'酒店',content:'【酒店经营更新】\n\nRevPAR同比增长5%。\n联系人：13800000000',date:'2026-10-01',url:'https://wx.zsxq.com/group/1/topic/12345'};
assert.equal(M.lowerDate('2026-10-07',7),'2026-10-01');
assert.equal(M.lowerDate('2026-03-02',7),'2026-02-24');
assert(M.matches(row,{kind:'views',q:'revpar',sector:'travel',from:'2026-10-01',to:'2026-10-07'}));
assert(!M.matches(row,{kind:'views',from:'2026-10-02'}));
assert(!M.matches({...row,content:'提到黄金'}, {kind:'views',sector:'gold'}),'body mentions must not change sector filter');
assert(!M.sectorIds({title:'国庆黄金周出行前瞻'}).includes('gold'));
assert(!M.sectorIds({title:'Nyota updates'}).includes('travel'));
assert.equal(M.preview(row),'RevPAR同比增长5%。');
assert.equal(M.format({kind:'minutes',file:'报告.pdf',state:'附件索引，正文未提取'}),'document');
assert.equal(M.format({kind:'minutes',file:'交流.mp3；补充.mp3',state:'会议音频，未转写'}),'audio');
assert.equal(M.format({kind:'minutes',file:'',state:''}),'text');
assert(!M.matches({...row,kind:'minutes',file:'会议.mp3'},{kind:'minutes',format:'text'}));
const minute={...row,kind:'minutes',file:'交流.mp3；补充.mp3'};
const url=new URL(M.href(minute),'https://example.com/');
assert.equal(url.searchParams.get('topic'),'12345');
assert.equal(url.searchParams.get('kind'),'minutes');
assert.equal(url.searchParams.get('file'),minute.file);
assert.equal(new URL(M.href({title:'旧纪要',kind:'minutes'}),'https://example.com').searchParams.get('q'),'旧纪要');
console.log('Research filters, date boundaries, attachment types and deep links passed.');
