(async function(){
  'use strict';const D=SiteData,$=id=>document.getElementById(id);let entries=[],filtered=[],kind='views',page=1,manifest;const size=12;const archive=new Set();
  function entry(r,k){return {kind:k,title:r['标题']||'',date:(r['时间']||r['日期']||'').slice(0,10),content:r['内容']||r['摘要']||'',author:r['作者']||r['类型']||'纪要文库',sector:r['覆盖板块']||r['命中关键词']||'',company:r['相关标的']||'',url:D.link(r['原文链接']||r['下载链接']),file:r['文件名']||''};}
  function render(){const kw=$('search').value.trim().toLowerCase(),from=$('from').value,to=$('to').value;filtered=entries.filter(r=>r.kind===kind&&(!kw||(r.title+' '+r.content+' '+r.company+' '+r.sector).toLowerCase().includes(kw))&&(!from||r.date>=from)&&(!to||r.date<=to)).sort((a,b)=>$('sort').value==='asc'?a.date.localeCompare(b.date):b.date.localeCompare(a.date));const pages=Math.max(1,Math.ceil(filtered.length/size));page=Math.min(page,pages);$('results').innerHTML=filtered.slice((page-1)*size,page*size).map((r,i)=>'<article class="portal-research-item"><div class="portal-research-meta"><time>'+D.esc(r.date||'日期待补充')+'</time><span>'+D.esc(r.author)+'</span><span class="portal-tag">'+(r.kind==='minutes'?'纪要':'观点')+'</span></div><button class="portal-research-title" data-entry="'+((page-1)*size+i)+'">'+D.esc(r.title||'未命名内容')+' ↗</button><p class="portal-research-summary">'+D.esc(r.content)+'</p></article>').join('')||'<div class="portal-empty">当前筛选没有内容</div>';$('count').textContent=filtered.length+' 条结果';$('page-label').textContent=page+' / '+pages;$('prev').disabled=page<=1;$('next').disabled=page>=pages;$('archive').hidden=archive.has(kind)||kind==='minutes';$('source-note').textContent=archive.has(kind)||kind==='minutes'?'已读取该分类的全部已收录记录':'默认展示近期索引；更早内容可按需读取历史库';}
  function open(index){const r=filtered[index];if(!r)return;$('article-title').textContent=r.title;$('article-meta').textContent=r.date+' · '+r.author+(r.company?' · '+r.company:'');$('article-body').textContent=r.content||'暂无正文';$('article-source').hidden=!r.url;$('article-source').href=r.url||'#';$('article-source').textContent=r.kind==='minutes'?'下载纪要 ↗':'查看原文 ↗';$('article-dialog').showModal();}
  function select(k){kind=k;page=1;$('research-tabs').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.kind===kind)));render();}
  $('research-tabs').onclick=e=>{const b=e.target.closest('[data-kind]');if(b)select(b.dataset.kind);};$('search').value=new URLSearchParams(location.search).get('q')||'';$('search').oninput=()=>{page=1;render();};[$('from'),$('to'),$('sort')].forEach(el=>el.onchange=()=>{page=1;render();});$('clear').onclick=()=>{$('from').value=$('to').value='';$('search').value='';page=1;render();};$('results').onclick=e=>{const b=e.target.closest('[data-entry]');if(b)open(Number(b.dataset.entry));};$('close-article').onclick=()=>$('article-dialog').close();$('prev').onclick=()=>{page--;render();};$('next').onclick=()=>{page++;render();};
  $('archive').onclick=async()=>{const requested=kind;const button=$('archive');button.disabled=true;button.textContent='正在读取历史库…';try{const source=manifest.datasets.find(d=>d.id===requested);const all=await D.table(source.file);entries=entries.filter(r=>r.kind!==requested).concat(all.map(r=>entry(r,requested)));archive.add(requested);render();}catch(e){$('status').textContent='历史库未能读取，可重试；近期内容仍可浏览。';}finally{button.disabled=false;button.textContent='读取更早内容（历史库较大）';}};
  try{manifest=await D.json('data-manifest.json');const [recent,minutes]=await Promise.all([D.json('data/research/recent.json'),D.table(manifest.datasets.find(d=>d.id==='minutes').file)]);entries=recent.dbs.filter(db=>db.id!=='minutes').flatMap(db=>db.rows.map(r=>entry(r,db.id))).concat(minutes.map(r=>entry(r,'minutes')));$('status').textContent='';$('content').hidden=false;select('views');}catch(e){$('status').innerHTML='研究文库暂时无法读取。<button class="portal-button" onclick="location.reload()">重试</button>';}
})();
