(async function(){
  'use strict';
  const D=SiteData,M=SectorModel,$=id=>document.getElementById(id),sid=document.body.dataset.sector,params=new URLSearchParams(location.search);
  const quality={official:'官方原始',primary:'原始披露',official_reprint:'官方转载',provider:'Choice转引',legacy:'历史整理',derived:'计算值'};
  let data,sources,metric,page=1,companyPage=1;const size=20;
  const esc=D.esc,fmt=D.fmt;
  function sourceLink(id){const s=sources[id]||{},url=D.link(s.url)||(/^data\//.test(s.file||'')?s.file:'');return url?'<a href="'+esc(url)+'" target="_blank" rel="noopener">'+esc(s.name||s.title||'来源')+' ↗</a>':'暂无来源链接';}
  function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function active(){return data.metrics.find(m=>m.id===$('metric').value);}
  function chosenPoints(){return M.points(active(),{basis:$('basis').value,from:$('from').value,to:$('to').value});}
  function chart(rows,m){if(rows.some(p=>Number.isFinite(p.change))&&m.unit!=='%')return SiteCharts.paired(rows.map(p=>({period:p.periodLabel,breakBefore:M.groups(rows,m.frequency).some(part=>part[0]===p),x:Date.parse(p.endDate),value:p.value,change:p.change})),{mode:$('sector-chart-mode')?.value||'combo',unit:m.unit,precision:m.precision,name:m.label,gap:m.frequency.includes('月')?65*86400000:m.frequency.includes('季')?120*86400000:Infinity}).html;if(!rows.length)return '<p class="portal-empty">当前筛选暂无数据</p>';const values=rows.map(p=>p.value),low=Math.min(...values),high=Math.max(...values),spread=high-low||Math.max(1,Math.abs(high)*.05),lo=low-spread*.12,hi=high+spread*.12,start=Date.parse(rows[0].endDate),end=Date.parse(rows.at(-1).endDate),x=p=>70+(Date.parse(p.endDate)-start)/Math.max(1,end-start)*800,y=v=>220-(v-lo)/(hi-lo)*175;
    const grid=[0,1,2].map(i=>{const v=hi-(hi-lo)*i/2;return '<line x1="70" x2="890" y1="'+y(v)+'" y2="'+y(v)+'" stroke="#e8ecf3"/><text x="58" y="'+(y(v)+4)+'" text-anchor="end">'+fmt(v,2)+'</text>';}).join('');
    const marks=M.groups(rows,m.frequency).map(group=>'<polyline points="'+group.map(p=>x(p)+','+y(p.value)).join(' ')+'" fill="none" stroke="#555cab" stroke-width="2.5"/>').join('')+rows.map(p=>'<circle cx="'+x(p)+'" cy="'+y(p.value)+'" r="3" fill="#555cab"><title>'+esc(p.periodLabel+'：'+fmt(p.value,m.precision)+' '+m.unit)+'</title></circle>').join('');
    return '<svg class="sector-chart" viewBox="0 0 940 265" role="img" aria-label="'+esc(m.label)+'"><title>'+esc(m.label+' · '+m.unit)+'</title>'+grid+marks+'<text x="70" y="250">'+esc(rows[0].period)+'</text><text x="890" y="250" text-anchor="end">'+esc(rows.at(-1).period)+'</text></svg>';
  }
  function cards(){ $('core').innerHTML=data.core.map(id=>{const m=data.metrics.find(x=>x.id===id),p=M.latest(m);return '<button data-metric="'+esc(id)+'" aria-pressed="'+(id===metric)+'"><span>'+esc(m.label)+'</span><strong>'+fmt(p?.value,m.precision)+'<small>'+esc(m.unit)+'</small></strong><span>'+esc(p?.periodLabel||'暂无数据')+'</span><small>'+esc(m.frequency)+(p&&Number.isFinite(p.change)?' · 同比 '+fmt(p.change,1)+'%':'')+'</small></button>';}).join('');}
  function resetBasis(){if(!$('sector-chart-mode')){const label=document.createElement('label');label.className='site-chart-mode';label.innerHTML='显示 <select id="sector-chart-mode"><option value="combo">数值＋同比</option><option value="value">仅数值</option><option value="change">仅同比</option></select>';$('chart').before(label);$('sector-chart-mode').onchange=render;} const m=active(),bases=[...new Set(m.points.map(p=>p.basis))];$('basis').innerHTML=bases.map(b=>'<option value="'+esc(b)+'">'+esc(M.basisLabels[b]||b)+'</option>').join('');$('basis').value=bases.includes('monthly')?'monthly':bases[0]||'';}
  function selectMetric(id){metric=id;$('metric').value=id;resetBasis();page=1;cards();render();}
  function history(){const rows=chosenPoints().reverse(),m=active(),pages=Math.max(1,Math.ceil(rows.length/size));page=Math.min(page,pages);$('history').innerHTML=rows.slice((page-1)*size,page*size).map(p=>'<tr><td>'+esc(p.periodLabel)+'<small>'+esc(M.basisLabels[p.basis]||p.basis)+'</small></td><td>'+fmt(p.value,m.precision)+'</td><td>'+fmt(p.change,2)+'</td><td>'+sourceLink(p.sourceId)+'<small>'+esc(quality[p.quality]||p.quality)+' · '+esc(p.status||'')+'</small></td></tr>').join('')||'<tr><td colspan="4">当前筛选暂无数据</td></tr>';$('history-unit').textContent='数值 · '+m.unit;$('page-label').textContent=page+' / '+pages+' · '+rows.length+'条';$('prev').disabled=page<=1;$('next').disabled=page>=pages;}
  function render(){const m=active(),rows=chosenPoints();$('sector-chart-mode').parentElement.hidden=m.unit==='%'||!rows.some(p=>Number.isFinite(p.change));const last=rows.at(-1),s=last?sources[last.sourceId]:{};$('metric-title').textContent=m.label;$('chart').innerHTML=chart(rows,m);$('scope').textContent=m.scope+(m.scopeNote?' · '+m.scopeNote:'');$('metric-meta').innerHTML='<span>'+esc(m.unit)+' · '+esc(m.frequency)+'</span><span>'+rows.length+'条 · '+esc(rows[0]?.period||'—')+' 至 '+esc(last?.period||'—')+'</span>'+(last?sourceLink(last.sourceId):'');$('publication').textContent=last?'发布 '+(s.publishedAt||'暂无')+' · 核对 '+(s.retrievedAt||'暂无')+(s.vintage?' · '+s.vintage:''):'';history();}
  function companyFilters(){return {company:$('company').value,period:$('company-period').value,q:$('company-search').value.trim()};}
  function companies(){const rows=M.companyRows(data,companyFilters()),map=Object.fromEntries(data.companies.map(c=>[c.id,c])),pages=Math.max(1,Math.ceil(rows.length/size));companyPage=Math.min(companyPage,pages);$('company-history').innerHTML=rows.slice((companyPage-1)*size,companyPage*size).map(p=>'<tr><td>'+esc(map[p.companyId].name)+'<small>'+esc(p.period)+' · '+esc(M.basisLabels[p.basis]||p.basis)+'</small></td><td>'+esc(p.label)+'<small>'+esc(p.scope)+'</small></td><td>'+fmt(p.value,p.precision)+'<small>'+esc(p.unit)+'</small></td><td>'+sourceLink(p.sourceId)+(p.calculation?'<small>计算值 · '+esc(p.calculation)+'</small>':'')+'</td></tr>').join('')||'<tr><td colspan="4">当前筛选暂无公司数据</td></tr>';$('company-page').textContent=companyPage+' / '+pages+' · '+rows.length+'条';$('company-prev').disabled=companyPage<=1;$('company-next').disabled=companyPage>=pages;}
  function view(id){const valid=['market','companies','research','sources'].includes(id)?id:'market';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===valid)));document.querySelectorAll('.sector-view').forEach(p=>p.hidden=p.id!=='view-'+valid);window.history.replaceState(null,'','#'+valid);}
  function provenance(){ $('source-list').innerHTML=data.sources.map(s=>'<article class="sector-source">'+sourceLink(s.id)+'<p>'+esc(s.publisher||s.provider)+' · '+esc(quality[s.quality]||s.quality)+'</p><p>发布日期 '+esc(s.publishedAt||'暂无')+' · 采集/核对 '+esc(s.retrievedAt||'暂无')+'</p><p>'+esc(s.locator||'')+'</p>'+(s.vintage?'<p>'+esc(s.vintage)+'</p>':'')+'</article>').join('');$('gaps').innerHTML=data.gaps.map(g=>'<article><strong>'+esc(g.metric)+'</strong><p>'+esc(g.reason)+'</p></article>').join('');$('revisions').innerHTML=data.revisions.length?'<p class="sector-count">'+data.revisions.length+'条 · <a href="data/sectors/'+sid+'.json">查看修订记录 ↗</a></p>':'<p class="sector-count">暂无数值修订</p>';$('reports').innerHTML=data.research.map(r=>'<article class="sector-report"><div><a href="'+esc(D.link(r.url))+'" target="_blank" rel="noopener">'+esc(r.title)+' ↗</a><p>'+esc(r.focus.join(' · '))+'</p><p>'+esc(r.locator)+'</p></div><time>'+esc(r.publishedAt)+'</time></article>').join('');}
  $('retry').onclick=()=>location.reload();
  try{data=await D.json('data/sectors/'+sid+'.json');sources=Object.fromEntries(data.sources.map(s=>[s.id,s]));if(!data.metrics.length)throw Error('empty');$('title').textContent=data.name;$('checked').textContent='核对 '+data.checkedAt;$('metric').innerHTML=data.metrics.map(m=>'<option value="'+esc(m.id)+'">'+esc(m.label)+' · '+esc(m.frequency)+'</option>').join('');$('company').innerHTML='<option value="">全部公司</option>'+data.companies.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join('');$('company-period').innerHTML='<option value="">全部报告期</option>'+[...new Set(data.companyObservations.map(p=>p.period))].sort().reverse().map(p=>'<option>'+esc(p)+'</option>').join('');$('company-links').innerHTML=data.companies.map(c=>'<a href="companies.html?company='+encodeURIComponent(c.code)+'">'+esc(c.name)+' · '+esc(c.code)+' ↗</a>').join('');
    const requested=params.get('company');if(data.companies.some(c=>c.id===requested))$('company').value=requested;
    provenance();selectMetric(data.metrics.some(m=>m.id===params.get('metric'))?params.get('metric'):data.defaultMetric);companies();$('status').hidden=true;$('content').hidden=false;view(location.hash.slice(1));
    $('core').onclick=e=>{const b=e.target.closest('[data-metric]');if(b)selectMetric(b.dataset.metric);};$('metric').onchange=()=>selectMetric($('metric').value);for(const id of ['basis','from','to'])$(id).onchange=()=>{page=1;render();};$('clear-range').onclick=()=>{$('from').value='';$('to').value='';page=1;render();};$('prev').onclick=()=>{page--;history();};$('next').onclick=()=>{page++;history();};$('download').onclick=()=>{const m=active();download(M.csv(chosenPoints().map(p=>({...p,label:m.label,unit:m.unit,scope:m.scope})),sources),sid+'-'+m.id+'.csv');};
    for(const id of ['company','company-period'])$(id).onchange=()=>{companyPage=1;companies();};$('company-search').oninput=()=>{companyPage=1;companies();};$('company-prev').onclick=()=>{companyPage--;companies();};$('company-next').onclick=()=>{companyPage++;companies();};$('company-download').onclick=()=>{const map=Object.fromEntries(data.companies.map(c=>[c.id,c.name]));download(M.csv(M.companyRows(data,companyFilters()).map(p=>({...p,label:map[p.companyId]+' / '+p.label})),sources),sid+'-companies.csv');};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));window.addEventListener('hashchange',()=>view(location.hash.slice(1)));
    // Industry and related company snapshots are independent of update transport status.
    D.json('data/sectors/update-status.json').then(s=>{if(s.status==='failed')$('checked').textContent+=' · 最近更新失败，保留历史';}).catch(()=>{});
  }catch(e){$('status-text').textContent='板块数据暂时无法读取。';$('retry').hidden=false;}
})();
